# -*- coding: utf-8 -*-
"""Fiche 10 — consommation, refaite au nouveau standard.
   Cinq blocs : 2 raisons pour · 1 raison contre · conclusion.
   Introduction en cinq mouvements."""

L = [("INTRODUCTION","lb-intro"),
     ("PREMIÈRE RAISON — POUR","lb-arg"),
     ("DEUXIÈME RAISON — POUR","lb-arg"),
     ("MAIS — L'AUTRE CÔTÉ","lb-arg"),
     ("CONCLUSION","lb-conc")]

# ── B1 : le niveau qu'elle va enseigner ──
B1 = [
 (*L[0], [
  ("La consommation occupe aujourd'hui", "مصرف امروزه جا دارد"),
  ("une place centrale dans les pays riches.", "جایگاهی مرکزی در کشورهای ثروتمند."),
  ("En quelques minutes,", "در چند دقیقه،"),
  ("on peut commander un vêtement,", "می‌شود یک لباس سفارش داد،"),
  ("un téléphone ou même un repas.", "یک تلفن یا حتی یک وعده غذا."),
  ("Certains estiment que cette facilité", "بعضی‌ها معتقدند این آسانی"),
  ("améliore vraiment la vie quotidienne ;", "زندگیِ روزمره را واقعاً بهتر می‌کند؛"),
  ("d'autres, au contraire, pensent", "بعضی دیگر، برعکس، فکر می‌کنند"),
  ("qu'elle pousse les gens à acheter sans réfléchir.", "که آدم‌ها را به خریدِ بی‌فکر می‌راند."),
  ("Face à ces deux positions,", "در برابرِ این دو موضع،"),
  ("il est légitime de se demander", "مشروع است که بپرسیم"),
  ("si nos habitudes de consommation sont raisonnables.", "آیا عادت‌های مصرفیِ ما معقول‌اند."),
  ("Pour ma part, je considère", "از نظرِ من،"),
  ("qu'elles posent un vrai problème,", "این عادت‌ها مشکلی واقعی می‌سازند،"),
  ("mais que chacun peut agir à son niveau.", "اما هر کس در حدِ خودش می‌تواند کاری کند."),
  ("Je vais donner deux raisons pour,", "دو دلیلِ موافق می‌آورم،"),
  ("et une raison contre.", "و یک دلیلِ مخالف."),
 ]),
 (*L[1], [
  ("Premièrement, la publicité pousse les gens", "اول، تبلیغات آدم‌ها را می‌راند"),
  ("à acheter des choses inutiles.", "به خریدنِ چیزهای بی‌فایده."),
  ("En effet, les marques créent un besoin", "در واقع، برندها نیازی می‌سازند"),
  ("qui n'existait pas avant.", "که قبلاً وجود نداشت."),
  ("Par exemple, beaucoup de personnes", "برای مثال، خیلی‌ها"),
  ("changent de téléphone tous les deux ans,", "هر دو سال تلفنشان را عوض می‌کنند،"),
  ("alors que l'ancien fonctionne encore très bien.", "درحالی‌که قبلی هنوز خیلی خوب کار می‌کند."),
  ("Elles le gardent dans un tiroir", "قبلی را در کشو نگه می‌دارند"),
  ("et achètent le nouveau modèle.", "و مدلِ تازه را می‌خرند."),
  ("C'est pourquoi les familles dépensent beaucoup d'argent", "برای همین خانواده‌ها پولِ زیادی خرج می‌کنند"),
  ("pour remplacer des objets qui marchent.", "برای عوض کردنِ چیزهایی که کار می‌کنند."),
 ]),
 (*L[2], [
  ("Deuxièmement, cette façon de consommer", "دوم، این شیوه‌ی مصرف"),
  ("a un impact direct sur l'environnement.", "تأثیرِ مستقیمی بر محیط زیست دارد."),
  ("En effet, chaque objet demande des matières premières,", "در واقع، هر شیء مواد اولیه می‌خواهد،"),
  ("de l'eau et beaucoup de transport.", "آب و حمل‌ونقلِ زیاد."),
  ("Prenons l'exemple des vêtements :", "مثالِ لباس را در نظر بگیریم:"),
  ("on en achète de plus en plus,", "هرچه بیشتر می‌خریم،"),
  ("on les garde de moins en moins longtemps,", "هرچه کمتر نگهشان می‌داریم،"),
  ("et une grande partie finit à la poubelle.", "و بخشِ زیادی سر از سطل درمی‌آورد."),
  ("De plus, ces produits viennent souvent de très loin.", "به‌علاوه، این کالاها اغلب از راهِ دور می‌آیند."),
  ("C'est pourquoi les déchets augmentent chaque année", "برای همین زباله‌ها هر سال بیشتر می‌شوند"),
  ("dans les pays développés.", "در کشورهای توسعه‌یافته."),
 ]),
 (*L[3], [
  ("Cependant, il faut reconnaître", "با این حال، باید پذیرفت"),
  ("que consommer n'est pas mauvais en soi.", "که مصرف کردن ذاتاً بد نیست."),
  ("En effet, la consommation fait vivre des entreprises", "در واقع، مصرف شرکت‌ها را زنده نگه می‌دارد"),
  ("et crée des millions d'emplois.", "و میلیون‌ها شغل می‌سازد."),
  ("Par exemple, quand un magasin ferme,", "برای مثال، وقتی مغازه‌ای می‌بندد،"),
  ("des employés perdent leur travail", "کارمندانی کارشان را از دست می‌دهند"),
  ("et un quartier perd son commerce.", "و محله‌ای مغازه‌اش را."),
  ("Il ne faut pas oublier non plus", "این را هم نباید فراموش کرد"),
  ("que les produits durables coûtent souvent plus cher.", "که کالای بادوام اغلب گران‌تر است."),
  ("C'est pourquoi le vrai problème", "برای همین مشکلِ واقعی"),
  ("n'est pas d'acheter, mais d'acheter sans réfléchir.", "خریدن نیست، خریدنِ بی‌فکر است."),
 ]),
 (*L[4], [
  ("Pour conclure, je pense", "برای جمع‌بندی، فکر می‌کنم"),
  ("que nos habitudes de consommation doivent changer.", "که عادت‌های مصرفیِ ما باید عوض شوند."),
  ("Il ne faut pas culpabiliser les gens,", "نباید آدم‌ها را سرزنش کرد،"),
  ("mais il faut mieux les informer.", "بلکه باید بهتر آگاهشان کرد."),
  ("Beaucoup de gestes ne coûtent rien :", "خیلی کارها هیچ هزینه‌ای ندارند:"),
  ("réparer, emprunter ou acheter d'occasion.", "تعمیر، قرض گرفتن یا خریدِ دستِ‌دوم."),
  ("En fin de compte, mieux vaut acheter moins souvent", "در نهایت، بهتر است کمتر بخریم"),
  ("et garder ses objets beaucoup plus longtemps.", "و چیزهایمان را خیلی بیشتر نگه داریم."),
 ]),
]

# ── A1 : même plan, langue simple ──
A1 = [
 (*L[0], [
  ("Aujourd'hui, on achète beaucoup", "امروزه، خیلی خرید می‌کنیم"),
  ("dans les pays riches.", "در کشورهای ثروتمند."),
  ("En cinq minutes,", "در پنج دقیقه،"),
  ("on peut commander un vêtement ou un téléphone.", "می‌شود لباس یا تلفن سفارش داد."),
  ("Certaines personnes disent que c'est très pratique.", "بعضی‌ها می‌گویند خیلی کاربردی است."),
  ("D'autres disent qu'on achète trop.", "بعضی می‌گویند زیادی می‌خریم."),
  ("Alors, est-ce que nos habitudes sont raisonnables ?", "خب، آیا عادت‌های ما معقول‌اند؟"),
  ("À mon avis, non, il y a un problème.", "به نظرِ من، نه، مشکلی هست."),
  ("Mais chacun peut faire quelque chose.", "اما هر کس می‌تواند کاری بکند."),
  ("Je vais donner deux raisons pour,", "دو دلیلِ موافق می‌آورم،"),
  ("et une raison contre.", "و یک دلیلِ مخالف."),
 ]),
 (*L[1], [
  ("Premièrement, la publicité est partout.", "اول، تبلیغات همه‌جا هست."),
  ("Elle donne envie d'acheter.", "آدم را به خرید مشتاق می‌کند."),
  ("Par exemple, beaucoup de gens", "برای مثال، خیلی‌ها"),
  ("changent de téléphone tous les deux ans.", "هر دو سال تلفنشان را عوض می‌کنند."),
  ("Mais l'ancien téléphone marche encore bien.", "اما تلفنِ قبلی هنوز خوب کار می‌کند."),
  ("Alors on dépense beaucoup d'argent", "پس پولِ زیادی خرج می‌کنیم"),
  ("pour rien.", "بی‌جهت."),
 ]),
 (*L[2], [
  ("Deuxièmement, c'est mauvais pour la planète.", "دوم، برای کره‌ی زمین بد است."),
  ("Chaque objet demande de l'eau", "هر شیء آب می‌خواهد"),
  ("et beaucoup de transport.", "و حمل‌ونقلِ زیاد."),
  ("Par exemple, les vêtements :", "برای مثال، لباس:"),
  ("on achète beaucoup", "زیاد می‌خریم"),
  ("et on jette vite.", "و زود دور می‌ریزیم."),
  ("Alors il y a de plus en plus de déchets.", "پس زباله هرچه بیشتر می‌شود."),
 ]),
 (*L[3], [
  ("Cependant, acheter n'est pas toujours mauvais.", "با این حال، خریدن همیشه بد نیست."),
  ("Les magasins donnent du travail aux gens.", "مغازه‌ها به مردم کار می‌دهند."),
  ("Par exemple, quand un magasin ferme,", "برای مثال، وقتی مغازه‌ای می‌بندد،"),
  ("des employés perdent leur travail.", "کارمندانی کارشان را از دست می‌دهند."),
  ("C'est vrai, je suis d'accord.", "درست است، موافقم."),
  ("Mais le problème,", "اما مشکل،"),
  ("c'est d'acheter sans réfléchir.", "خریدنِ بی‌فکر است."),
 ]),
 (*L[4], [
  ("Pour conclure, je pense", "برای جمع‌بندی، فکر می‌کنم"),
  ("qu'il faut acheter moins.", "که باید کمتر خرید کرد."),
  ("On peut réparer les objets.", "می‌شود چیزها را تعمیر کرد."),
  ("On peut aussi acheter d'occasion.", "می‌شود دستِ‌دوم هم خرید."),
  ("C'est bon pour l'argent", "هم برای پول خوب است"),
  ("et pour la planète.", "هم برای زمین."),
 ]),
]

# ── B2 : même plan, langue riche ──
B2 = [
 (*L[0], [
  ("La consommation occupe aujourd'hui une place centrale", "مصرف امروزه جایگاهی مرکزی دارد"),
  ("dans le fonctionnement des pays riches.", "در کارکردِ کشورهای ثروتمند."),
  ("Acheter est devenu si simple", "خرید آن‌قدر ساده شده"),
  ("que quelques minutes suffisent", "که چند دقیقه کافی است"),
  ("pour commander un vêtement ou un appareil.", "برای سفارشِ یک لباس یا یک دستگاه."),
  ("Certains estiment que cette facilité", "بعضی‌ها معتقدند این آسانی"),
  ("représente un progrès réel pour la vie quotidienne ;", "پیشرفتی واقعی برای زندگیِ روزمره است؛"),
  ("d'autres, au contraire, dénoncent", "بعضی دیگر، برعکس، محکوم می‌کنند"),
  ("une société qui pousse à acheter sans réfléchir.", "جامعه‌ای را که به خریدِ بی‌فکر می‌راند."),
  ("Face à ces deux positions,", "در برابرِ این دو موضع،"),
  ("il est légitime de se demander", "مشروع است که بپرسیم"),
  ("si nos habitudes de consommation restent raisonnables.", "آیا عادت‌های مصرفیِ ما معقول می‌مانند."),
  ("Pour ma part, je considère", "از نظرِ من،"),
  ("qu'elles posent un problème sérieux,", "این عادت‌ها مشکلی جدی می‌سازند،"),
  ("sans pour autant condamner la consommation elle-même.", "بی‌آنکه خودِ مصرف را محکوم کنم."),
  ("C'est ce que je voudrais montrer par deux arguments,", "این را با دو استدلال نشان می‌دهم،"),
  ("avant d'examiner une objection.", "پیش از آنکه به یک ایراد بپردازم."),
 ]),
 (*L[1], [
  ("Premièrement, la publicité pousse les consommateurs", "اول، تبلیغات مصرف‌کننده‌ها را می‌راند"),
  ("à acheter des objets dont ils n'ont pas besoin.", "به خریدنِ چیزهایی که لازمشان ندارند."),
  ("En effet, les marques créent un besoin", "در واقع، برندها نیازی می‌سازند"),
  ("qui n'existait pas auparavant,", "که پیش‌تر وجود نداشت،"),
  ("et les réseaux sociaux montrent en permanence", "و شبکه‌های اجتماعی مدام نشان می‌دهند"),
  ("ce que les autres possèdent.", "دیگران چه دارند."),
  ("Par exemple, de nombreuses personnes", "برای مثال، خیلی‌ها"),
  ("changent de téléphone tous les deux ans,", "هر دو سال تلفنشان را عوض می‌کنند،"),
  ("alors que l'ancien fonctionne parfaitement.", "درحالی‌که قبلی بی‌نقص کار می‌کند."),
  ("C'est pourquoi les ménages dépensent des sommes importantes", "برای همین خانوارها مبالغِ مهمی خرج می‌کنند"),
  ("pour remplacer des objets en bon état,", "برای عوض کردنِ چیزهای سالم،"),
  ("et cette habitude finit par paraître normale.", "و این عادت آخرش عادی به نظر می‌رسد."),
 ]),
 (*L[2], [
  ("Deuxièmement, ce mode de consommation", "دوم، این شیوه‌ی مصرف"),
  ("a un impact considérable sur l'environnement.", "تأثیرِ چشمگیری بر محیط زیست دارد."),
  ("En effet, chaque produit exige des matières premières,", "در واقع، هر کالا مواد اولیه می‌خواهد،"),
  ("de l'eau et des milliers de kilomètres de transport", "آب و هزاران کیلومتر حمل‌ونقل"),
  ("avant d'arriver chez nous.", "پیش از رسیدن به دستِ ما."),
  ("Prenons l'exemple du textile :", "مثالِ پوشاک را در نظر بگیریم:"),
  ("on achète de plus en plus de vêtements,", "هرچه بیشتر لباس می‌خریم،"),
  ("on les conserve de moins en moins longtemps,", "هرچه کمتر نگهشان می‌داریم،"),
  ("et une grande partie finit à la poubelle après quelques mois.", "و بخشِ زیادی بعد از چند ماه سر از سطل درمی‌آورد."),
  ("C'est pourquoi le volume des déchets augmente chaque année", "برای همین حجمِ زباله هر سال بیشتر می‌شود"),
  ("dans les pays développés,", "در کشورهای توسعه‌یافته،"),
  ("alors même que la population n'augmente presque plus.", "درحالی‌که جمعیت تقریباً دیگر زیاد نمی‌شود."),
 ]),
 (*L[3], [
  ("Cependant, il faut reconnaître", "با این حال، باید پذیرفت"),
  ("que consommer n'est pas mauvais en soi.", "که مصرف کردن ذاتاً بد نیست."),
  ("En effet, la consommation fait vivre les entreprises", "در واقع، مصرف شرکت‌ها را زنده نگه می‌دارد"),
  ("et crée des millions d'emplois dans tous les secteurs.", "و در همه‌ی بخش‌ها میلیون‌ها شغل می‌سازد."),
  ("Par exemple, lorsqu'un magasin ferme,", "برای مثال، وقتی مغازه‌ای می‌بندد،"),
  ("ce sont des employés qui perdent leur travail", "کارمندانی‌اند که کارشان را از دست می‌دهند"),
  ("et un quartier qui perd son commerce de proximité.", "و محله‌ای که مغازه‌ی نزدیکش را."),
  ("Il ne faut pas oublier non plus", "این را هم نباید فراموش کرد"),
  ("que les produits durables coûtent souvent plus cher", "که کالای بادوام اغلب گران‌تر است"),
  ("et restent hors de portée des familles modestes.", "و از دسترسِ خانواده‌های کم‌درآمد خارج می‌مانَد."),
  ("C'est pourquoi le véritable problème", "برای همین مشکلِ واقعی"),
  ("n'est pas d'acheter, mais d'acheter sans réfléchir.", "خریدن نیست، خریدنِ بی‌فکر است."),
 ]),
 (*L[4], [
  ("Pour conclure, je pense", "برای جمع‌بندی، فکر می‌کنم"),
  ("que nos habitudes de consommation doivent évoluer.", "که عادت‌های مصرفیِ ما باید تحول پیدا کنند."),
  ("Il ne s'agit pas de culpabiliser les consommateurs,", "بحث سرزنشِ مصرف‌کننده‌ها نیست،"),
  ("mais de mieux les informer.", "بلکه بهتر آگاه کردنشان است."),
  ("Beaucoup de gestes simples ne coûtent rien :", "خیلی کارهای ساده هیچ هزینه‌ای ندارند:"),
  ("réparer, emprunter ou acheter d'occasion.", "تعمیر، قرض گرفتن یا خریدِ دستِ‌دوم."),
  ("En fin de compte, mieux vaut acheter moins souvent,", "در نهایت، بهتر است کمتر بخریم،"),
  ("choisir avec soin", "با دقت انتخاب کنیم"),
  ("et conserver ses objets beaucoup plus longtemps.", "و چیزهایمان را خیلی بیشتر نگه داریم."),
 ]),
]
