// ═══════════════════════════════════════════════════════════════
//  BLOCS & COLLOCATIONS — fiches pour les élèves
//  But : casser l'habitude de traduire depuis le persan/l'anglais.
//  On n'apprend pas des mots isolés, on apprend des BLOCS.
//  Le persan ne sert qu'à comprendre une fois — jamais à produire.
// ═══════════════════════════════════════════════════════════════

const BLOCS_SUJETS = [

{
  id: 1,
  theme: 'culture',
  q: "Les loisirs culturels (musées, théâtres, etc.) devraient être gratuits. Qu'en pensez-vous ?",
  qFa: "تفریحات فرهنگی — موزه، تئاتر و مانند این‌ها — باید رایگان باشند. نظرتان چیست؟",
  these: "Favorable, mais à une condition : une gratuité ciblée, compensée par l'État.",
  theseFa: "موافق، اما به یک شرط: رایگانیِ هدفمند که دولت هزینه‌اش را جبران کند.",

  textes: {
    b2: [
      { label:"INTRODUCTION", cls:"lb-intro", segments:[
        {fr:"L'accès à la culture", fa:"دسترسی به فرهنگ"},
        {fr:"soulève aujourd'hui de nombreux débats.", fa:"امروز بحث‌های زیادی برمی‌انگیزد."},
        {fr:"Certains estiment", fa:"بعضی‌ها معتقدند"},
        {fr:"que les musées et les théâtres", fa:"که موزه‌ها و تئاترها"},
        {fr:"devraient être entièrement gratuits,", fa:"باید کاملاً رایگان باشند،"},
        {fr:"d'autres pensent", fa:"دیگران فکر می‌کنند"},
        {fr:"que cela n'est pas réaliste.", fa:"که این واقع‌بینانه نیست."},
        {fr:"Personnellement, je suis d'avis", fa:"شخصاً، بر این نظرم"},
        {fr:"que la gratuité représente un véritable atout,", fa:"که رایگانی یک برگ برنده‌ی واقعی است،"},
        {fr:"à condition qu'elle soit bien organisée.", fa:"به شرط آنکه خوب سازمان‌دهی شود."},
        {fr:"Je vais expliquer les raisons", fa:"دلایلی را توضیح می‌دهم"},
        {fr:"pour lesquelles je défends cette position.", fa:"که به‌خاطرشان از این موضع دفاع می‌کنم."},
      ]},
      { label:"ARGUMENT 1 — l'accès", cls:"lb-arg", segments:[
        {fr:"En premier lieu,", fa:"در وهله‌ی اول،"},
        {fr:"la gratuité favorise l'accès à la culture", fa:"رایگانی دسترسی به فرهنگ را تسهیل می‌کند"},
        {fr:"pour tous.", fa:"برای همه."},
        {fr:"En effet,", fa:"در واقع،"},
        {fr:"le prix d'entrée constitue souvent un obstacle", fa:"قیمتِ ورودی اغلب مانعی است"},
        {fr:"pour les familles modestes.", fa:"برای خانواده‌های کم‌درآمد."},
        {fr:"Cela s'explique notamment", fa:"این عمدتاً برمی‌گردد"},
        {fr:"par le coût élevé des billets", fa:"به هزینه‌ی بالای بلیت‌ها"},
        {fr:"dans les grandes villes.", fa:"در شهرهای بزرگ."},
        {fr:"Par exemple,", fa:"برای مثال،"},
        {fr:"une famille de quatre personnes", fa:"خانواده‌ای چهارنفره"},
        {fr:"doit parfois payer une somme importante", fa:"گاهی باید مبلغ قابل توجهی بپردازد"},
        {fr:"pour une seule visite.", fa:"برای یک بازدید."},
        {fr:"Par conséquent,", fa:"در نتیجه،"},
        {fr:"la gratuité permettrait de réduire les inégalités", fa:"رایگانی می‌تواند نابرابری‌ها را کم کند"},
        {fr:"entre les citoyens.", fa:"میان شهروندان."},
      ]},
      { label:"ARGUMENT 2 — la formation du citoyen", cls:"lb-arg", segments:[
        {fr:"Il convient également de souligner", fa:"همچنین باید تأکید کرد"},
        {fr:"que la culture joue un rôle essentiel", fa:"که فرهنگ نقشی اساسی دارد"},
        {fr:"dans la formation des citoyens.", fa:"در تربیتِ شهروندان."},
        {fr:"Fréquenter un musée", fa:"رفت‌وآمد به موزه"},
        {fr:"ou une pièce de théâtre", fa:"یا به یک نمایش"},
        {fr:"contribue à développer l'esprit critique", fa:"به رشدِ روحیه‌ی نقد کمک می‌کند"},
        {fr:"et à renforcer la cohésion sociale.", fa:"و به تقویتِ انسجام اجتماعی."},
        {fr:"Un enfant qui découvre une exposition", fa:"کودکی که نمایشگاهی را کشف می‌کند"},
        {fr:"n'apprend pas seulement des dates :", fa:"فقط تاریخ یاد نمی‌گیرد:"},
        {fr:"il apprend à observer,", fa:"یاد می‌گیرد مشاهده کند،"},
        {fr:"à comparer,", fa:"مقایسه کند،"},
        {fr:"à se poser des questions.", fa:"از خودش سؤال بپرسد."},
        {fr:"La gratuité ne représente donc pas une dépense,", fa:"پس رایگانی یک هزینه نیست،"},
        {fr:"mais un investissement à long terme.", fa:"بلکه سرمایه‌گذاری‌ای بلندمدت است."},
      ]},
      { label:"ARGUMENT 3 — l'effet réel", cls:"lb-arg", segments:[
        {fr:"Un autre aspect", fa:"جنبه‌ی دیگری"},
        {fr:"mérite d'être pris en considération :", fa:"درخورِ توجه است:"},
        {fr:"la gratuité a un impact direct", fa:"رایگانی تأثیری مستقیم دارد"},
        {fr:"sur la fréquentation.", fa:"بر میزانِ بازدید."},
        {fr:"Quand le prix disparaît,", fa:"وقتی قیمت حذف می‌شود،"},
        {fr:"les publics changent,", fa:"مخاطبان عوض می‌شوند،"},
        {fr:"et notamment les jeunes.", fa:"و به‌خصوص جوان‌ها."},
        {fr:"Par exemple,", fa:"برای مثال،"},
        {fr:"les journées gratuites", fa:"روزهای رایگان"},
        {fr:"organisées dans certains musées", fa:"که در بعضی موزه‌ها برگزار می‌شود"},
        {fr:"attirent un public beaucoup plus large", fa:"مخاطبی خیلی گسترده‌تر جذب می‌کند"},
        {fr:"et beaucoup plus varié.", fa:"و خیلی متنوع‌تر."},
        {fr:"Cela montre que la barrière", fa:"این نشان می‌دهد که مانع"},
        {fr:"n'est pas le manque d'intérêt,", fa:"نبودِ علاقه نیست،"},
        {fr:"mais bien le prix.", fa:"بلکه دقیقاً قیمت است."},
      ]},
      { label:"CONTRE-ARGUMENT", cls:"lb-arg", segments:[
        {fr:"Cela dit,", fa:"با این حال،"},
        {fr:"il ne faut pas perdre de vue", fa:"نباید از نظر دور داشت"},
        {fr:"que les institutions culturelles", fa:"که نهادهای فرهنگی"},
        {fr:"font face à de fortes contraintes budgétaires.", fa:"با محدودیت‌های شدیدِ بودجه‌ای مواجه‌اند."},
        {fr:"Si les recettes disparaissent,", fa:"اگر درآمدها از بین برود،"},
        {fr:"la qualité risque de se dégrader.", fa:"کیفیت ممکن است افت کند."},
        {fr:"Il convient donc de nuancer ce point :", fa:"پس باید این نکته را تعدیل کرد:"},
        {fr:"une gratuité totale et sans compensation", fa:"رایگانیِ کامل و بدون جبران"},
        {fr:"serait difficile à mettre en place.", fa:"اجرایش دشوار می‌بود."},
      ]},
      { label:"CONCLUSION", cls:"lb-conc", segments:[
        {fr:"Pour conclure,", fa:"برای جمع‌بندی،"},
        {fr:"je reste convaincu", fa:"همچنان معتقدم"},
        {fr:"que la gratuité constitue une mesure bénéfique,", fa:"که رایگانی اقدامی سودمند است،"},
        {fr:"à condition que l'État prenne en charge la différence.", fa:"به شرط آنکه دولت تفاوتش را به عهده بگیرد."},
        {fr:"Il serait donc souhaitable", fa:"پس مطلوب است"},
        {fr:"de mettre en place une gratuité ciblée,", fa:"که رایگانیِ هدفمند اجرا شود،"},
        {fr:"pour les jeunes, les étudiants", fa:"برای جوان‌ها، دانشجوها"},
        {fr:"et les personnes en difficulté,", fa:"و افرادِ در مضیقه،"},
        {fr:"plutôt qu'une gratuité générale.", fa:"به‌جای رایگانیِ همگانی."},
      ]},
    ],
    c1: [
      { label:"INTRODUCTION", cls:"lb-intro", segments:[
        {fr:"À l'heure où l'accès à la culture", fa:"در زمانه‌ای که دسترسی به فرهنگ"},
        {fr:"est présenté comme un droit,", fa:"به‌عنوان یک حق معرفی می‌شود،"},
        {fr:"la question de savoir", fa:"این پرسش"},
        {fr:"si les musées et les théâtres", fa:"که آیا موزه‌ها و تئاترها"},
        {fr:"devraient être gratuits", fa:"باید رایگان باشند"},
        {fr:"suscite de nombreux débats.", fa:"بحث‌های زیادی برمی‌انگیزد."},
        {fr:"Certains y voient une mesure de justice sociale,", fa:"بعضی در آن اقدامی برای عدالت اجتماعی می‌بینند،"},
        {fr:"d'autres une charge", fa:"دیگران باری"},
        {fr:"que les institutions ne pourraient pas supporter.", fa:"که نهادها تابش را ندارند."},
        {fr:"Personnellement, je suis convaincu", fa:"شخصاً، معتقدم"},
        {fr:"que la gratuité représente un enjeu majeur,", fa:"که رایگانی مسئله‌ای اساسی است،"},
        {fr:"à condition qu'elle s'accompagne", fa:"به شرط آنکه همراه شود"},
        {fr:"d'un financement public clair.", fa:"با تأمینِ مالیِ عمومیِ روشن."},
        {fr:"Je tiens à expliquer les raisons", fa:"می‌خواهم دلایلی را توضیح دهم"},
        {fr:"pour lesquelles cette nuance me paraît déterminante.", fa:"که این تفاوت را به نظرم تعیین‌کننده می‌کند."},
      ]},
      { label:"ARGUMENT 1 — l'accès", cls:"lb-arg", segments:[
        {fr:"D'emblée, il me semble", fa:"از همان ابتدا، به نظرم"},
        {fr:"que la gratuité favorise l'accès à la culture", fa:"رایگانی دسترسی به فرهنگ را تسهیل می‌کند"},
        {fr:"pour l'ensemble de la population.", fa:"برای کلِ جمعیت."},
        {fr:"En effet,", fa:"در واقع،"},
        {fr:"le prix d'entrée constitue un obstacle réel", fa:"قیمتِ ورودی مانعی واقعی است"},
        {fr:"pour les ménages modestes,", fa:"برای خانوارهای کم‌درآمد،"},
        {fr:"qui arbitrent en permanence", fa:"که دائماً در حالِ انتخاب‌اند"},
        {fr:"entre des dépenses jugées plus urgentes.", fa:"میانِ هزینه‌هایی که فوری‌تر می‌دانند."},
        {fr:"Cela s'explique notamment", fa:"این عمدتاً برمی‌گردد"},
        {fr:"par le coût cumulé d'une sortie familiale,", fa:"به هزینه‌ی روی‌هم‌رفته‌ی یک بیرون‌رفتنِ خانوادگی،"},
        {fr:"transport compris.", fa:"با احتسابِ رفت‌وآمد."},
        {fr:"Par conséquent,", fa:"در نتیجه،"},
        {fr:"supprimer ce prix reviendrait", fa:"حذفِ این قیمت یعنی"},
        {fr:"à réduire des inégalités", fa:"کم کردنِ نابرابری‌هایی"},
        {fr:"qui se creusent dès l'enfance.", fa:"که از کودکی عمیق می‌شوند."},
      ]},
      { label:"ARGUMENT 2 — la formation du citoyen", cls:"lb-arg", segments:[
        {fr:"Il convient également de souligner", fa:"همچنین باید تأکید کرد"},
        {fr:"que la culture joue un rôle déterminant", fa:"که فرهنگ نقشی تعیین‌کننده دارد"},
        {fr:"dans la formation des citoyens.", fa:"در تربیتِ شهروندان."},
        {fr:"Fréquenter une exposition", fa:"رفت‌وآمد به یک نمایشگاه"},
        {fr:"ou une salle de théâtre", fa:"یا به سالنِ تئاتر"},
        {fr:"contribue à développer l'esprit critique", fa:"به رشدِ روحیه‌ی نقد کمک می‌کند"},
        {fr:"et à renforcer la cohésion sociale.", fa:"و به تقویتِ انسجام اجتماعی."},
        {fr:"Un enfant qui découvre une œuvre", fa:"کودکی که اثری را کشف می‌کند"},
        {fr:"n'accumule pas des connaissances :", fa:"دانش انباشت نمی‌کند:"},
        {fr:"il apprend à observer,", fa:"یاد می‌گیرد مشاهده کند،"},
        {fr:"à comparer,", fa:"مقایسه کند،"},
        {fr:"à formuler un jugement.", fa:"قضاوتی صورت‌بندی کند."},
        {fr:"Dans cette perspective,", fa:"از این منظر،"},
        {fr:"la gratuité ne relève pas de la dépense,", fa:"رایگانی از جنسِ هزینه نیست،"},
        {fr:"mais bien de l'investissement.", fa:"بلکه دقیقاً از جنسِ سرمایه‌گذاری است."},
      ]},
      { label:"ARGUMENT 3 — l'effet réel", cls:"lb-arg", segments:[
        {fr:"Un dernier élément", fa:"عنصرِ آخری"},
        {fr:"mérite d'être pris en considération :", fa:"درخورِ توجه است:"},
        {fr:"l'impact de la gratuité sur la fréquentation", fa:"تأثیرِ رایگانی بر میزانِ بازدید"},
        {fr:"est mesurable.", fa:"قابلِ اندازه‌گیری است."},
        {fr:"Dès lors que la barrière tarifaire tombe,", fa:"به‌محضِ اینکه مانعِ قیمتی می‌افتد،"},
        {fr:"la composition du public se modifie,", fa:"ترکیبِ مخاطبان تغییر می‌کند،"},
        {fr:"en particulier chez les jeunes adultes.", fa:"به‌ویژه در جوانانِ بزرگسال."},
        {fr:"Les journées gratuites", fa:"روزهای رایگان"},
        {fr:"mises en place par certaines institutions", fa:"که بعضی نهادها اجرا می‌کنند"},
        {fr:"attirent ainsi un public", fa:"بدین‌ترتیب مخاطبی جذب می‌کند"},
        {fr:"sensiblement plus large et plus varié.", fa:"به‌طرزِ محسوسی گسترده‌تر و متنوع‌تر."},
        {fr:"Cela tend à prouver que l'obstacle", fa:"این نشان می‌دهد که مانع"},
        {fr:"n'est pas le désintérêt,", fa:"بی‌علاقگی نیست،"},
        {fr:"mais bien le prix.", fa:"بلکه دقیقاً قیمت است."},
      ]},
      { label:"CONTRE-ARGUMENT", cls:"lb-arg", segments:[
        {fr:"Cela dit,", fa:"با این حال،"},
        {fr:"il ne faut toutefois pas oublier", fa:"با این‌همه نباید فراموش کرد"},
        {fr:"que les institutions culturelles", fa:"که نهادهای فرهنگی"},
        {fr:"sont confrontées à de fortes contraintes budgétaires.", fa:"با محدودیت‌های شدیدِ بودجه‌ای روبه‌رویند."},
        {fr:"Si les recettes de billetterie", fa:"اگر درآمدِ فروشِ بلیت"},
        {fr:"venaient à disparaître sans contrepartie,", fa:"بدونِ جبران از بین برود،"},
        {fr:"la qualité des expositions", fa:"کیفیتِ نمایشگاه‌ها"},
        {fr:"et la conservation des collections", fa:"و نگهداریِ مجموعه‌ها"},
        {fr:"en pâtiraient.", fa:"آسیب می‌بیند."},
        {fr:"Il convient donc de nuancer ce point :", fa:"پس باید این نکته را تعدیل کرد:"},
        {fr:"une gratuité généralisée, sans compensation,", fa:"رایگانیِ همگانی، بدونِ جبران،"},
        {fr:"se révélerait difficilement soutenable.", fa:"به‌سختی قابلِ دوام از آب درمی‌آید."},
      ]},
      { label:"CONCLUSION", cls:"lb-conc", segments:[
        {fr:"Tout bien considéré,", fa:"با در نظر گرفتنِ همه‌چیز،"},
        {fr:"je reste convaincu", fa:"همچنان معتقدم"},
        {fr:"que la gratuité constitue une mesure bénéfique,", fa:"که رایگانی اقدامی سودمند است،"},
        {fr:"à condition que l'État prenne en charge le manque à gagner.", fa:"به شرط آنکه دولت درآمدِ از دست رفته را به عهده بگیرد."},
        {fr:"Il serait donc préférable", fa:"پس ترجیح دارد"},
        {fr:"de mettre en place une gratuité ciblée —", fa:"که رایگانیِ هدفمند اجرا شود —"},
        {fr:"jeunes, étudiants, publics en difficulté —", fa:"جوان‌ها، دانشجوها، مخاطبانِ در مضیقه —"},
        {fr:"plutôt qu'une mesure uniforme", fa:"به‌جای اقدامی یکسان"},
        {fr:"dont personne ne pourrait garantir la pérennité.", fa:"که هیچ‌کس دوامش را تضمین نمی‌کند."},
      ]},
    ],
  },

  // ── Les blocs, classés par fonction. C'est le cœur de la fiche. ──
  outils: {
    verbes: [
      { blocs: ["favoriser l'accès à…", "faciliter l'accès à…", "ouvrir l'accès à…", "rendre… accessible à tous"],            ex: "favoriser l'accès à la culture",              fa: "دسترسی به … را تسهیل کردن" },
      { blocs: ["contribuer à + nom/inf.", "participer à + nom", "concourir à + nom", "jouer un rôle dans + nom"],  ex: "contribuer à développer l'esprit critique",   fa: "به … کمک کردن" },
      { blocs: ["constituer un obstacle", "représenter un frein", "faire barrage à…", "être un frein à…"],          ex: "le prix constitue un obstacle réel",          fa: "مانع بودن" },
      { blocs: ["réduire les inégalités", "atténuer les écarts", "combler le fossé", "lutter contre les inégalités"],          ex: "réduire les inégalités entre les citoyens",   fa: "نابرابری‌ها را کم کردن" },
      { blocs: ["renforcer la cohésion sociale", "consolider le lien social", "resserrer les liens", "souder une société"],   ex: "la culture renforce la cohésion sociale",     fa: "انسجام اجتماعی را تقویت کردن" },
      { blocs: ["mettre en place une mesure", "instaurer un dispositif", "adopter une mesure", "déployer un dispositif"],      ex: "mettre en place une gratuité ciblée",         fa: "اقدامی را اجرا کردن" },
      { blocs: ["prendre en charge", "assumer le coût de…", "financer", "couvrir la dépense"],               ex: "l'État prend en charge la différence",        fa: "هزینه را به عهده گرفتن" },
      { blocs: ["faire face à…", "être confronté à…", "se heurter à…", "devoir composer avec…"],                   ex: "faire face à des contraintes budgétaires",    fa: "با … مواجه بودن" },
      { blocs: ["avoir un impact sur…", "avoir des conséquences sur…", "peser sur…", "influer sur…"],            ex: "avoir un impact direct sur la fréquentation", fa: "بر … تأثیر داشتن" },
      { blocs: ["se révéler + adj.", "s'avérer + adj.", "apparaître comme…", "se montrer + adj."],           ex: "se révéler difficilement soutenable",         fa: "از آب درآمدن، معلوم شدن که" }
    ],
    collocations: [
      { blocs: ["un enjeu majeur", "un enjeu de taille", "une question centrale", "un sujet de première importance"],              fa: "مسئله‌ای اساسی" },
      { blocs: ["un véritable atout", "un atout de poids", "un réel avantage", "une vraie chance"],           fa: "یک برگ برنده‌ی واقعی" },
      { blocs: ["des contraintes budgétaires", "des restrictions budgétaires", "des moyens limités", "un budget serré"],  fa: "محدودیت‌های بودجه‌ای" },
      { blocs: ["une mesure bénéfique", "une mesure salutaire", "une initiative heureuse", "une bonne décision"],         fa: "اقدامی سودمند" },
      { blocs: ["un investissement à long terme", "un investissement d'avenir", "un placement sur la durée"], fa: "سرمایه‌گذاری بلندمدت" },
      { blocs: ["la barrière tarifaire", "l'obstacle du prix", "le frein financier"],        fa: "مانعِ قیمتی" },
      { blocs: ["les recettes de billetterie", "les revenus des entrées", "le produit des ventes de billets"],  fa: "درآمدِ فروش بلیت" },
      { blocs: ["le manque à gagner", "la perte de recettes", "le déficit engendré"],           fa: "درآمدِ از دست رفته" },
      { blocs: ["un public plus large et plus varié", "une fréquentation élargie", "des publics plus divers"], fa: "مخاطبی گسترده‌تر و متنوع‌تر" },
      { blocs: ["les ménages modestes", "les familles modestes", "les foyers aux revenus limités"],         fa: "خانوارهای کم‌درآمد" }
    ],
    adjectifs: [
      { blocs: ["un obstacle réel", "un obstacle concret", "un véritable frein"],         fa: "مانعی واقعی" },
      { blocs: ["un rôle déterminant", "un rôle essentiel", "un rôle central", "un rôle de premier plan"],      fa: "نقشی تعیین‌کننده" },
      { blocs: ["un coût élevé", "un tarif prohibitif", "un prix dissuasif"],            fa: "هزینه‌ای بالا" },
      { blocs: ["une mesure bénéfique", "une mesure salutaire", "une initiative heureuse", "une bonne décision"],     fa: "اقدامی سودمند" },
      { blocs: ["une gratuité ciblée", "une gratuité sous conditions", "un tarif préférentiel"],      fa: "رایگانیِ هدفمند" },
      { blocs: ["un impact mesurable", "un effet quantifiable", "des résultats visibles"],      fa: "تأثیری قابل اندازه‌گیری" },
      { blocs: ["difficilement soutenable", "peu viable", "intenable sur la durée"], fa: "به‌سختی قابل دوام" }
    ],
    expressions: [
      { blocs: ["Il convient de souligner que…", "Il faut également noter que…", "Un autre aspect mérite d'être pris en considération…", "Par ailleurs,…"],        role: "ajouter un argument",  fa: "باید تأکید کرد که…" },
      { blocs: ["Cela s'explique notamment par…", "La raison en est simple :", "Ce phénomène s'explique par…", "Cela tient à…"],       role: "justifier",            fa: "این عمدتاً به … برمی‌گردد" },
      { blocs: ["Un autre aspect mérite d'être pris en considération…", "En deuxième lieu,…", "Il faut également tenir compte de…", "Un dernier point mérite d'être signalé…"], role: "argument suivant", fa: "جنبه‌ی دیگری هم درخور توجه است" },
      { blocs: ["Il ne faut pas perdre de vue que…", "Il ne faut toutefois pas oublier que…", "Cela dit,…", "Néanmoins,…"],    role: "nuancer",              fa: "نباید از نظر دور داشت که…" },
      { blocs: ["Il convient de nuancer ce point.", "Ce point mérite d'être nuancé.", "Il faut relativiser."],     role: "nuancer",              fa: "باید این نکته را تعدیل کرد" },
      { blocs: ["Tout bien considéré,…", "En définitive,…", "Au fond,…", "En somme,…", "Pour conclure,…"],                role: "conclure",             fa: "با در نظر گرفتن همه چیز،" },
      { blocs: ["à condition que + subj.", "à condition de + inf.", "pourvu que + subj.", "dans la mesure où + ind."],         role: "poser une condition",  fa: "به شرط آنکه…" },
      { blocs: ["Il serait souhaitable de…", "Il serait préférable de…", "Mieux vaudrait…", "Il vaut mieux + inf."],            role: "proposer",             fa: "مطلوب است که…" }
    ]
  },

  // ── L'échelle : la même idée, trois hauteurs ──
  echelle: [
    { fa: "رایگان بودن کمک می‌کند مردم بیشتر به موزه بروند.",
      simple: "La gratuité aide les gens à aller au musée.",
      b2:     "La gratuité favorise l'accès à la culture.",
      b2plus: "La gratuité favorise l'accès à la culture pour l'ensemble de la population." },
    { fa: "قیمت بلیت برای بعضی خانواده‌ها زیاد است.",
      simple: "Le prix est trop cher pour quelques familles.",
      b2:     "Le prix d'entrée constitue un obstacle pour les familles modestes.",
      b2plus: "Le prix d'entrée constitue un obstacle réel pour les ménages modestes." },
    { fa: "فرهنگ به فکر کردن آدم‌ها کمک می‌کند.",
      simple: "La culture aide les personnes à penser.",
      b2:     "La culture contribue à développer l'esprit critique.",
      b2plus: "La culture joue un rôle déterminant dans la formation des citoyens." },
    { fa: "موزه‌ها پول کافی ندارند.",
      simple: "Les musées n'ont pas assez d'argent.",
      b2:     "Les musées font face à des contraintes budgétaires.",
      b2plus: "Les institutions culturelles sont confrontées à de fortes contraintes budgétaires." },
    { fa: "دولت باید هزینه‌اش را بدهد.",
      simple: "L'État doit payer l'argent.",
      b2:     "L'État doit prendre en charge la différence.",
      b2plus: "L'État doit prendre en charge le manque à gagner." }
  ],

  // ── Le piège : ce que produit une traduction mot à mot ──
  antiTrad: [
    { faux: "Le musée est très cher pour beaucoup de personnes.",
      juste: "Le prix d'entrée constitue un obstacle pour de nombreuses familles.",
      pourquoi: "En persan on dit « موزه گران است ». En français, ce n'est pas le musée qui est cher, c'est le prix d'entrée. On nomme la chose précise, puis on lui applique un bloc." },
    { faux: "La culture donne beaucoup de choses aux gens.",
      juste: "La culture contribue à développer l'esprit critique.",
      pourquoi: "« Donner beaucoup de choses » traduit « چیزهای زیادی می‌دهد ». C'est vague. Le français d'examen attend un verbe précis + un nom précis." },
    { faux: "Le gouvernement doit donner l'argent aux musées.",
      juste: "L'État doit prendre en charge le manque à gagner.",
      pourquoi: "« Donner l'argent » est de l'anglais scolaire (give money). Le bloc naturel est « prendre en charge » + un nom de coût." },
    { faux: "Beaucoup de personnes veulent aller au musée mais ils ne peuvent pas.",
      juste: "L'obstacle n'est pas le désintérêt, mais bien le prix.",
      pourquoi: "La phrase persane décrit deux faits l'un après l'autre. Le français argumentatif oppose : « ce n'est pas X, c'est Y »." },
    { faux: "C'est un bon investissement pour le futur.",
      juste: "Il s'agit d'un investissement à long terme.",
      pourquoi: "« Pour le futur » est une traduction littérale. La collocation figée est « à long terme »." }
  ],

  // ── Ce qui se recycle ailleurs ──
  transferables: [
    { bloc: "X constitue un obstacle réel pour…",
      ailleurs: ["l'emploi : la langue constitue un obstacle réel pour les nouveaux arrivants",
                 "la santé : la distance constitue un obstacle réel pour les patients ruraux"] },
    { bloc: "X contribue à développer…",
      ailleurs: ["le sport contribue à développer l'esprit d'équipe",
                 "la lecture contribue à développer l'autonomie"] },
    { blocs: ["Il ne faut pas perdre de vue que…", "Il ne faut toutefois pas oublier que…", "Cela dit,…", "Néanmoins,…"],
      ailleurs: ["utilisable dans absolument tous les sujets, pour amener la nuance"] },
    { bloc: "…à condition que + subjonctif",
      ailleurs: ["la technologie est utile à condition qu'elle soit encadrée",
                 "le télétravail fonctionne à condition que l'entreprise l'organise"] },
    { bloc: "Il s'agit non pas d'une dépense, mais d'un investissement.",
      ailleurs: ["éducation, santé, environnement, formation — partout où l'on parle de budget public"] }
  ],

  // ── La carte du thème ──
  reseau: {
    noms: ["l'accès à la culture", "le prix d'entrée", "la billetterie", "la fréquentation",
           "les inégalités", "l'esprit critique", "la cohésion sociale", "le budget public",
           "les institutions culturelles", "le patrimoine"],
    verbes: ["favoriser", "contribuer à", "réduire", "renforcer", "financer",
             "subventionner", "élargir", "attirer", "prendre en charge", "encadrer"],
    adjectifs: ["accessible", "gratuit", "bénéfique", "déterminant", "modeste",
                "élevé", "ciblé", "durable", "varié"],
    consequences: ["une fréquentation en hausse", "un public plus varié",
                   "une réduction des inégalités", "une perte de recettes"],
    causes: ["le coût des billets", "l'éloignement géographique", "le manque d'habitude familiale"],
    solutions: ["la gratuité ciblée", "les journées gratuites", "le tarif étudiant",
                "les subventions publiques", "le pass culture"]
  },

  grammaire: [
    { structure: "à condition que + subjonctif", ex: "à condition qu'elle soit bien organisée" },
    { structure: "Si + imparfait, + conditionnel", ex: "si les recettes disparaissaient, la qualité se dégraderait" },
    { structure: "mise en relief : ce n'est pas X, c'est Y", ex: "l'obstacle n'est pas le désintérêt, mais bien le prix" },
    { structure: "nominalisation", ex: "la suppression du prix / la fréquentation des musées" },
    { structure: "voix passive", ex: "les institutions sont confrontées à des contraintes" },
    { structure: "gérondif", ex: "en supprimant le prix, on élargit le public" }
  ]
}
,

{
  id: 2,
  theme: 'fam',
  q: "Pensez-vous que l'autorité soit indispensable dans l'éducation d'un enfant ? Pourquoi ?",
  qFa: "به نظر شما آیا اقتدار در تربیت کودک ضروری است؟ چرا؟",
  these: "Oui, à condition qu'elle soit juste et bienveillante — jamais brutale.",
  theseFa: "بله، به شرط آنکه عادلانه و مهربان باشد — هرگز خشن.",

  textes: {
    b2: [
      { label:"INTRODUCTION", cls:"lb-intro", segments:[
        {fr:"Avec l'essor des méthodes éducatives modernes,", fa:"با گسترشِ روش‌های آموزشیِ مدرن،"},
        {fr:"les modèles traditionnels", fa:"الگوهای سنتی"},
        {fr:"sont de plus en plus remis en cause,", fa:"هرچه بیشتر زیر سؤال می‌روند،"},
        {fr:"et la question de l'autorité", fa:"و مسئله‌ی اقتدار"},
        {fr:"suscite de nombreux débats.", fa:"بحث‌های زیادی برمی‌انگیزد."},
        {fr:"Il est donc légitime de se demander", fa:"پس معقول است که بپرسیم"},
        {fr:"si l'autorité est vraiment indispensable", fa:"آیا اقتدار واقعاً ضروری است"},
        {fr:"pour bien élever un enfant.", fa:"برای درست تربیت کردنِ یک کودک."},
        {fr:"Certains soutiennent le contraire,", fa:"بعضی‌ها خلافش را می‌گویند،"},
        {fr:"et je comprends leur point de vue.", fa:"و دیدگاهشان را درک می‌کنم."},
        {fr:"Pourtant, je suis convaincu", fa:"با این حال، معتقدم"},
        {fr:"que l'autorité reste essentielle,", fa:"که اقتدار اساسی می‌مانَد،"},
        {fr:"à condition qu'elle soit juste", fa:"به شرط آنکه عادلانه باشد"},
        {fr:"et bienveillante.", fa:"و مهربان."},
        {fr:"Et cela pour trois raisons :", fa:"و این به سه دلیل:"},
        {fr:"elle donne à l'enfant des limites claires,", fa:"به کودک مرزهای روشن می‌دهد،"},
        {fr:"elle le prépare à la vie en société,", fa:"او را برای زندگی در جامعه آماده می‌کند،"},
        {fr:"et elle ne doit jamais se confondre", fa:"و هرگز نباید اشتباه گرفته شود"},
        {fr:"avec la sévérité.", fa:"با سختگیری."},
        {fr:"Je vais expliquer pourquoi.", fa:"توضیح می‌دهم چرا."},
      ]},
      { label:"ARGUMENT 1 — connaître ses limites", cls:"lb-arg", segments:[
        {fr:"D'emblée, je suis d'avis", fa:"از همان اول، بر این نظرم"},
        {fr:"que l'autorité permet à l'enfant", fa:"که اقتدار به کودک اجازه می‌دهد"},
        {fr:"de connaître ses limites.", fa:"مرزهایش را بشناسد."},
        {fr:"En effet,", fa:"در واقع،"},
        {fr:"les enfants cherchent naturellement", fa:"کودکان به‌طور طبیعی می‌خواهند"},
        {fr:"à tester leur environnement,", fa:"محیطشان را محک بزنند،"},
        {fr:"et sans règles claires,", fa:"و بدونِ قواعدِ روشن،"},
        {fr:"ils se sentent vite perdus.", fa:"زود گم می‌شوند."},
        {fr:"Par exemple,", fa:"برای مثال،"},
        {fr:"un cadre bien défini", fa:"چارچوبی که خوب تعریف شده"},
        {fr:"à la maison et à l'école", fa:"در خانه و در مدرسه"},
        {fr:"les aide à comprendre", fa:"کمکشان می‌کند بفهمند"},
        {fr:"ce qui est acceptable", fa:"چه چیزی پذیرفتنی است"},
        {fr:"et ce qui ne l'est pas.", fa:"و چه چیزی نیست."},
        {fr:"Il revient donc aux parents", fa:"پس بر عهده‌ی والدین است"},
        {fr:"de faire en sorte", fa:"که ترتیبی بدهند"},
        {fr:"que les règles soient cohérentes", fa:"که قواعد هماهنگ باشند"},
        {fr:"et expliquées.", fa:"و توضیح داده شده."},
        {fr:"Ce qui compte avant tout,", fa:"آنچه پیش از هر چیز مهم است،"},
        {fr:"ce n'est pas la règle elle-même :", fa:"خودِ قاعده نیست:"},
        {fr:"c'est la stabilité du cadre.", fa:"ثباتِ چارچوب است."},
        {fr:"Parce que c'est cette stabilité", fa:"چون همین ثبات است"},
        {fr:"qui rassure l'enfant", fa:"که کودک را آرام می‌کند"},
        {fr:"et qui favorise son développement.", fa:"و رشدش را تسهیل می‌کند."},
      ]},
      { label:"ARGUMENT 2 — préparer à la vie en société", cls:"lb-arg", segments:[
        {fr:"En deuxième lieu, j'estime", fa:"در وهله‌ی دوم، معتقدم"},
        {fr:"que l'autorité contribue", fa:"که اقتدار کمک می‌کند"},
        {fr:"à préparer l'enfant à la vie en société.", fa:"به آماده کردنِ کودک برای زندگی در جامعه."},
        {fr:"Cela s'explique simplement :", fa:"این را به‌سادگی می‌شود توضیح داد:"},
        {fr:"apprendre à respecter les règles familiales", fa:"یاد گرفتنِ احترام به قواعدِ خانوادگی"},
        {fr:"l'aide plus tard", fa:"بعدها کمکش می‌کند"},
        {fr:"à respecter les règles sociales.", fa:"به احترام گذاشتن به قواعدِ اجتماعی."},
        {fr:"Par exemple,", fa:"برای مثال،"},
        {fr:"un enfant habitué à un cadre", fa:"کودکی که به چارچوب عادت کرده"},
        {fr:"s'intègre plus facilement à l'école,", fa:"راحت‌تر در مدرسه جا می‌افتد،"},
        {fr:"puis dans la vie professionnelle.", fa:"و بعد در زندگیِ کاری."},
        {fr:"En grandissant dans un environnement structuré,", fa:"با بزرگ شدن در محیطی ساختارمند،"},
        {fr:"il développe le sens de la responsabilité.", fa:"حسِ مسئولیت در او رشد می‌کند."},
        {fr:"Et tout en étant encadré,", fa:"و درحالی‌که در چارچوب است،"},
        {fr:"il apprend à faire la différence", fa:"یاد می‌گیرد فرق بگذارد"},
        {fr:"entre la liberté et le laisser-aller.", fa:"میانِ آزادی و بی‌قیدی."},
      ]},
      { label:"ARGUMENT 3 — autorité n'est pas sévérité", cls:"lb-arg", segments:[
        {fr:"Un dernier point", fa:"نکته‌ی آخری"},
        {fr:"mérite d'être pris en considération :", fa:"درخورِ توجه است:"},
        {fr:"l'autorité ne doit surtout pas devenir", fa:"اقتدار به‌هیچ‌وجه نباید تبدیل شود"},
        {fr:"synonyme de sévérité excessive.", fa:"به معادلِ سختگیریِ بیش از حد."},
        {fr:"À titre d'exemple,", fa:"به‌عنوانِ نمونه،"},
        {fr:"une discipline trop rigide", fa:"انضباطی خیلی سفت‌وسخت"},
        {fr:"peut engendrer de la peur,", fa:"می‌تواند ترس ایجاد کند،"},
        {fr:"ou au contraire de la rébellion.", fa:"یا برعکس، سرکشی."},
        {fr:"Malgré la nécessité des règles,", fa:"با وجودِ ضرورتِ قواعد،"},
        {fr:"celles-ci doivent toujours s'accompagner", fa:"این‌ها همیشه باید همراه باشند"},
        {fr:"d'écoute et de dialogue.", fa:"با شنیدن و گفت‌وگو."},
        {fr:"Quand on élève un enfant", fa:"وقتی کودکی را بزرگ می‌کنیم"},
        {fr:"uniquement avec des punitions,", fa:"فقط با تنبیه،"},
        {fr:"on détruit peu à peu", fa:"کم‌کم از بین می‌بریم"},
        {fr:"sa confiance en lui.", fa:"اعتمادش به خودش را."},
        {fr:"Là encore, ce qui compte,", fa:"اینجا هم، آنچه مهم است،"},
        {fr:"c'est l'équilibre entre la fermeté", fa:"تعادل است میانِ قاطعیت"},
        {fr:"et l'écoute.", fa:"و شنیدن."},
      ]},
      { label:"CONTRE-ARGUMENT — ce que disent les autres", cls:"lb-arg", segments:[
        {fr:"Cela dit,", fa:"با این حال،"},
        {fr:"je comprends ceux qui pensent le contraire.", fa:"کسانی را که برعکس فکر می‌کنند درک می‌کنم."},
        {fr:"Ils estiment qu'un enfant", fa:"معتقدند که کودک"},
        {fr:"se construit mieux dans la liberté,", fa:"در آزادی بهتر ساخته می‌شود،"},
        {fr:"et que toute autorité", fa:"و اینکه هر اقتداری"},
        {fr:"finit par étouffer sa personnalité.", fa:"آخرش شخصیتش را خفه می‌کند."},
        {fr:"Leur argument n'est pas sans fondement :", fa:"استدلالشان بی‌پایه نیست:"},
        {fr:"beaucoup d'adultes associent encore", fa:"خیلی از بزرگ‌ترها هنوز یکی می‌دانند"},
        {fr:"autorité et rigueur absolue,", fa:"اقتدار و سختگیریِ مطلق را،"},
        {fr:"et ce modèle se transmet", fa:"و این الگو منتقل می‌شود"},
        {fr:"souvent de génération en génération.", fa:"اغلب نسل به نسل."},
        {fr:"Mais confondre l'autorité et la brutalité,", fa:"اما یکی گرفتنِ اقتدار و خشونت،"},
        {fr:"c'est justement l'erreur que je dénonce.", fa:"دقیقاً همان خطایی است که به آن اعتراض دارم."},
        {fr:"Poser un cadre,", fa:"گذاشتنِ چارچوب،"},
        {fr:"ce n'est pas priver un enfant de liberté :", fa:"محروم کردنِ کودک از آزادی نیست:"},
        {fr:"c'est lui apprendre à s'en servir.", fa:"یاد دادنِ استفاده از آن است."},
      ]},
      { label:"CONCLUSION", cls:"lb-conc", segments:[
        {fr:"Pour conclure,", fa:"برای جمع‌بندی،"},
        {fr:"les bienfaits d'une autorité bien mesurée", fa:"فایده‌های اقتداری که خوب سنجیده شده"},
        {fr:"l'emportent largement", fa:"به‌روشنی می‌چربد"},
        {fr:"sur les risques d'une absence totale de cadre.", fa:"بر خطرهای نبودِ کاملِ چارچوب."},
        {fr:"Bien qu'elle soit parfois difficile à exercer,", fa:"هرچند گاهی اعمالش سخت است،"},
        {fr:"elle reste nécessaire", fa:"لازم می‌مانَد"},
        {fr:"au bon développement de l'enfant.", fa:"برای رشدِ درستِ کودک."},
        {fr:"À condition qu'elle soit juste et expliquée,", fa:"به شرط آنکه عادلانه و توضیح‌داده‌شده باشد،"},
        {fr:"elle favorise son équilibre.", fa:"تعادلش را تقویت می‌کند."},
        {fr:"Au fond,", fa:"در نهایت،"},
        {fr:"il vaut mieux guider avec fermeté", fa:"بهتر است با قاطعیت راهنمایی کنیم"},
        {fr:"que laisser faire sans repères.", fa:"تا اینکه بی‌هیچ نشانه‌ای رها کنیم."},
        {fr:"Et l'enfant qui a connu des limites claires", fa:"و کودکی که مرزهای روشن را شناخته"},
        {fr:"est souvent celui qui, plus tard,", fa:"اغلب همان کسی است که بعدها،"},
        {fr:"saura le mieux poser les siennes.", fa:"بهتر از همه مرزهای خودش را می‌گذارد."},
      ]},
    ],
    c1: [
      { label:"INTRODUCTION", cls:"lb-intro", segments:[
        {fr:"À l'heure où les méthodes éducatives se renouvellent", fa:"در زمانه‌ای که روش‌های آموزشی نو می‌شوند"},
        {fr:"et où les modèles traditionnels", fa:"و الگوهای سنتی"},
        {fr:"sont largement remis en cause,", fa:"به‌طور گسترده زیر سؤال می‌روند،"},
        {fr:"la question de l'autorité dans l'éducation", fa:"مسئله‌ی اقتدار در تربیت"},
        {fr:"suscite de nombreux débats.", fa:"بحث‌های زیادی برمی‌انگیزد."},
        {fr:"Il est donc légitime de se demander", fa:"پس معقول است که بپرسیم"},
        {fr:"si elle demeure indispensable", fa:"آیا همچنان ضروری است"},
        {fr:"pour élever correctement un enfant.", fa:"برای درست تربیت کردنِ یک کودک."},
        {fr:"Certains soutiennent résolument le contraire,", fa:"بعضی‌ها قاطعانه خلافش را می‌گویند،"},
        {fr:"et leur position mérite qu'on s'y arrête.", fa:"و موضعشان ارزشِ درنگ دارد."},
        {fr:"Je reste néanmoins convaincu", fa:"با این‌همه معتقد می‌مانم"},
        {fr:"que l'autorité constitue un élément déterminant,", fa:"که اقتدار عنصری تعیین‌کننده است،"},
        {fr:"à condition qu'elle soit juste et bienveillante.", fa:"به شرط آنکه عادلانه و مهربان باشد."},
        {fr:"Et cela pour trois raisons :", fa:"و این به سه دلیل:"},
        {fr:"elle pose des limites lisibles,", fa:"مرزهای خوانا می‌گذارد،"},
        {fr:"elle prépare à la vie en société,", fa:"برای زندگی در جامعه آماده می‌کند،"},
        {fr:"et elle ne saurait se confondre", fa:"و نمی‌تواند اشتباه گرفته شود"},
        {fr:"avec la sévérité.", fa:"با سختگیری."},
        {fr:"Je tiens à expliquer pourquoi.", fa:"می‌خواهم توضیح دهم چرا."},
      ]},
      { label:"ARGUMENT 1 — connaître ses limites", cls:"lb-arg", segments:[
        {fr:"D'emblée, il me semble", fa:"از همان ابتدا، به نظرم"},
        {fr:"que l'autorité permet à l'enfant", fa:"اقتدار به کودک اجازه می‌دهد"},
        {fr:"de situer ses limites.", fa:"مرزهایش را جای‌گذاری کند."},
        {fr:"En effet,", fa:"در واقع،"},
        {fr:"les enfants cherchent spontanément", fa:"کودکان خودبه‌خود می‌خواهند"},
        {fr:"à éprouver leur environnement,", fa:"محیطشان را بیازمایند،"},
        {fr:"et faute de règles lisibles,", fa:"و در نبودِ قواعدِ خوانا،"},
        {fr:"ils s'y perdent rapidement.", fa:"زود در آن گم می‌شوند."},
        {fr:"Ainsi, un cadre clairement défini,", fa:"بدین‌ترتیب، چارچوبی که روشن تعریف شده،"},
        {fr:"à la maison comme à l'école,", fa:"در خانه همچون در مدرسه،"},
        {fr:"les aide à distinguer", fa:"کمکشان می‌کند تشخیص دهند"},
        {fr:"ce qui est acceptable", fa:"آنچه پذیرفتنی است"},
        {fr:"de ce qui ne l'est pas.", fa:"را از آنچه نیست."},
        {fr:"Il revient donc aux parents", fa:"پس بر عهده‌ی والدین است"},
        {fr:"de veiller à ce que les règles", fa:"که مراقب باشند قواعد"},
        {fr:"soient cohérentes et explicitées.", fa:"هماهنگ و تشریح‌شده باشند."},
        {fr:"Ce qui compte avant tout,", fa:"آنچه پیش از هر چیز مهم است،"},
        {fr:"ce n'est pas la règle en elle-même :", fa:"خودِ قاعده نیست:"},
        {fr:"c'est la stabilité du cadre.", fa:"ثباتِ چارچوب است."},
        {fr:"Car c'est cette stabilité", fa:"چون همین ثبات است"},
        {fr:"qui rassure l'enfant", fa:"که کودک را آرام می‌کند"},
        {fr:"et favorise son développement.", fa:"و رشدش را تسهیل می‌کند."},
      ]},
      { label:"ARGUMENT 2 — préparer à la vie en société", cls:"lb-arg", segments:[
        {fr:"En deuxième lieu, j'estime", fa:"در وهله‌ی دوم، معتقدم"},
        {fr:"que l'autorité contribue", fa:"که اقتدار کمک می‌کند"},
        {fr:"à préparer l'enfant à la vie en société.", fa:"به آماده کردنِ کودک برای زندگی در جامعه."},
        {fr:"Cela s'explique aisément :", fa:"این را به‌راحتی می‌شود توضیح داد:"},
        {fr:"apprendre à respecter les règles familiales", fa:"یاد گرفتنِ احترام به قواعدِ خانوادگی"},
        {fr:"prépare au respect des règles sociales.", fa:"برای احترام به قواعدِ اجتماعی آماده می‌کند."},
        {fr:"Un enfant habitué à un cadre", fa:"کودکی که به چارچوب عادت کرده"},
        {fr:"s'intègre ainsi plus aisément à l'école,", fa:"بدین‌ترتیب راحت‌تر در مدرسه جا می‌افتد،"},
        {fr:"puis dans la vie professionnelle.", fa:"و بعد در زندگیِ کاری."},
        {fr:"En grandissant dans un environnement structuré,", fa:"با بزرگ شدن در محیطی ساختارمند،"},
        {fr:"il développe le sens des responsabilités.", fa:"حسِ مسئولیت‌پذیری در او رشد می‌کند."},
        {fr:"Et tout en étant encadré,", fa:"و درحالی‌که در چارچوب است،"},
        {fr:"il apprend à distinguer la liberté", fa:"یاد می‌گیرد آزادی را تشخیص دهد"},
        {fr:"du laisser-aller.", fa:"از بی‌قیدی."},
      ]},
      { label:"ARGUMENT 3 — autorité n'est pas sévérité", cls:"lb-arg", segments:[
        {fr:"Un dernier élément", fa:"عنصرِ آخری"},
        {fr:"mérite d'être pris en considération :", fa:"درخورِ توجه است:"},
        {fr:"l'autorité ne saurait devenir", fa:"اقتدار نمی‌تواند تبدیل شود"},
        {fr:"synonyme de sévérité excessive.", fa:"به معادلِ سختگیریِ بیش از حد."},
        {fr:"À titre d'exemple,", fa:"به‌عنوانِ نمونه،"},
        {fr:"une discipline trop rigide", fa:"انضباطی خیلی سفت‌وسخت"},
        {fr:"risque d'engendrer la peur,", fa:"خطرِ ایجادِ ترس دارد،"},
        {fr:"ou au contraire la rébellion.", fa:"یا برعکس، سرکشی."},
        {fr:"Malgré la nécessité des règles,", fa:"با وجودِ ضرورتِ قواعد،"},
        {fr:"celles-ci doivent toujours s'accompagner", fa:"این‌ها همیشه باید همراه باشند"},
        {fr:"d'écoute et de dialogue.", fa:"با شنیدن و گفت‌وگو."},
        {fr:"Élever un enfant à coups de punitions", fa:"بزرگ کردنِ کودک با ضربِ تنبیه"},
        {fr:"revient à miner peu à peu", fa:"یعنی کم‌کم فرسودنِ"},
        {fr:"sa confiance en lui.", fa:"اعتمادش به خودش."},
        {fr:"Là encore, ce qui compte,", fa:"اینجا هم، آنچه مهم است،"},
        {fr:"c'est l'équilibre entre la fermeté", fa:"تعادل است میانِ قاطعیت"},
        {fr:"et l'écoute.", fa:"و شنیدن."},
      ]},
      { label:"CONTRE-ARGUMENT — ce que disent les autres", cls:"lb-arg", segments:[
        {fr:"Cela dit,", fa:"با این حال،"},
        {fr:"je comprends ceux qui défendent la position inverse.", fa:"کسانی را که از موضعِ مقابل دفاع می‌کنند درک می‌کنم."},
        {fr:"Ils considèrent qu'un enfant", fa:"معتقدند که کودک"},
        {fr:"se construit mieux dans la liberté", fa:"در آزادی بهتر ساخته می‌شود"},
        {fr:"et que toute autorité", fa:"و اینکه هر اقتداری"},
        {fr:"finit par étouffer sa personnalité.", fa:"آخرش شخصیتش را خفه می‌کند."},
        {fr:"Leur argument n'est pas sans fondement :", fa:"استدلالشان بی‌پایه نیست:"},
        {fr:"bien des adultes associent encore", fa:"بسیاری از بزرگ‌ترها هنوز یکی می‌دانند"},
        {fr:"autorité et rigueur absolue,", fa:"اقتدار و سختگیریِ مطلق را،"},
        {fr:"et ce modèle se transmet", fa:"و این الگو منتقل می‌شود"},
        {fr:"de génération en génération.", fa:"نسل به نسل."},
        {fr:"Mais confondre autorité et brutalité,", fa:"اما یکی گرفتنِ اقتدار و خشونت،"},
        {fr:"c'est précisément l'erreur que je dénonce.", fa:"دقیقاً همان خطایی است که به آن اعتراض دارم."},
        {fr:"Poser un cadre,", fa:"گذاشتنِ چارچوب،"},
        {fr:"ce n'est pas priver l'enfant de liberté :", fa:"محروم کردنِ کودک از آزادی نیست:"},
        {fr:"c'est lui apprendre à en faire usage.", fa:"یاد دادنِ به‌کار بردنِ آن است."},
      ]},
      { label:"CONCLUSION", cls:"lb-conc", segments:[
        {fr:"Tout bien considéré,", fa:"با در نظر گرفتنِ همه‌چیز،"},
        {fr:"les bienfaits d'une autorité mesurée", fa:"فایده‌های اقتداری سنجیده"},
        {fr:"l'emportent largement", fa:"به‌روشنی می‌چربد"},
        {fr:"sur les risques d'une absence totale de repères.", fa:"بر خطرهای نبودِ کاملِ نشانه‌ها."},
        {fr:"Bien qu'elle soit parfois délicate à exercer,", fa:"هرچند گاهی اعمالش ظریف است،"},
        {fr:"elle demeure nécessaire", fa:"لازم می‌مانَد"},
        {fr:"au bon développement de l'enfant.", fa:"برای رشدِ درستِ کودک."},
        {fr:"À condition d'être juste et expliquée,", fa:"به شرطِ عادلانه و توضیح‌داده‌شده بودن،"},
        {fr:"elle favorise son équilibre.", fa:"تعادلش را تقویت می‌کند."},
        {fr:"Au fond,", fa:"در نهایت،"},
        {fr:"mieux vaut guider avec fermeté", fa:"بهتر است با قاطعیت راهنمایی کنیم"},
        {fr:"que laisser faire sans repères.", fa:"تا اینکه بی‌هیچ نشانه‌ای رها کنیم."},
        {fr:"Et l'enfant qui a connu des limites claires", fa:"و کودکی که مرزهای روشن را شناخته"},
        {fr:"est souvent celui qui, plus tard,", fa:"اغلب همان کسی است که بعدها،"},
        {fr:"saura le mieux poser les siennes.", fa:"بهتر از همه مرزهای خودش را می‌گذارد."},
      ]},
    ]
  },

  outils: {
  verbes: [
    { fa: "اجازه دادن به کسی که …",
      blocs: ["permettre à qqn de + inf.", "donner à qqn la possibilité de + inf.",
              "offrir à qqn l'occasion de + inf.", "mettre qqn en mesure de + inf."],
      ex: "l'autorité permet à l'enfant de connaître ses limites" },
    { fa: "کمک کردن به / سهم داشتن در",
      blocs: ["contribuer à + inf./nom", "participer à + nom", "concourir à + nom",
              "jouer un rôle dans + nom"],
      ex: "l'autorité contribue à préparer l'enfant à la vie en société" },
    { fa: "به وجود آوردن، ایجاد کردن (پیامد منفی)",
      blocs: ["engendrer + nom", "provoquer + nom", "susciter + nom",
              "entraîner + nom", "donner lieu à + nom"],
      ex: "une discipline trop rigide peut engendrer de la peur" },
    { fa: "بر عهده‌ی کسی بودن",
      blocs: ["il revient à qqn de + inf.", "il appartient à qqn de + inf.",
              "c'est à qqn de + inf.", "il incombe à qqn de + inf."],
      ex: "il revient aux parents de faire en sorte que les règles soient expliquées" },
    { fa: "مراقب بودن که، ترتیبی دادن که",
      blocs: ["faire en sorte que + subj.", "veiller à ce que + subj.",
              "s'assurer que + ind.", "faire le nécessaire pour que + subj."],
      ex: "faire en sorte que les règles soient cohérentes" },
    { fa: "کم‌کم از بین بردن",
      blocs: ["détruire peu à peu", "miner peu à peu", "saper progressivement",
              "éroder petit à petit"],
      ex: "on détruit peu à peu sa confiance en lui" },
    { fa: "خفه کردن، سرکوب کردن",
      blocs: ["étouffer + nom", "brider + nom", "inhiber + nom", "museler + nom"],
      ex: "toute autorité finit par étouffer sa personnalité" },
    { fa: "همراه بودن با",
      blocs: ["s'accompagner de + nom", "aller de pair avec + nom",
              "être assorti de + nom", "être associé à + nom"],
      ex: "les règles doivent s'accompagner d'écoute et de dialogue" },
    { fa: "فرق گذاشتن بین",
      blocs: ["faire la différence entre X et Y", "distinguer X de Y",
              "faire la part entre X et Y", "ne pas confondre X et Y"],
      ex: "il apprend à faire la différence entre la liberté et le laisser-aller" },
    { fa: "چربیدن بر، برتری داشتن بر",
      blocs: ["l'emporter sur + nom", "prévaloir sur + nom",
              "peser plus lourd que + nom", "prendre le pas sur + nom"],
      ex: "les bienfaits l'emportent largement sur les risques" },
    { fa: "زیر سؤال بردن",
      blocs: ["remettre en cause + nom", "remettre en question + nom",
              "contester + nom", "battre en brèche + nom"],
      ex: "les modèles traditionnels sont remis en cause" },
    { fa: "امتحان کردن، محک زدن",
      blocs: ["tester + nom", "éprouver + nom", "sonder + nom", "mettre à l'épreuve"],
      ex: "les enfants cherchent à tester leur environnement" }
  ],

  collocations: [
    { fa: "چارچوب تربیتی",
      blocs: ["un cadre éducatif", "un cadre bien défini", "un cadre structurant",
              "un environnement structuré"] },
    { fa: "قواعد روشن",
      blocs: ["des règles claires", "des règles lisibles", "des règles cohérentes",
              "des repères clairs"] },
    { fa: "سختگیری بیش از حد",
      blocs: ["une sévérité excessive", "une discipline trop rigide",
              "une rigueur absolue", "une fermeté excessive"] },
    { fa: "حس مسئولیت",
      blocs: ["le sens de la responsabilité", "le sens des responsabilités",
              "le goût de l'effort", "la conscience de ses devoirs"] },
    { fa: "رها کردن، بی‌قیدی",
      blocs: ["le laisser-aller", "le laxisme", "l'absence de repères",
              "une absence totale de cadre"] },
    { fa: "اعتماد به نفس",
      blocs: ["la confiance en soi", "l'estime de soi", "l'assurance"] },
    { fa: "گوش دادن و گفت‌وگو",
      blocs: ["l'écoute et le dialogue", "la communication", "l'échange",
              "une relation de confiance"] },
    { fa: "نسل به نسل منتقل شدن",
      blocs: ["se transmettre de génération en génération", "se perpétuer",
              "être reproduit d'une génération à l'autre"] },
    { fa: "استدلالشان بی‌پایه نیست",
      blocs: ["leur argument n'est pas sans fondement", "leur argument tient debout",
              "leur position mérite qu'on s'y arrête", "il y a du vrai dans ce qu'ils disent"] },
    { fa: "تعادل میان الف و ب",
      blocs: ["l'équilibre entre X et Y", "le juste milieu entre X et Y",
              "le bon dosage entre X et Y"] }
  ],

  adjectifs: [
    { fa: "ضروری، لازم",
      blocs: ["indispensable", "essentiel", "nécessaire", "déterminant", "incontournable"] },
    { fa: "عادلانه و مهربان",
      blocs: ["juste et bienveillante", "ferme mais bienveillante",
              "exigeante mais à l'écoute", "mesurée"] },
    { fa: "سفت و سخت",
      blocs: ["rigide", "strict", "sévère", "autoritaire", "intransigeant"] },
    { fa: "روشن، تعریف‌شده",
      blocs: ["clair", "bien défini", "lisible", "explicite", "cohérent"] },
    { fa: "سنجیده، اندازه‌شده",
      blocs: ["bien mesuré", "bien dosé", "raisonnable", "proportionné"] }
  ],

  expressions: [
    { fa: "برای شروع، اول از همه",
      role: "premier argument",
      blocs: ["D'emblée, je suis d'avis que…", "En premier lieu,…",
              "Pour commencer, il faut dire que…", "Un premier élément à prendre en compte est…"] },
    { fa: "دوم اینکه",
      role: "argument suivant",
      blocs: ["En deuxième lieu,…", "Par ailleurs,…", "Il convient également de souligner que…",
              "Un autre aspect mérite d'être pris en considération…"] },
    { fa: "و نکته‌ی آخر",
      role: "dernier argument",
      blocs: ["Un dernier point mérite d'être pris en considération…",
              "Dernier point, mais non le moindre,…", "Enfin,…", "Il faut également tenir compte de…"] },
    { fa: "این را به سادگی می‌شود توضیح داد",
      role: "justifier",
      blocs: ["Cela s'explique simplement :", "Cela s'explique notamment par…",
              "La raison en est simple :", "Ce phénomène s'explique par…"] },
    { fa: "با این حال، البته",
      role: "nuancer",
      blocs: ["Cela dit,…", "Cependant,…", "Néanmoins,…", "Il ne faut toutefois pas oublier que…",
              "Il convient de nuancer ce point."] },
    { fa: "برعکس، در مقابل",
      role: "opposer",
      blocs: ["En revanche,…", "À l'inverse,…", "Au contraire,…", "Or,…"] },
    { fa: "به شرط اینکه",
      role: "poser une condition",
      blocs: ["à condition que + subj.", "à condition de + inf.", "pourvu que + subj.",
              "dans la mesure où + ind.", "si tant est que + subj."] },
    { fa: "با اینکه، هرچند",
      role: "concéder",
      blocs: ["Bien que + subj.", "Même si + ind.", "Quoique + subj.",
              "Malgré + nom", "Certes…, mais…"] },
    { fa: "برای جمع‌بندی",
      role: "conclure",
      blocs: ["Pour conclure,…", "En définitive,…", "Tout bien considéré,…",
              "En somme,…", "Au fond,…"] },
    { fa: "بهتر است که",
      role: "recommander",
      blocs: ["Il vaut mieux + inf.", "Mieux vaut + inf.", "Il serait préférable de + inf.",
              "Il serait souhaitable de + inf."] }
  ]
},

  echelle: [
    { fa: "قواعد به بچه کمک می‌کند بفهمد چه کاری درست است.",
      simple: "Les règles aident l'enfant à savoir ce qui est bien.",
      b2:     "Un cadre clair aide l'enfant à connaître ses limites.",
      b2plus: "Un cadre bien défini permet à l'enfant de situer ses limites." },
    { fa: "سختگیری زیاد نتیجه‌ی بد می‌دهد.",
      simple: "Trop de sévérité donne un mauvais résultat.",
      b2:     "Une discipline trop rigide peut engendrer de la peur.",
      b2plus: "Une discipline trop rigide risque d'engendrer la peur, voire la rébellion." },
    { fa: "پدر و مادر باید مطمئن شوند قواعد یکسان است.",
      simple: "Les parents doivent être sûrs que les règles sont les mêmes.",
      b2:     "Il revient aux parents de faire en sorte que les règles soient cohérentes.",
      b2plus: "Il revient aux parents de veiller à ce que les règles soient cohérentes et explicitées." },
    { fa: "بچه یاد می‌گیرد در جامعه زندگی کند.",
      simple: "L'enfant apprend à vivre avec les autres.",
      b2:     "L'autorité contribue à préparer l'enfant à la vie en société.",
      b2plus: "Un environnement structuré développe chez l'enfant le sens des responsabilités." },
    { fa: "فایده‌هایش بیشتر از ضررهایش است.",
      simple: "Il y a plus d'avantages que d'inconvénients.",
      b2:     "Les bienfaits l'emportent sur les risques.",
      b2plus: "Les bienfaits d'une autorité mesurée l'emportent largement sur les risques d'une absence de repères." }
  ],

  antiTrad: [
    { faux: "Les parents doivent faire attention que les règles sont les mêmes.",
      juste: "Il revient aux parents de veiller à ce que les règles soient cohérentes.",
      pourquoi: "« Faire attention que » traduit « مراقب باشند که ». En français on dit « veiller à ce que » + subjonctif. Et « les mêmes » devient « cohérentes »." },
    { faux: "L'autorité donne beaucoup de bonnes choses à l'enfant.",
      juste: "L'autorité permet à l'enfant de connaître ses limites.",
      pourquoi: "« Donner beaucoup de bonnes choses » est vague. On nomme précisément ce que l'autorité rend possible." },
    { faux: "Si les parents sont trop durs, l'enfant devient peur.",
      juste: "Une discipline trop rigide peut engendrer de la peur.",
      pourquoi: "« Devenir peur » calque « ترسو می‌شود ». La peur n'est pas un état qu'on devient : elle est engendrée, provoquée, suscitée." },
    { faux: "Ce n'est pas bon de mélanger l'autorité avec la violence.",
      juste: "Confondre l'autorité et la brutalité, c'est justement l'erreur que je dénonce.",
      pourquoi: "« Mélanger » se dit d'ingrédients. Pour deux notions qu'on prend l'une pour l'autre, le verbe est « confondre »." },
    { faux: "Les parents apprennent leur méthode de leurs parents.",
      juste: "Ce modèle se transmet de génération en génération.",
      pourquoi: "La phrase persane suit les personnes ; le français d'examen préfère nommer le phénomène — « le modèle se transmet »." }
  ],

  transferables: [
    { bloc: "Il revient à X de + infinitif",
      ailleurs: ["l'État : il revient à l'État de garantir l'accès aux soins",
                 "l'entreprise : il revient à l'employeur de former ses salariés"] },
    { bloc: "X ne doit pas devenir synonyme de Y",
      ailleurs: ["la fermeté ne doit pas devenir synonyme de rigidité",
                 "la liberté ne doit pas devenir synonyme de laisser-aller"] },
    { bloc: "Ce qui compte avant tout, ce n'est pas X : c'est Y.",
      ailleurs: ["utilisable partout — c'est le pivot argumentatif le plus rentable de la fiche"] },
    { bloc: "…à condition que + subjonctif",
      ailleurs: ["la technologie est utile à condition qu'elle soit encadrée",
                 "la gratuité fonctionne à condition que l'État compense"] },
    { bloc: "Les bienfaits de X l'emportent sur les risques de Y.",
      ailleurs: ["santé, environnement, travail — toute question qui se tranche par une balance"] }
  ],

  reseau: {
    noms: ["l'autorité", "le cadre éducatif", "les limites", "les repères", "la discipline",
           "la fermeté", "l'écoute", "le dialogue", "la confiance en soi", "le laisser-aller"],
    verbes: ["poser", "fixer", "encadrer", "guider", "rassurer", "structurer",
             "engendrer", "étouffer", "transmettre", "distinguer"],
    adjectifs: ["indispensable", "bienveillant", "juste", "rigide", "cohérent",
                "structuré", "excessif", "mesuré", "lisible"],
    consequences: ["un enfant rassuré", "le sens des responsabilités", "la peur",
                   "la rébellion", "une confiance en soi entamée"],
    causes: ["l'absence de règles", "des règles incohérentes", "un modèle familial reproduit",
             "une discipline trop rigide"],
    solutions: ["des règles expliquées", "un cadre cohérent", "l'écoute et le dialogue",
                "l'équilibre entre fermeté et écoute"]
  },

  grammaire: [
    { structure: "à condition que + subjonctif", ex: "à condition qu'elle soit juste et bienveillante" },
    { structure: "bien que + subjonctif", ex: "bien qu'elle soit parfois difficile à exercer" },
    { structure: "faire en sorte que / veiller à ce que + subjonctif", ex: "faire en sorte que les règles soient cohérentes" },
    { structure: "gérondif", ex: "en grandissant dans un environnement structuré, il développe…" },
    { structure: "tout en + participe présent (concession)", ex: "tout en étant encadré, il apprend à…" },
    { structure: "mise en relief : ce n'est pas X, c'est Y", ex: "ce n'est pas la règle elle-même : c'est la stabilité du cadre" },
    { structure: "infinitif sujet", ex: "poser un cadre, ce n'est pas priver un enfant de liberté" }
  ]
}

];
