// ═══════════════════════════════════════════════════════════════
//  BLOCS & COLLOCATIONS — fiches pour les élèves
//  But : casser l'habitude de traduire depuis le persan/l'anglais.
//  On n'apprend pas des mots isolés, on apprend des BLOCS.
//  Le persan ne sert qu'à comprendre une fois — jamais à produire.
// ═══════════════════════════════════════════════════════════════

const BLOCS_SUJETS = [

{
  id: 1,
  theme: 'culture',
  q: "Les loisirs culturels (musées, théâtres, etc.) devraient être gratuits. Qu'en pensez-vous ?",
  qFa: "تفریحات فرهنگی — موزه، تئاتر و مانند این‌ها — باید رایگان باشند. نظرتان چیست؟",
  these: "Favorable, mais à une condition : une gratuité ciblée, compensée par l'État.",
  theseFa: "موافق، اما به یک شرط: رایگانیِ هدفمند که دولت هزینه‌اش را جبران کند.",

  textes: {
    b2: [
      { label:"INTRODUCTION", cls:"lb-intro", segments:[
        {fr:"L'accès à la culture", fa:"دسترسی به فرهنگ"},
        {fr:"soulève aujourd'hui de nombreux débats.", fa:"امروز بحث‌های زیادی برمی‌انگیزد."},
        {fr:"Certains estiment", fa:"بعضی‌ها معتقدند"},
        {fr:"que les musées et les théâtres", fa:"که موزه‌ها و تئاترها"},
        {fr:"devraient être entièrement gratuits,", fa:"باید کاملاً رایگان باشند،"},
        {fr:"d'autres pensent", fa:"دیگران فکر می‌کنند"},
        {fr:"que cela n'est pas réaliste.", fa:"که این واقع‌بینانه نیست."},
        {fr:"Personnellement, je suis d'avis", fa:"شخصاً، بر این نظرم"},
        {fr:"que la gratuité représente un véritable atout,", fa:"که رایگانی یک برگ برنده‌ی واقعی است،"},
        {fr:"à condition qu'elle soit bien organisée.", fa:"به شرط آنکه خوب سازمان‌دهی شود."},
        {fr:"Je vais expliquer les raisons", fa:"دلایلی را توضیح می‌دهم"},
        {fr:"pour lesquelles je défends cette position.", fa:"که به‌خاطرشان از این موضع دفاع می‌کنم."},
      ]},
      { label:"ARGUMENT 1 — l'accès", cls:"lb-arg", segments:[
        {fr:"En premier lieu,", fa:"در وهله‌ی اول،"},
        {fr:"la gratuité favorise l'accès à la culture", fa:"رایگانی دسترسی به فرهنگ را تسهیل می‌کند"},
        {fr:"pour tous.", fa:"برای همه."},
        {fr:"En effet,", fa:"در واقع،"},
        {fr:"le prix d'entrée constitue souvent un obstacle", fa:"قیمتِ ورودی اغلب مانعی است"},
        {fr:"pour les familles modestes.", fa:"برای خانواده‌های کم‌درآمد."},
        {fr:"Cela s'explique notamment", fa:"این عمدتاً برمی‌گردد"},
        {fr:"par le coût élevé des billets", fa:"به هزینه‌ی بالای بلیت‌ها"},
        {fr:"dans les grandes villes.", fa:"در شهرهای بزرگ."},
        {fr:"Par exemple,", fa:"برای مثال،"},
        {fr:"une famille de quatre personnes", fa:"خانواده‌ای چهارنفره"},
        {fr:"doit parfois payer une somme importante", fa:"گاهی باید مبلغ قابل توجهی بپردازد"},
        {fr:"pour une seule visite.", fa:"برای یک بازدید."},
        {fr:"Par conséquent,", fa:"در نتیجه،"},
        {fr:"la gratuité permettrait de réduire les inégalités", fa:"رایگانی می‌تواند نابرابری‌ها را کم کند"},
        {fr:"entre les citoyens.", fa:"میان شهروندان."},
      ]},
      { label:"ARGUMENT 2 — la formation du citoyen", cls:"lb-arg", segments:[
        {fr:"Il convient également de souligner", fa:"همچنین باید تأکید کرد"},
        {fr:"que la culture joue un rôle essentiel", fa:"که فرهنگ نقشی اساسی دارد"},
        {fr:"dans la formation des citoyens.", fa:"در تربیتِ شهروندان."},
        {fr:"Fréquenter un musée", fa:"رفت‌وآمد به موزه"},
        {fr:"ou une pièce de théâtre", fa:"یا به یک نمایش"},
        {fr:"contribue à développer l'esprit critique", fa:"به رشدِ روحیه‌ی نقد کمک می‌کند"},
        {fr:"et à renforcer la cohésion sociale.", fa:"و به تقویتِ انسجام اجتماعی."},
        {fr:"Un enfant qui découvre une exposition", fa:"کودکی که نمایشگاهی را کشف می‌کند"},
        {fr:"n'apprend pas seulement des dates :", fa:"فقط تاریخ یاد نمی‌گیرد:"},
        {fr:"il apprend à observer,", fa:"یاد می‌گیرد مشاهده کند،"},
        {fr:"à comparer,", fa:"مقایسه کند،"},
        {fr:"à se poser des questions.", fa:"از خودش سؤال بپرسد."},
        {fr:"La gratuité ne représente donc pas une dépense,", fa:"پس رایگانی یک هزینه نیست،"},
        {fr:"mais un investissement à long terme.", fa:"بلکه سرمایه‌گذاری‌ای بلندمدت است."},
      ]},
      { label:"ARGUMENT 3 — l'effet réel", cls:"lb-arg", segments:[
        {fr:"Un autre aspect", fa:"جنبه‌ی دیگری"},
        {fr:"mérite d'être pris en considération :", fa:"درخورِ توجه است:"},
        {fr:"la gratuité a un impact direct", fa:"رایگانی تأثیری مستقیم دارد"},
        {fr:"sur la fréquentation.", fa:"بر میزانِ بازدید."},
        {fr:"Quand le prix disparaît,", fa:"وقتی قیمت حذف می‌شود،"},
        {fr:"les publics changent,", fa:"مخاطبان عوض می‌شوند،"},
        {fr:"et notamment les jeunes.", fa:"و به‌خصوص جوان‌ها."},
        {fr:"Par exemple,", fa:"برای مثال،"},
        {fr:"les journées gratuites", fa:"روزهای رایگان"},
        {fr:"organisées dans certains musées", fa:"که در بعضی موزه‌ها برگزار می‌شود"},
        {fr:"attirent un public beaucoup plus large", fa:"مخاطبی خیلی گسترده‌تر جذب می‌کند"},
        {fr:"et beaucoup plus varié.", fa:"و خیلی متنوع‌تر."},
        {fr:"Cela montre que la barrière", fa:"این نشان می‌دهد که مانع"},
        {fr:"n'est pas le manque d'intérêt,", fa:"نبودِ علاقه نیست،"},
        {fr:"mais bien le prix.", fa:"بلکه دقیقاً قیمت است."},
      ]},
      { label:"CONTRE-ARGUMENT", cls:"lb-arg", segments:[
        {fr:"Cela dit,", fa:"با این حال،"},
        {fr:"il ne faut pas perdre de vue", fa:"نباید از نظر دور داشت"},
        {fr:"que les institutions culturelles", fa:"که نهادهای فرهنگی"},
        {fr:"font face à de fortes contraintes budgétaires.", fa:"با محدودیت‌های شدیدِ بودجه‌ای مواجه‌اند."},
        {fr:"Si les recettes disparaissent,", fa:"اگر درآمدها از بین برود،"},
        {fr:"la qualité risque de se dégrader.", fa:"کیفیت ممکن است افت کند."},
        {fr:"Il convient donc de nuancer ce point :", fa:"پس باید این نکته را تعدیل کرد:"},
        {fr:"une gratuité totale et sans compensation", fa:"رایگانیِ کامل و بدون جبران"},
        {fr:"serait difficile à mettre en place.", fa:"اجرایش دشوار می‌بود."},
      ]},
      { label:"CONCLUSION", cls:"lb-conc", segments:[
        {fr:"Pour conclure,", fa:"برای جمع‌بندی،"},
        {fr:"je reste convaincu", fa:"همچنان معتقدم"},
        {fr:"que la gratuité constitue une mesure bénéfique,", fa:"که رایگانی اقدامی سودمند است،"},
        {fr:"à condition que l'État prenne en charge la différence.", fa:"به شرط آنکه دولت تفاوتش را به عهده بگیرد."},
        {fr:"Il serait donc souhaitable", fa:"پس مطلوب است"},
        {fr:"de mettre en place une gratuité ciblée,", fa:"که رایگانیِ هدفمند اجرا شود،"},
        {fr:"pour les jeunes, les étudiants", fa:"برای جوان‌ها، دانشجوها"},
        {fr:"et les personnes en difficulté,", fa:"و افرادِ در مضیقه،"},
        {fr:"plutôt qu'une gratuité générale.", fa:"به‌جای رایگانیِ همگانی."},
      ]},
    ],
    c1: [
      { label:"INTRODUCTION", cls:"lb-intro", segments:[
        {fr:"À l'heure où l'accès à la culture", fa:"در زمانه‌ای که دسترسی به فرهنگ"},
        {fr:"est présenté comme un droit,", fa:"به‌عنوان یک حق معرفی می‌شود،"},
        {fr:"la question de savoir", fa:"این پرسش"},
        {fr:"si les musées et les théâtres", fa:"که آیا موزه‌ها و تئاترها"},
        {fr:"devraient être gratuits", fa:"باید رایگان باشند"},
        {fr:"suscite de nombreux débats.", fa:"بحث‌های زیادی برمی‌انگیزد."},
        {fr:"Certains y voient une mesure de justice sociale,", fa:"بعضی در آن اقدامی برای عدالت اجتماعی می‌بینند،"},
        {fr:"d'autres une charge", fa:"دیگران باری"},
        {fr:"que les institutions ne pourraient pas supporter.", fa:"که نهادها تابش را ندارند."},
        {fr:"Personnellement, je suis convaincu", fa:"شخصاً، معتقدم"},
        {fr:"que la gratuité représente un enjeu majeur,", fa:"که رایگانی مسئله‌ای اساسی است،"},
        {fr:"à condition qu'elle s'accompagne", fa:"به شرط آنکه همراه شود"},
        {fr:"d'un financement public clair.", fa:"با تأمینِ مالیِ عمومیِ روشن."},
        {fr:"Je tiens à expliquer les raisons", fa:"می‌خواهم دلایلی را توضیح دهم"},
        {fr:"pour lesquelles cette nuance me paraît déterminante.", fa:"که این تفاوت را به نظرم تعیین‌کننده می‌کند."},
      ]},
      { label:"ARGUMENT 1 — l'accès", cls:"lb-arg", segments:[
        {fr:"D'emblée, il me semble", fa:"از همان ابتدا، به نظرم"},
        {fr:"que la gratuité favorise l'accès à la culture", fa:"رایگانی دسترسی به فرهنگ را تسهیل می‌کند"},
        {fr:"pour l'ensemble de la population.", fa:"برای کلِ جمعیت."},
        {fr:"En effet,", fa:"در واقع،"},
        {fr:"le prix d'entrée constitue un obstacle réel", fa:"قیمتِ ورودی مانعی واقعی است"},
        {fr:"pour les ménages modestes,", fa:"برای خانوارهای کم‌درآمد،"},
        {fr:"qui arbitrent en permanence", fa:"که دائماً در حالِ انتخاب‌اند"},
        {fr:"entre des dépenses jugées plus urgentes.", fa:"میانِ هزینه‌هایی که فوری‌تر می‌دانند."},
        {fr:"Cela s'explique notamment", fa:"این عمدتاً برمی‌گردد"},
        {fr:"par le coût cumulé d'une sortie familiale,", fa:"به هزینه‌ی روی‌هم‌رفته‌ی یک بیرون‌رفتنِ خانوادگی،"},
        {fr:"transport compris.", fa:"با احتسابِ رفت‌وآمد."},
        {fr:"Par conséquent,", fa:"در نتیجه،"},
        {fr:"supprimer ce prix reviendrait", fa:"حذفِ این قیمت یعنی"},
        {fr:"à réduire des inégalités", fa:"کم کردنِ نابرابری‌هایی"},
        {fr:"qui se creusent dès l'enfance.", fa:"که از کودکی عمیق می‌شوند."},
      ]},
      { label:"ARGUMENT 2 — la formation du citoyen", cls:"lb-arg", segments:[
        {fr:"Il convient également de souligner", fa:"همچنین باید تأکید کرد"},
        {fr:"que la culture joue un rôle déterminant", fa:"که فرهنگ نقشی تعیین‌کننده دارد"},
        {fr:"dans la formation des citoyens.", fa:"در تربیتِ شهروندان."},
        {fr:"Fréquenter une exposition", fa:"رفت‌وآمد به یک نمایشگاه"},
        {fr:"ou une salle de théâtre", fa:"یا به سالنِ تئاتر"},
        {fr:"contribue à développer l'esprit critique", fa:"به رشدِ روحیه‌ی نقد کمک می‌کند"},
        {fr:"et à renforcer la cohésion sociale.", fa:"و به تقویتِ انسجام اجتماعی."},
        {fr:"Un enfant qui découvre une œuvre", fa:"کودکی که اثری را کشف می‌کند"},
        {fr:"n'accumule pas des connaissances :", fa:"دانش انباشت نمی‌کند:"},
        {fr:"il apprend à observer,", fa:"یاد می‌گیرد مشاهده کند،"},
        {fr:"à comparer,", fa:"مقایسه کند،"},
        {fr:"à formuler un jugement.", fa:"قضاوتی صورت‌بندی کند."},
        {fr:"Dans cette perspective,", fa:"از این منظر،"},
        {fr:"la gratuité ne relève pas de la dépense,", fa:"رایگانی از جنسِ هزینه نیست،"},
        {fr:"mais bien de l'investissement.", fa:"بلکه دقیقاً از جنسِ سرمایه‌گذاری است."},
      ]},
      { label:"ARGUMENT 3 — l'effet réel", cls:"lb-arg", segments:[
        {fr:"Un dernier élément", fa:"عنصرِ آخری"},
        {fr:"mérite d'être pris en considération :", fa:"درخورِ توجه است:"},
        {fr:"l'impact de la gratuité sur la fréquentation", fa:"تأثیرِ رایگانی بر میزانِ بازدید"},
        {fr:"est mesurable.", fa:"قابلِ اندازه‌گیری است."},
        {fr:"Dès lors que la barrière tarifaire tombe,", fa:"به‌محضِ اینکه مانعِ قیمتی می‌افتد،"},
        {fr:"la composition du public se modifie,", fa:"ترکیبِ مخاطبان تغییر می‌کند،"},
        {fr:"en particulier chez les jeunes adultes.", fa:"به‌ویژه در جوانانِ بزرگسال."},
        {fr:"Les journées gratuites", fa:"روزهای رایگان"},
        {fr:"mises en place par certaines institutions", fa:"که بعضی نهادها اجرا می‌کنند"},
        {fr:"attirent ainsi un public", fa:"بدین‌ترتیب مخاطبی جذب می‌کند"},
        {fr:"sensiblement plus large et plus varié.", fa:"به‌طرزِ محسوسی گسترده‌تر و متنوع‌تر."},
        {fr:"Cela tend à prouver que l'obstacle", fa:"این نشان می‌دهد که مانع"},
        {fr:"n'est pas le désintérêt,", fa:"بی‌علاقگی نیست،"},
        {fr:"mais bien le prix.", fa:"بلکه دقیقاً قیمت است."},
      ]},
      { label:"CONTRE-ARGUMENT", cls:"lb-arg", segments:[
        {fr:"Cela dit,", fa:"با این حال،"},
        {fr:"il ne faut toutefois pas oublier", fa:"با این‌همه نباید فراموش کرد"},
        {fr:"que les institutions culturelles", fa:"که نهادهای فرهنگی"},
        {fr:"sont confrontées à de fortes contraintes budgétaires.", fa:"با محدودیت‌های شدیدِ بودجه‌ای روبه‌رویند."},
        {fr:"Si les recettes de billetterie", fa:"اگر درآمدِ فروشِ بلیت"},
        {fr:"venaient à disparaître sans contrepartie,", fa:"بدونِ جبران از بین برود،"},
        {fr:"la qualité des expositions", fa:"کیفیتِ نمایشگاه‌ها"},
        {fr:"et la conservation des collections", fa:"و نگهداریِ مجموعه‌ها"},
        {fr:"en pâtiraient.", fa:"آسیب می‌بیند."},
        {fr:"Il convient donc de nuancer ce point :", fa:"پس باید این نکته را تعدیل کرد:"},
        {fr:"une gratuité généralisée, sans compensation,", fa:"رایگانیِ همگانی، بدونِ جبران،"},
        {fr:"se révélerait difficilement soutenable.", fa:"به‌سختی قابلِ دوام از آب درمی‌آید."},
      ]},
      { label:"CONCLUSION", cls:"lb-conc", segments:[
        {fr:"Tout bien considéré,", fa:"با در نظر گرفتنِ همه‌چیز،"},
        {fr:"je reste convaincu", fa:"همچنان معتقدم"},
        {fr:"que la gratuité constitue une mesure bénéfique,", fa:"که رایگانی اقدامی سودمند است،"},
        {fr:"à condition que l'État prenne en charge le manque à gagner.", fa:"به شرط آنکه دولت درآمدِ از دست رفته را به عهده بگیرد."},
        {fr:"Il serait donc préférable", fa:"پس ترجیح دارد"},
        {fr:"de mettre en place une gratuité ciblée —", fa:"که رایگانیِ هدفمند اجرا شود —"},
        {fr:"jeunes, étudiants, publics en difficulté —", fa:"جوان‌ها، دانشجوها، مخاطبانِ در مضیقه —"},
        {fr:"plutôt qu'une mesure uniforme", fa:"به‌جای اقدامی یکسان"},
        {fr:"dont personne ne pourrait garantir la pérennité.", fa:"که هیچ‌کس دوامش را تضمین نمی‌کند."},
      ]},
    ],
  },

  // ── Les blocs, classés par fonction. C'est le cœur de la fiche. ──
  outils: {
    verbes: [
      { bloc: "favoriser l'accès à…",            ex: "favoriser l'accès à la culture",              fa: "دسترسی به … را تسهیل کردن" },
      { bloc: "contribuer à + nom / infinitif",  ex: "contribuer à développer l'esprit critique",   fa: "به … کمک کردن" },
      { bloc: "constituer un obstacle",          ex: "le prix constitue un obstacle réel",          fa: "مانع بودن" },
      { bloc: "réduire les inégalités",          ex: "réduire les inégalités entre les citoyens",   fa: "نابرابری‌ها را کم کردن" },
      { bloc: "renforcer la cohésion sociale",   ex: "la culture renforce la cohésion sociale",     fa: "انسجام اجتماعی را تقویت کردن" },
      { bloc: "mettre en place une mesure",      ex: "mettre en place une gratuité ciblée",         fa: "اقدامی را اجرا کردن" },
      { bloc: "prendre en charge",               ex: "l'État prend en charge la différence",        fa: "هزینه را به عهده گرفتن" },
      { bloc: "faire face à…",                   ex: "faire face à des contraintes budgétaires",    fa: "با … مواجه بودن" },
      { bloc: "avoir un impact sur…",            ex: "avoir un impact direct sur la fréquentation", fa: "بر … تأثیر داشتن" },
      { bloc: "se révéler + adjectif",           ex: "se révéler difficilement soutenable",         fa: "از آب درآمدن، معلوم شدن که" }
    ],
    collocations: [
      { bloc: "un enjeu majeur",              fa: "مسئله‌ای اساسی" },
      { bloc: "un véritable atout",           fa: "یک برگ برنده‌ی واقعی" },
      { bloc: "des contraintes budgétaires",  fa: "محدودیت‌های بودجه‌ای" },
      { bloc: "une mesure bénéfique",         fa: "اقدامی سودمند" },
      { bloc: "un investissement à long terme", fa: "سرمایه‌گذاری بلندمدت" },
      { bloc: "la barrière tarifaire",        fa: "مانعِ قیمتی" },
      { bloc: "les recettes de billetterie",  fa: "درآمدِ فروش بلیت" },
      { bloc: "le manque à gagner",           fa: "درآمدِ از دست رفته" },
      { bloc: "un public plus large et plus varié", fa: "مخاطبی گسترده‌تر و متنوع‌تر" },
      { bloc: "les ménages modestes",         fa: "خانوارهای کم‌درآمد" }
    ],
    adjectifs: [
      { bloc: "un obstacle réel",         fa: "مانعی واقعی" },
      { bloc: "un rôle déterminant",      fa: "نقشی تعیین‌کننده" },
      { bloc: "un coût élevé",            fa: "هزینه‌ای بالا" },
      { bloc: "une mesure bénéfique",     fa: "اقدامی سودمند" },
      { bloc: "une gratuité ciblée",      fa: "رایگانیِ هدفمند" },
      { bloc: "un impact mesurable",      fa: "تأثیری قابل اندازه‌گیری" },
      { bloc: "difficilement soutenable", fa: "به‌سختی قابل دوام" }
    ],
    expressions: [
      { bloc: "Il convient de souligner que…",        role: "ajouter un argument",  fa: "باید تأکید کرد که…" },
      { bloc: "Cela s'explique notamment par…",       role: "justifier",            fa: "این عمدتاً به … برمی‌گردد" },
      { bloc: "Un autre aspect mérite d'être pris en considération…", role: "argument suivant", fa: "جنبه‌ی دیگری هم درخور توجه است" },
      { bloc: "Il ne faut pas perdre de vue que…",    role: "nuancer",              fa: "نباید از نظر دور داشت که…" },
      { bloc: "Il convient de nuancer ce point.",     role: "nuancer",              fa: "باید این نکته را تعدیل کرد" },
      { bloc: "Tout bien considéré,…",                role: "conclure",             fa: "با در نظر گرفتن همه چیز،" },
      { bloc: "à condition que + subjonctif",         role: "poser une condition",  fa: "به شرط آنکه…" },
      { bloc: "Il serait souhaitable de…",            role: "proposer",             fa: "مطلوب است که…" }
    ]
  },

  // ── L'échelle : la même idée, trois hauteurs ──
  echelle: [
    { fa: "رایگان بودن کمک می‌کند مردم بیشتر به موزه بروند.",
      simple: "La gratuité aide les gens à aller au musée.",
      b2:     "La gratuité favorise l'accès à la culture.",
      b2plus: "La gratuité favorise l'accès à la culture pour l'ensemble de la population." },
    { fa: "قیمت بلیت برای بعضی خانواده‌ها زیاد است.",
      simple: "Le prix est trop cher pour quelques familles.",
      b2:     "Le prix d'entrée constitue un obstacle pour les familles modestes.",
      b2plus: "Le prix d'entrée constitue un obstacle réel pour les ménages modestes." },
    { fa: "فرهنگ به فکر کردن آدم‌ها کمک می‌کند.",
      simple: "La culture aide les personnes à penser.",
      b2:     "La culture contribue à développer l'esprit critique.",
      b2plus: "La culture joue un rôle déterminant dans la formation des citoyens." },
    { fa: "موزه‌ها پول کافی ندارند.",
      simple: "Les musées n'ont pas assez d'argent.",
      b2:     "Les musées font face à des contraintes budgétaires.",
      b2plus: "Les institutions culturelles sont confrontées à de fortes contraintes budgétaires." },
    { fa: "دولت باید هزینه‌اش را بدهد.",
      simple: "L'État doit payer l'argent.",
      b2:     "L'État doit prendre en charge la différence.",
      b2plus: "L'État doit prendre en charge le manque à gagner." }
  ],

  // ── Le piège : ce que produit une traduction mot à mot ──
  antiTrad: [
    { faux: "Le musée est très cher pour beaucoup de personnes.",
      juste: "Le prix d'entrée constitue un obstacle pour de nombreuses familles.",
      pourquoi: "En persan on dit « موزه گران است ». En français, ce n'est pas le musée qui est cher, c'est le prix d'entrée. On nomme la chose précise, puis on lui applique un bloc." },
    { faux: "La culture donne beaucoup de choses aux gens.",
      juste: "La culture contribue à développer l'esprit critique.",
      pourquoi: "« Donner beaucoup de choses » traduit « چیزهای زیادی می‌دهد ». C'est vague. Le français d'examen attend un verbe précis + un nom précis." },
    { faux: "Le gouvernement doit donner l'argent aux musées.",
      juste: "L'État doit prendre en charge le manque à gagner.",
      pourquoi: "« Donner l'argent » est de l'anglais scolaire (give money). Le bloc naturel est « prendre en charge » + un nom de coût." },
    { faux: "Beaucoup de personnes veulent aller au musée mais ils ne peuvent pas.",
      juste: "L'obstacle n'est pas le désintérêt, mais bien le prix.",
      pourquoi: "La phrase persane décrit deux faits l'un après l'autre. Le français argumentatif oppose : « ce n'est pas X, c'est Y »." },
    { faux: "C'est un bon investissement pour le futur.",
      juste: "Il s'agit d'un investissement à long terme.",
      pourquoi: "« Pour le futur » est une traduction littérale. La collocation figée est « à long terme »." }
  ],

  // ── Ce qui se recycle ailleurs ──
  transferables: [
    { bloc: "X constitue un obstacle réel pour…",
      ailleurs: ["l'emploi : la langue constitue un obstacle réel pour les nouveaux arrivants",
                 "la santé : la distance constitue un obstacle réel pour les patients ruraux"] },
    { bloc: "X contribue à développer…",
      ailleurs: ["le sport contribue à développer l'esprit d'équipe",
                 "la lecture contribue à développer l'autonomie"] },
    { bloc: "Il ne faut pas perdre de vue que…",
      ailleurs: ["utilisable dans absolument tous les sujets, pour amener la nuance"] },
    { bloc: "…à condition que + subjonctif",
      ailleurs: ["la technologie est utile à condition qu'elle soit encadrée",
                 "le télétravail fonctionne à condition que l'entreprise l'organise"] },
    { bloc: "Il s'agit non pas d'une dépense, mais d'un investissement.",
      ailleurs: ["éducation, santé, environnement, formation — partout où l'on parle de budget public"] }
  ],

  // ── La carte du thème ──
  reseau: {
    noms: ["l'accès à la culture", "le prix d'entrée", "la billetterie", "la fréquentation",
           "les inégalités", "l'esprit critique", "la cohésion sociale", "le budget public",
           "les institutions culturelles", "le patrimoine"],
    verbes: ["favoriser", "contribuer à", "réduire", "renforcer", "financer",
             "subventionner", "élargir", "attirer", "prendre en charge", "encadrer"],
    adjectifs: ["accessible", "gratuit", "bénéfique", "déterminant", "modeste",
                "élevé", "ciblé", "durable", "varié"],
    consequences: ["une fréquentation en hausse", "un public plus varié",
                   "une réduction des inégalités", "une perte de recettes"],
    causes: ["le coût des billets", "l'éloignement géographique", "le manque d'habitude familiale"],
    solutions: ["la gratuité ciblée", "les journées gratuites", "le tarif étudiant",
                "les subventions publiques", "le pass culture"]
  },

  grammaire: [
    { structure: "à condition que + subjonctif", ex: "à condition qu'elle soit bien organisée" },
    { structure: "Si + imparfait, + conditionnel", ex: "si les recettes disparaissaient, la qualité se dégraderait" },
    { structure: "mise en relief : ce n'est pas X, c'est Y", ex: "l'obstacle n'est pas le désintérêt, mais bien le prix" },
    { structure: "nominalisation", ex: "la suppression du prix / la fréquentation des musées" },
    { structure: "voix passive", ex: "les institutions sont confrontées à des contraintes" },
    { structure: "gérondif", ex: "en supprimant le prix, on élargit le public" }
  ]
}

];
