// ═══════════════════════════════════════════════════════════
//  Expression Orale — Tâche 3 · بانکِ ۱۲۰ سؤال + موضوع‌بندی
//  هر سؤال به یک موضوع (theme) تعلق دارد.
//  done=false یعنی هنوز تمرینِ ترجمه‌اش ساخته نشده.
//  وقتی ساخته شد: done=true و trainer=<آیدیِ داده‌ی ترینر>.
// ═══════════════════════════════════════════════════════════

const EO_THEMES = [
  { id:'etudes',       fa:'تحصیل و آموزش',            fr:'Études & Éducation',        color:'#43a047' },
  { id:'travail',      fa:'کار و شغل',                 fr:'Travail & Carrière',        color:'#1e88e5' },
  { id:'immigration',  fa:'مهاجرت و زندگی در خارج',    fr:'Immigration & Étranger',    color:'#fb8c00' },
  { id:'techno',       fa:'تکنولوژی و اینترنت',        fr:'Technologie & Internet',    color:'#8e24aa' },
  { id:'medias',       fa:'رسانه و تلویزیون',          fr:'Médias & Information',      color:'#e53935' },
  { id:'environnement',fa:'محیط‌زیست و اکولوژی',       fr:'Environnement & Écologie',  color:'#2e7d32' },
  { id:'tourisme',     fa:'گردشگری و سفر',             fr:'Tourisme & Voyage',         color:'#00acc1' },
  { id:'sante',        fa:'سلامت و تغذیه',             fr:'Santé & Alimentation',      color:'#d81b60' },
  { id:'famille',      fa:'خانواده و روابط',           fr:'Famille & Relations',       color:'#6d4c41' },
  { id:'culture',      fa:'فرهنگ و اوقات فراغت',       fr:'Culture & Loisirs',         color:'#5e35b1' },
  { id:'societe',      fa:'جامعه و ارزش‌ها',           fr:'Société & Valeurs',         color:'#546e7a' },
  { id:'animaux',      fa:'حیوانات',                   fr:'Animaux',                   color:'#7cb342' },
];

const EO_QUESTIONS = [
  { id:1,  theme:'travail',      done:true,  q:"Faire des études permet de réussir sa carrière professionnelle. Qu’en pensez-vous ?" },
  { id:2,  theme:'immigration',  done:true,  q:"Quel est l’intérêt d’avoir une expérience professionnelle ou universitaire à l’étranger ?" },
  { id:3,  theme:'medias',       done:false, q:"Selon vous, quel rôle joue la télévision dans l’éducation des enfants ?" },
  { id:4,  theme:'etudes',       done:false, q:"Pensez-vous que l’autorité soit indispensable dans l’éducation d’un enfant ? Pourquoi ?" },
  { id:5,  theme:'immigration',  done:false, q:"Est-ce que vous pensez qu'il est difficile de vivre dans un pays étranger ? Pourquoi ?" },
  { id:6,  theme:'immigration',  done:false, q:"D’après vous, vivre à l’étranger a-t-il plus d’avantages ou d’inconvénients ? Pourquoi ?" },
  { id:7,  theme:'famille',      done:false, q:"À votre avis, peut-on être épanoui en vivant seul ?" },
  { id:8,  theme:'culture',      done:false, q:"Les loisirs culturels (musées, théâtres, etc.) devraient être gratuits. Qu’en pensez-vous ?" },
  { id:9,  theme:'culture',      done:false, q:"D’après vous, le style vestimentaire a-t-il une importance dans la vie quotidienne ? Pourquoi ?" },
  { id:10, theme:'immigration',  done:false, q:"Apprendre la langue du pays où l’on vit est essentiel pour s’intégrer. Êtes-vous d’accord ? Pourquoi ?" },
  { id:11, theme:'techno',       done:false, q:"Les jeux vidéo contribuent-ils au développement de l’enfant ? Qu’en pensez-vous ?" },
  { id:12, theme:'travail',      done:false, q:"Selon vous, aimer son métier est-il nécessaire pour réussir sa carrière professionnelle ? Pourquoi ?" },
  { id:13, theme:'environnement',done:false, q:"Les transports en commun devraient être gratuits pour protéger l’environnement. Qu’en pensez-vous ?" },
  { id:14, theme:'immigration',  done:false, q:"Est-il indispensable de vivre dans un pays pour bien connaître sa culture ? Expliquez pourquoi." },
  { id:15, theme:'famille',      done:false, q:"Pensez-vous qu’il vaut mieux avoir une grande famille ou des amis proches ? Qu’en pensez-vous ?" },
  { id:16, theme:'etudes',       done:false, q:"Quelles matières devraient être enseignées à l’école pour capter davantage l’intérêt des élèves ? Pourquoi ?" },
  { id:17, theme:'sante',        done:false, q:"Il est possible de vivre sans médicaments. Êtes-vous d’accord avec cette affirmation ?" },
  { id:18, theme:'travail',      done:false, q:"Le télétravail permet-il réellement de mieux concilier la vie professionnelle et la vie personnelle ? Qu’en pensez-vous ?" },
  { id:19, theme:'societe',      done:false, q:"Selon vous, est-il important de dédier une journée aux droits des femmes ? Pourquoi ?" },
  { id:20, theme:'travail',      done:false, q:"Comment les entreprises peuvent-elles aider les nouveaux employés à bien s’intégrer ?" },
  { id:21, theme:'etudes',       done:false, q:"Quel cours aimiez-vous le plus à l’école ? Expliquez pourquoi c’était votre préféré." },
  { id:22, theme:'travail',      done:false, q:"D’après vous, Internet a-t-il modifié les comportements au travail ? Qu’en pensez-vous ?" },
  { id:23, theme:'environnement',done:false, q:"La voiture est indispensable dans notre vie. Êtes vous d’accord avec cette affirmation ?" },
  { id:24, theme:'immigration',  done:false, q:"Faut-il s’intégrer dans la culture du pays d’accueil ou préserver sa propre culture ?" },
  { id:25, theme:'travail',      done:false, q:"Travailler jusqu’à l’âge de 70 ans, est-ce une bonne idée ? Qu’en pensez-vous ?" },
  { id:26, theme:'medias',       done:false, q:"De nos jours, peut-on se passer de la télévision ? Pourquoi ?" },
  { id:27, theme:'immigration',  done:false, q:"Travailler à l’étranger est facile. Qu’en pensez-vous ?" },
  { id:28, theme:'travail',      done:false, q:"Préférez-vous travailler sous la direction d’un homme ou d’une femme ? Pourquoi ?" },
  { id:29, theme:'travail',      done:false, q:"À votre avis, le salaire est-il la principale source de motivation pour les employés ? Pourquoi ?" },
  { id:30, theme:'techno',       done:false, q:"De nos jours, il est impossible de vivre sans technologie. Qu’en pensez-vous ?" },
  { id:31, theme:'societe',      done:false, q:"Pour certains, les sportifs professionnels gagnent beaucoup trop d’argent. Êtes-vous d’accord ?" },
  { id:32, theme:'techno',       done:false, q:"Selon vous, les enfants passent-ils trop de temps devant les écrans (télévisions, ordinateurs, téléphones, tablettes, etc.) ? Pourquoi ?" },
  { id:33, theme:'immigration',  done:false, q:"Si vous partez vivre au Canada, pensez-vous pouvoir trouver facilement un emploi ? Pourquoi ?" },
  { id:34, theme:'travail',      done:false, q:"Certaines personnes pensent qu’il vaut mieux éviter de travailler avec des amis ou des membres de sa famille. Êtes-vous d’accord ?" },
  { id:35, theme:'travail',      done:false, q:"Autoriser la sieste au travail est une bonne idée. Qu’en pensez-vous ?" },
  { id:36, theme:'etudes',       done:false, q:"Pensez-vous qu’il soit essentiel d’apprendre des langues étrangères ? Pourquoi ?" },
  { id:37, theme:'techno',       done:false, q:"Faut-il apprendre l’utilisation des nouvelles technologies (réseaux sociaux, Internet, etc.) dès le plus jeune âge ? Pourquoi ?" },
  { id:38, theme:'immigration',  done:false, q:"Parler la langue du pays d’accueil suffit-il pour bien s’intégrer ? Pourquoi ?" },
  { id:39, theme:'etudes',       done:false, q:"Pour réussir sa vie, faut-il avoir fait de longues études ?" },
  { id:40, theme:'tourisme',     done:false, q:"Certains choisissent de voyager en solitaire. Qu’en pensez-vous ?" },
  { id:41, theme:'famille',      done:false, q:"Il est plus facile de vivre seul(e) qu’en famille. Qu’en pensez-vous ?" },
  { id:42, theme:'tourisme',     done:false, q:"Le développement du tourisme peut abîmer certaines régions. Qu’en pensez-vous ?" },
  { id:43, theme:'societe',      done:false, q:"Pour des raisons d’égalité, avoir autant d’hommes que de femmes dans un gouvernement est-il une bonne idée ? Pourquoi ?" },
  { id:44, theme:'sante',        done:false, q:"Les habitudes alimentaires évoluent au fil de la vie. Qu’en pensez-vous ?" },
  { id:45, theme:'tourisme',     done:false, q:"En quoi le tourisme contribue-t-il à l’économie et au développement d’un pays ?" },
  { id:46, theme:'travail',      done:false, q:"Le téléphone portable personnel devrait être interdit au travail. Qu’en pensez-vous ?" },
  { id:47, theme:'etudes',       done:false, q:"Les matières culturelles (musique, dessin, théâtre, etc.) ne devraient pas être enseignées à l’école. Êtes-vous d’accord ? Pourquoi ?" },
  { id:48, theme:'societe',      done:false, q:"Les associations et les ONG sont les seules à pouvoir aider les plus pauvres. Qu’en pensez-vous ?" },
  { id:49, theme:'techno',       done:false, q:"De nos jours, beaucoup de personnes changent régulièrement de téléphone portable. Qu’en pensez-vous ?" },
  { id:50, theme:'medias',       done:false, q:"Selon vous, pourquoi la vie des célébrités attire-t-elle autant l’attention du public ?" },
  { id:51, theme:'immigration',  done:false, q:"Si vous immigrez, est-il important pour vous de bien connaître le pays d’accueil ?" },
  { id:52, theme:'sante',        done:false, q:"Les soins de santé doivent être gratuits pour tout le monde. Qu’en pensez-vous ?" },
  { id:53, theme:'societe',      done:false, q:"Pensez-vous qu’un monde sans frontières, sans passeports et sans visas serait possible ? Pourquoi ?" },
  { id:54, theme:'travail',      done:false, q:"Les employeurs doivent donner la possibilité de suivre des formations tout au long de la vie. Est-ce utile pour chacun ? Qu’en pensez-vous ?" },
  { id:55, theme:'travail',      done:false, q:"Pour évoluer dans son entreprise, il faut avant tout être compétent dans son travail. Partagez-vous cette opinion ?" },
  { id:56, theme:'environnement',done:false, q:"Quel est votre avis sur les mesures prises dans votre pays pour réduire la pollution ?" },
  { id:57, theme:'tourisme',     done:false, q:"Pensez-vous qu’il faudrait davantage développer le tourisme dans votre pays ? Pourquoi ?" },
  { id:58, theme:'famille',      done:false, q:"D’après vous, la famille est-elle ce qu’il y a de plus important dans la vie ?" },
  { id:59, theme:'techno',       done:false, q:"À votre avis, quels sont les effets des jeux vidéo sur les enfants ? Pourquoi ?" },
  { id:60, theme:'techno',       done:false, q:"Aujourd’hui, peut-on encore vivre sans Internet ? Qu’en pensez-vous ?" },
  { id:61, theme:'techno',       done:false, q:"Aujourd’hui, chaque enfant et adolescent devrait avoir son propre téléphone portable. Êtes-vous d’accord ?" },
  { id:62, theme:'immigration',  done:false, q:"Adaptation à l’étranger : Évoquez les facilités et les défis de l’intégration d’un jeune qui déménage à l’étranger." },
  { id:63, theme:'travail',      done:false, q:"De nos jours, il est possible de changer de métier à tout âge. Qu’en pensez-vous ?" },
  { id:64, theme:'techno',       done:false, q:"À la maison, les parents devraient interdire à leurs enfants l’utilisation d’Internet. Êtes-vous d’accord avec cette affirmation ?" },
  { id:65, theme:'sante',        done:false, q:"Le stress est un bon stimulant. Qu’en pensez-vous ?" },
  { id:66, theme:'sante',        done:false, q:"Les menus végétariens sont-ils une alternative saine et durable à l’alimentation traditionnelle ? Qu’en pensez-vous ?" },
  { id:67, theme:'tourisme',     done:false, q:"Pour quelle(s) raison(s) voudrait-on développer le tourisme dans un pays ?" },
  { id:68, theme:'techno',       done:false, q:"Quels effets et quels risques voyez-vous dans l’usage quotidien des appareils électroniques comme les téléphones, ordinateurs ou tablettes ?" },
  { id:69, theme:'societe',      done:false, q:"De nos jours, les gens ne s’envoient presque plus de courrier (cartes de vœux, lettres d’amour, etc.). Est-ce que c’est regrettable ?" },
  { id:70, theme:'environnement',done:false, q:"Les petits gestes du quotidien peuvent-ils vraiment contribuer à la protection de la planète ? Qu’en pensez-vous ?" },
  { id:71, theme:'societe',      done:false, q:"À votre avis, parmi les grandes causes actuelles (sociale, humanitaire ou culturelle), laquelle devrait être prioritaire dans le monde d’aujourd’hui ? Expliquez pourquoi." },
  { id:72, theme:'sante',        done:false, q:"Comment trouvez-vous l’alimentation dans votre pays ?" },
  { id:73, theme:'societe',      done:false, q:"De nos jours, tout le monde veut rester jeune. Qu’en pensez-vous ?" },
  { id:74, theme:'sante',        done:false, q:"Que pensez-vous du développement de l’agriculture biologique ?" },
  { id:75, theme:'culture',      done:false, q:"De nos jours, le livre est devenu inutile. Êtes-vous d’accord avec cette affirmation ?" },
  { id:76, theme:'societe',      done:false, q:"La gentillesse aide-t-elle toujours à se faire écouter et respecter ? Êtes-vous d’accord avec cette idée ?" },
  { id:77, theme:'famille',      done:false, q:"Vivre avec ses parents après l’âge de 25 ans peut être pratique. Qu’en pensez-vous ?" },
  { id:78, theme:'etudes',       done:false, q:"Pensez-vous que les universités devraient recevoir davantage de financements ? Pourquoi ?" },
  { id:79, theme:'tourisme',     done:false, q:"Quelles activités ou visites proposeriez-vous à un touriste étranger qui découvre votre pays pour la première fois ? Pourquoi ?" },
  { id:80, theme:'culture',      done:false, q:"Selon vous, comment pourrait-on encourager les gens à pratiquer plus de sport ?" },
  { id:81, theme:'travail',      done:false, q:"Tout le monde est capable d’occuper des fonctions de responsable (responsable d’un service, un magasin, une association, etc.). Qu’en pensez-vous ?" },
  { id:82, theme:'environnement',done:false, q:"Pour protéger la planète, les gouvernements devraient limiter les trajets en avion des citoyens. Qu’en pensez-vous ?" },
  { id:83, theme:'animaux',      done:false, q:"La place accordée aux animaux de compagnie dans la société est trop importante. Qu’en pensez-vous ?" },
  { id:84, theme:'environnement',done:false, q:"L’écologie devrait être enseignée dès le plus jeune âge. Est-ce que vous êtes d’accord ?" },
  { id:85, theme:'sante',        done:false, q:"Pour être en bonne santé, il est préférable de vivre à la campagne plutôt qu’en ville. Êtes-vous d’accord ?" },
  { id:86, theme:'immigration',  done:false, q:"S’expatrier en famille est plus simple que de partir seul(e). Êtes-vous d’accord avec cette idée ?" },
  { id:87, theme:'societe',      done:false, q:"Pensez-vous que les caméras installées dans les lieux publics améliorent vraiment la sécurité ? Êtes-vous d’accord ?" },
  { id:88, theme:'animaux',      done:false, q:"Pour quelles raisons voudrait-on un animal de compagnie chez soi ?" },
  { id:89, theme:'immigration',  done:false, q:"Est-ce que les bénéfices de vivre à l’étranger surpassent ses inconvénients ? Pourquoi ?" },
  { id:90, theme:'sante',        done:false, q:"Pour rester en bonne santé, faut-il consommer uniquement des produits biologiques ? Êtes-vous d’accord ?" },
  { id:91, theme:'etudes',       done:false, q:"Il faut faire de longues études pour gagner beaucoup d’argent. Qu’en pensez-vous ?" },
  { id:92, theme:'immigration',  done:false, q:"Est-il facile de garder un lien avec sa culture d’origine quand on vit dans un autre pays ? Pourquoi ?" },
  { id:93, theme:'societe',      done:false, q:"La gentillesse permet toujours d’être entendu et respecté. Êtes-vous d’accord avec cette affirmation ?" },
  { id:94, theme:'techno',       done:false, q:"À votre avis, l’usage des téléphones portables devrait-il être interdit aux enfants ? Pourquoi ?" },
  { id:95, theme:'medias',       done:false, q:"Regarder la télé permet de s’instruire. Qu’en pensez-vous ?" },
  { id:96, theme:'animaux',      done:false, q:"Quelle est votre opinion sur le fait d’avoir un animal domestique chez soi ?" },
  { id:97, theme:'travail',      done:false, q:"D’après vous, jusqu’à quel âge peut-on travailler ? Quelles en sont les raisons ?" },
  { id:98, theme:'sante',        done:false, q:"Pensez-vous que les gens cuisinent encore beaucoup aujourd’hui ? Pourquoi ?" },
  { id:99, theme:'medias',       done:false, q:"Avez-vous confiance dans les informations que vous trouvez sur Internet ? Pourquoi ?" },
  { id:100,theme:'environnement',done:false, q:"Pour préserver l’environnement, il faut consommer des produits locaux et de saison. Êtes-vous d’accord avec cette idée ?" },
  { id:101,theme:'travail',      done:false, q:"Quel métier aimeriez-vous tester un jour ? Expliquez votre choix." },
  { id:102,theme:'tourisme',     done:false, q:"Beaucoup de personnes n’aiment pas voyager seules. Êtes-vous d’accord avec cette idée ? Pourquoi ?" },
  { id:103,theme:'tourisme',     done:false, q:"Selon vous, comment expliquer l’intérêt pour les déplacements en train, en avion ou en bus (selon la situation locale) ?" },
  { id:104,theme:'societe',      done:false, q:"Pour quelles raisons peut-on choisir de participer à une action humanitaire ?" },
  { id:105,theme:'travail',      done:false, q:"Le plus important dans la vie, c’est d’être heureux au travail. Qu’en pensez-vous ?" },
  { id:106,theme:'sante',        done:false, q:"Pour rester en bonne santé, est-ce que bien manger est l’élément le plus essentiel ? Qu’en pensez-vous ?" },
  { id:107,theme:'societe',      done:false, q:"Pensez-vous que les aides sociales réduisent la solidarité familiale ? Justifiez votre réponse." },
  { id:108,theme:'etudes',       done:false, q:"Il n’y a pas d’âge limite pour apprendre. Êtes-vous d’accord avec cette affirmation ?" },
  { id:109,theme:'immigration',  done:false, q:"Est-il facile de se faire des amis quand on s’installe dans un nouveau pays ? Pourquoi selon vous ?" },
  { id:110,theme:'medias',       done:false, q:"Certaines personnes refusent de regarder les actualités diffusées à la télévision. Qu’en pensez-vous ?" },
  { id:111,theme:'travail',      done:false, q:"Est-il bon de faire plusieurs métiers dans sa carrière ? Qu’en pensez-vous ?" },
  { id:112,theme:'societe',      done:false, q:"L’État ne peut pas tout contrôler : êtes-vous d’accord avec cette affirmation ? Pourquoi ?" },
  { id:113,theme:'societe',      done:false, q:"Êtes-vous d’accord avec cette affirmation : les adultes portent un regard pessimiste sur les jeunes ? Pourquoi ?" },
  { id:114,theme:'techno',       done:false, q:"Le téléphone portable est indispensable. Qu’en pensez-vous ?" },
  { id:115,theme:'tourisme',     done:false, q:"Le voyage fait de vous une meilleure personne. Êtes-vous d’accord avec cette affirmation ?" },
  { id:116,theme:'famille',      done:false, q:"De nombreux jeunes adultes au Canada décident de continuer à vivre chez leurs parents car ils s’y sentent à l’aise. Que pensez-vous de cette situation ?" },
  { id:117,theme:'immigration',  done:false, q:"Selon vous, quelles sont les trois questions importantes à se poser avant de commencer des démarches d’immigration au Québec ? Pourquoi ces trois-là ?" },
  { id:118,theme:'techno',       done:false, q:"Internet a transformé le monde en un village. Qu’en pensez-vous ?" },
  { id:119,theme:'famille',      done:false, q:"Certaines personnes choisissent de ne jamais avoir d’enfants. Qu’en pensez-vous ?" },
  { id:120,theme:'medias',       done:false, q:"Pensez-vous que les journaux télévisés devraient éviter de diffuser des images violentes ?" },
];
