// ═══════════════════════════════════════════════════════════════
//  BANQUE DE SUJETS — Expression Orale, Tâche 3
//  Source : relevé des sujets réellement tombés. `freq` = nombre
//  d'occurrences constatées, `diff` = indice d'ambiguïté /10.
//  L'ordre d'affichage suit la fréquence : le plus probable en tête.
//  `done:true` = un entraînement existe dans eo-trainers.js.
//  Tout le reste attend encore une réponse.
// ═══════════════════════════════════════════════════════════════

const EO_THEMES = [
  { id:'edu', emoji:'📚', fa:'آموزش و یادگیری', fr:'Éducation', color:'#43a047' },   // 29
  { id:'trav', emoji:'💼', fa:'کار و اقتصاد', fr:'Travail', color:'#1e88e5' },   // 33
  { id:'imm', emoji:'🌍', fa:'مهاجرت و زندگی در خارج', fr:'Immigration', color:'#fb8c00' },   // 40
  { id:'tech', emoji:'📱', fa:'فناوری و رسانه', fr:'Technologie', color:'#8e24aa' },   // 47
  { id:'env', emoji:'🌿', fa:'محیط‌زیست و محیط زندگی', fr:'Environnement', color:'#2e7d32' },   // 30
  { id:'voy', emoji:'✈️', fa:'سفر و فرهنگ', fr:'Voyage', color:'#00acc1' },   // 27
  { id:'sante', emoji:'🏥', fa:'سلامت و تغذیه', fr:'Santé', color:'#d81b60' },   // 17
  { id:'fam', emoji:'👨‍👩‍👧', fa:'خانواده و روابط اجتماعی', fr:'Famille', color:'#6d4c41' },   // 30
  { id:'soc', emoji:'⚖️', fa:'جامعه و شهروندی', fr:'Société', color:'#546e7a' },   // 32
  { id:'val', emoji:'💡', fa:'ارزش‌ها و تعهد', fr:'Valeurs', color:'#5e35b1' },   // 19
  { id:'sport', emoji:'⚽', fa:'ورزش و تفریح', fr:'Sport', color:'#7cb342' },   // 5
];

const EO_QUESTIONS = [
  { id:1, theme:'edu', freq:43, diff:4, done:true , q:"Faire des études permet de réussir sa carrière professionnelle. Qu'en pensez-vous ?" },
  { id:6, theme:'imm', freq:37, diff:3, done:true , q:"D'après vous, vivre à l'étranger a-t-il plus d'avantages ou d'inconvénients ? Pourquoi ?" },
  { id:8, theme:'edu', freq:35, diff:5, done:false, q:"Apprendre la langue du pays où l'on vit est essentiel pour s'intégrer. Êtes-vous d'accord ? Pourquoi ?" },
  { id:3, theme:'edu', freq:32, diff:4, done:true , q:"Selon vous, quel rôle joue la télévision dans l'éducation des enfants ?" },
  { id:9, theme:'env', freq:30, diff:3, done:false, q:"La voiture est indispensable dans notre vie. Êtes-vous d'accord avec cette affirmation ?" },
  { id:10, theme:'imm', freq:29, diff:6, done:false, q:"Faut-il s'intégrer dans la culture du pays d'accueil ou préserver sa propre culture ?" },
  { id:11, theme:'fam', freq:27, diff:4, done:false, q:"Les jeux vidéo contribuent-ils au développement de l'enfant ? Qu'en pensez-vous ?" },
  { id:4, theme:'fam', freq:26, diff:5, done:true , q:"Pensez-vous que l'autorité soit indispensable dans l'éducation d'un enfant ? Pourquoi ?" },
  { id:12, theme:'tech', freq:26, diff:5, done:false, q:"Pensez-vous que l'utilisation d'Internet favorise l'isolement des individus ? Donnez votre avis sur cette idée." },
  { id:13, theme:'tech', freq:26, diff:3, done:false, q:"Aujourd'hui, chaque enfant et adolescent devrait avoir son propre téléphone portable. Êtes-vous d'accord ?" },
  { id:14, theme:'trav', freq:26, diff:4, done:false, q:"Travailler jusqu'à l'âge de 70 ans, est-ce une bonne idée ? Qu'en pensez-vous ?" },
  { id:2, theme:'imm', freq:22, diff:5, done:true , q:"Quel est l'intérêt d'avoir une expérience professionnelle ou universitaire à l'étranger ?" },
  { id:15, theme:'tech', freq:21, diff:7, done:false, q:"De nos jours, peut-on se passer de la télévision ? Pourquoi ?" },
  { id:16, theme:'trav', freq:21, diff:3, done:false, q:"Selon vous, aimer son métier est-il nécessaire pour réussir sa carrière professionnelle ? Pourquoi ?" },
  { id:17, theme:'voy', freq:21, diff:3, done:false, q:"Certains choisissent de voyager en solitaire. Qu'en pensez-vous ?" },
  { id:18, theme:'imm', freq:20, diff:4, done:false, q:"Travailler à l'étranger est facile. Qu'en pensez-vous ?" },
  { id:19, theme:'env', freq:19, diff:4, done:false, q:"Les transports en commun devraient être gratuits pour protéger l'environnement. Qu'en pensez-vous ?" },
  { id:20, theme:'voy', freq:19, diff:4, done:false, q:"Est-il indispensable de vivre dans un pays pour bien connaître sa culture ? Expliquez pourquoi." },
  { id:21, theme:'imm', freq:18, diff:6, done:false, q:"Adaptation à l'étranger : évoquez les facilités et les défis de l'intégration d'un jeune qui déménage à l'étranger." },
  { id:22, theme:'fam', freq:17, diff:2, done:false, q:"Il est plus facile de vivre seul(e) qu'en famille. Qu'en pensez-vous ?" },
  { id:23, theme:'soc', freq:16, diff:5, done:false, q:"Préférez-vous travailler sous la direction d'un homme ou d'une femme ? Pourquoi ?" },
  { id:24, theme:'trav', freq:16, diff:3, done:false, q:"À votre avis, le salaire est-il la principale source de motivation pour les employés ? Pourquoi ?" },
  { id:25, theme:'fam', freq:16, diff:4, done:false, q:"Pensez-vous qu'il vaut mieux avoir une grande famille ou des amis proches ? Qu'en pensez-vous ?" },
  { id:26, theme:'trav', freq:16, diff:3, done:false, q:"De nos jours, il est possible de changer de métier à tout âge. Qu'en pensez-vous ?" },
  { id:27, theme:'voy', freq:16, diff:5, done:false, q:"Les loisirs culturels (musées, théâtres, etc.) devraient être gratuits. Qu'en pensez-vous ?" },
  { id:28, theme:'voy', freq:16, diff:6, done:false, q:"Le développement du tourisme peut abîmer certaines régions. Qu'en pensez-vous ?" },
  { id:29, theme:'val', freq:15, diff:4, done:false, q:"De nos jours, tout le monde veut paraître beau. Que pensez-vous de la beauté ?" },
  { id:30, theme:'tech', freq:15, diff:5, done:false, q:"À la maison, les parents devraient interdire à leurs enfants l'utilisation d'Internet. Êtes-vous d'accord avec cette affirmation ?" },
  { id:31, theme:'sante', freq:15, diff:7, done:false, q:"Le stress est un bon stimulant. Qu'en pensez-vous ?" },
  { id:32, theme:'soc', freq:14, diff:5, done:false, q:"Pour des raisons d'égalité, avoir autant d'hommes que de femmes dans un gouvernement est-il une bonne idée ? Pourquoi ?" },
  { id:33, theme:'env', freq:14, diff:4, done:false, q:"Les menus végétariens sont-ils une alternative saine et durable à l'alimentation traditionnelle ? Qu'en pensez-vous ?" },
  { id:7, theme:'val', freq:13, diff:7, done:true , q:"À votre avis, peut-on être épanoui en vivant seul ?" },
  { id:34, theme:'tech', freq:13, diff:2, done:false, q:"De nos jours, il est impossible de vivre sans technologie. Qu'en pensez-vous ?" },
  { id:35, theme:'trav', freq:13, diff:5, done:false, q:"Le télétravail permet-il réellement de mieux concilier la vie professionnelle et la vie personnelle ? Qu'en pensez-vous ?" },
  { id:36, theme:'soc', freq:13, diff:5, done:false, q:"D'après vous, le style vestimentaire a-t-il une importance dans la vie quotidienne ? Pourquoi ?" },
  { id:37, theme:'sport', freq:13, diff:3, done:false, q:"Pour certains, les sportifs professionnels gagnent beaucoup trop d'argent. Êtes-vous d'accord ?" },
  { id:38, theme:'edu', freq:13, diff:4, done:false, q:"Il n'y a pas d'âge limite pour apprendre. Êtes-vous d'accord avec cette affirmation ?" },
  { id:5, theme:'imm', freq:12, diff:3, done:true , q:"Est-ce que vous pensez qu'il est difficile de vivre dans un pays étranger ? Pourquoi ?" },
  { id:39, theme:'sante', freq:12, diff:5, done:false, q:"Les habitudes alimentaires évoluent au fil de la vie. Qu'en pensez-vous ?" },
  { id:40, theme:'tech', freq:12, diff:4, done:false, q:"Quels effets et quels risques voyez-vous dans l'usage quotidien des appareils électroniques comme les téléphones, ordinateurs ou tablettes ?" },
  { id:41, theme:'voy', freq:12, diff:3, done:false, q:"Pour quelle(s) raison(s) voudrait-on développer le tourisme dans un pays ?" },
  { id:42, theme:'edu', freq:12, diff:5, done:false, q:"Quelles matières devraient être enseignées à l'école pour capter davantage l'intérêt des élèves ? Pourquoi ?" },
  { id:43, theme:'tech', freq:11, diff:4, done:false, q:"Certaines personnes refusent de regarder les actualités diffusées à la télévision. Qu'en pensez-vous ?" },
  { id:44, theme:'voy', freq:11, diff:5, done:false, q:"En quoi le tourisme contribue-t-il à l'économie et au développement d'un pays ?" },
  { id:45, theme:'tech', freq:11, diff:3, done:false, q:"Dans le futur, avec les nouvelles technologies, nous n'aurons plus besoin de travailler. Qu'en pensez-vous ?" },
  { id:46, theme:'soc', freq:11, diff:5, done:false, q:"Selon vous, est-il important de dédier une journée aux droits des femmes ? Pourquoi ?" },
  { id:47, theme:'fam', freq:11, diff:5, done:false, q:"Est-il facile de se faire des amis quand on s'installe dans un nouveau pays ? Pourquoi selon vous ?" },
  { id:48, theme:'edu', freq:11, diff:2, done:false, q:"Quel cours aimiez-vous le plus à l'école ? Expliquez pourquoi c'était votre préféré." },
  { id:49, theme:'imm', freq:11, diff:4, done:false, q:"Comment les entreprises peuvent-elles aider les nouveaux employés à bien s'intégrer ?" },
  { id:50, theme:'tech', freq:11, diff:5, done:false, q:"De nos jours, les gens ne s'envoient presque plus de courrier (cartes de vœux, lettres d'amour, etc.). Est-ce que c'est regrettable ?" },
  { id:51, theme:'env', freq:10, diff:5, done:false, q:"Les petits gestes du quotidien peuvent-ils vraiment contribuer à la protection de la planète ? Qu'en pensez-vous ?" },
  { id:52, theme:'tech', freq:10, diff:3, done:false, q:"Selon vous, les enfants passent-ils trop de temps devant les écrans (télévisions, ordinateurs, téléphones, tablettes, etc.) ? Pourquoi ?" },
  { id:53, theme:'trav', freq:10, diff:4, done:false, q:"Si vous partez vivre au Canada, pensez-vous pouvoir trouver facilement un emploi ? Pourquoi ?" },
  { id:54, theme:'val', freq:10, diff:6, done:false, q:"À votre avis, parmi les grandes causes actuelles (sociale, humanitaire ou culturelle), laquelle devrait être prioritaire dans le monde d'aujourd'hui ? Expliquez pourquoi." },
  { id:55, theme:'fam', freq:10, diff:4, done:false, q:"Certaines personnes pensent qu'il vaut mieux éviter de travailler avec des amis ou des membres de sa famille. Êtes-vous d'accord ?" },
  { id:56, theme:'tech', freq:10, diff:4, done:false, q:"D'après vous, Internet a-t-il modifié les comportements au travail ? Qu'en pensez-vous ?" },
  { id:57, theme:'sante', freq:10, diff:5, done:false, q:"Comment trouvez-vous l'alimentation dans votre pays ?" },
  { id:58, theme:'tech', freq:10, diff:3, done:false, q:"Le téléphone portable est indispensable. Qu'en pensez-vous ?" },
  { id:59, theme:'trav', freq:10, diff:4, done:false, q:"Les métiers les plus difficiles devraient être les mieux payés. Qu'en pensez-vous ?" },
  { id:60, theme:'val', freq:10, diff:5, done:false, q:"De nos jours, tout le monde veut rester jeune. Qu'en pensez-vous ?" },
  { id:61, theme:'soc', freq:10, diff:3, done:false, q:"Est-ce que vous pensez que l'État devrait interdire la vente de tabac et d'alcool ? Pourquoi ?" },
  { id:62, theme:'env', freq:10, diff:4, done:false, q:"Les zoos ont-ils une utilité ? Pourquoi ?" },
  { id:63, theme:'tech', freq:10, diff:4, done:false, q:"Le téléphone portable personnel devrait être interdit au travail. Qu'en pensez-vous ?" },
  { id:64, theme:'trav', freq:10, diff:9, done:false, q:"Est-il bon de faire plusieurs métiers dans sa carrière ? Qu'en pensez-vous ?" },
  { id:65, theme:'soc', freq:10, diff:5, done:false, q:"L'État ne peut pas tout contrôler : êtes-vous d'accord avec cette affirmation ? Pourquoi ?" },
  { id:66, theme:'fam', freq:10, diff:7, done:false, q:"Êtes-vous d'accord avec cette affirmation : les adultes portent un regard pessimiste sur les jeunes ? Pourquoi ?" },
  { id:67, theme:'sante', freq:9, diff:5, done:false, q:"Chaque année, à l'arrivée de l'été, beaucoup de magazines proposent des régimes pour perdre du poids. Pensez-vous que ces conseils sont utiles et sérieux ? Pourquoi ?" },
  { id:68, theme:'soc', freq:9, diff:5, done:false, q:"Dans une entreprise, tout le monde devrait avoir le même salaire. Que pensez-vous de cette affirmation ?" },
  { id:69, theme:'tech', freq:9, diff:6, done:false, q:"Internet a transformé le monde en un village. Qu'en pensez-vous ?" },
  { id:70, theme:'fam', freq:9, diff:3, done:false, q:"Certaines personnes choisissent de ne jamais avoir d'enfants. Qu'en pensez-vous ?" },
  { id:71, theme:'val', freq:9, diff:5, done:false, q:"Pensez-vous que les journaux télévisés devraient éviter de diffuser des images violentes ?" },
  { id:72, theme:'voy', freq:9, diff:3, done:false, q:"Pensez-vous que voyager est vraiment utile ? Pourquoi ?" },
  { id:73, theme:'fam', freq:9, diff:3, done:false, q:"Il n'est pas nécessaire d'avoir des ami(e)s pour être heureux(se). Qu'en pensez-vous ?" },
  { id:74, theme:'voy', freq:9, diff:3, done:false, q:"Les voyages dans l'espace coûtent trop cher et sont inutiles. Qu'en pensez-vous ?" },
  { id:75, theme:'imm', freq:9, diff:7, done:false, q:"Selon vous, quelles sont les trois questions importantes à se poser avant de commencer des démarches d'immigration au Québec ? Pourquoi ces trois-là ?" },
  { id:76, theme:'voy', freq:9, diff:3, done:false, q:"Le voyage fait de vous une meilleure personne. Êtes-vous d'accord avec cette affirmation ?" },
  { id:77, theme:'env', freq:9, diff:3, done:false, q:"Les animaux de compagnie sont-ils essentiels pour le bien-être des personnes âgées ? Qu'en pensez-vous ?" },
  { id:78, theme:'sante', freq:9, diff:5, done:false, q:"Il est possible de vivre sans médicaments. Êtes-vous d'accord avec cette affirmation ?" },
  { id:79, theme:'fam', freq:9, diff:5, done:false, q:"De nombreux jeunes adultes au Canada décident de continuer à vivre chez leurs parents car ils s'y sentent à l'aise. Que pensez-vous de cette situation ?" },
  { id:80, theme:'voy', freq:8, diff:6, done:false, q:"La lecture est souvent liée à la culture. Faut-il lire pour être cultivé ? Qu'en pensez-vous ?" },
  { id:81, theme:'imm', freq:8, diff:6, done:false, q:"Lorsqu'une personne quitte son pays pour vivre ailleurs, c'est souvent une décision imposée. Qu'en pensez-vous ?" },
  { id:82, theme:'soc', freq:8, diff:4, done:false, q:"D'après vous, la liberté d'expression doit-elle avoir des limites ? Pourquoi ?" },
  { id:83, theme:'val', freq:8, diff:6, done:false, q:"Quelles sont les actions citoyennes (aide alimentaire, visite à des malades, projet écologique, etc.) que vous jugez admirables ? Pourquoi ?" },
  { id:84, theme:'imm', freq:8, diff:3, done:false, q:"À votre avis, tout le monde est-il capable de s'adapter dans un pays étranger ? Pourquoi ?" },
  { id:85, theme:'edu', freq:8, diff:6, done:false, q:"La priorité de l'école, c'est d'enseigner le programme scolaire. Que pensez-vous de cette affirmation ? Pourquoi ?" },
  { id:86, theme:'env', freq:8, diff:4, done:false, q:"Que pensez-vous du développement de l'agriculture biologique ?" },
  { id:87, theme:'voy', freq:8, diff:4, done:false, q:"Les matières culturelles (musique, dessin, théâtre, etc.) ne devraient pas être enseignées à l'école. Êtes-vous d'accord ? Pourquoi ?" },
  { id:88, theme:'voy', freq:7, diff:4, done:false, q:"Avez-vous une préférence entre les pièces de théâtre et les films ? Expliquez votre choix." },
  { id:89, theme:'edu', freq:7, diff:4, done:false, q:"Internet a un impact positif dans l'éducation des enfants. Qu'en pensez-vous ?" },
  { id:90, theme:'imm', freq:7, diff:4, done:false, q:"À votre avis, comment un État peut-il faciliter l'intégration des étrangers ?" },
  { id:91, theme:'val', freq:7, diff:6, done:false, q:"La gentillesse aide-t-elle toujours à se faire écouter et respecter ? Êtes-vous d'accord avec cette idée ?" },
  { id:92, theme:'voy', freq:7, diff:4, done:false, q:"Selon vous, pourquoi la vie des célébrités attire-t-elle autant l'attention du public ?" },
  { id:93, theme:'sante', freq:7, diff:3, done:false, q:"Les soins de santé doivent être gratuits pour tout le monde. Qu'en pensez-vous ?" },
  { id:94, theme:'sante', freq:7, diff:6, done:false, q:"Autoriser la sieste au travail est une bonne idée. Qu'en pensez-vous ?" },
  { id:95, theme:'val', freq:7, diff:6, done:false, q:"Pendant leur temps libre, certaines personnes s'engagent dans des associations pour aider les autres. Qu'en pensez-vous ?" },
  { id:96, theme:'val', freq:7, diff:6, done:false, q:"Beaucoup de gens ont recours à la chirurgie esthétique pour paraître plus jeunes. Qu'en pensez-vous ?" },
  { id:97, theme:'trav', freq:7, diff:3, done:false, q:"Trouver un emploi peut être plus compliqué quand on est jeune. Êtes-vous d'accord ? Pourquoi ?" },
  { id:98, theme:'fam', freq:7, diff:8, done:false, q:"Les parents doivent contrôler les fréquentations de leurs enfants. Qu'en pensez-vous ?" },
  { id:99, theme:'fam', freq:7, diff:5, done:false, q:"De nos jours, les jeunes sont de moins en moins polis. Êtes-vous d'accord ? Pourquoi ?" },
  { id:100, theme:'voy', freq:7, diff:4, done:false, q:"La cuisine est un excellent moyen pour faire connaître son pays. Êtes-vous d'accord avec cette affirmation ?" },
  { id:101, theme:'voy', freq:7, diff:4, done:false, q:"De nos jours, le livre est devenu inutile. Êtes-vous d'accord avec cette affirmation ?" },
  { id:102, theme:'imm', freq:6, diff:6, done:false, q:"D'après vous, à quel âge est-il préférable d'émigrer ? Pourquoi ?" },
  { id:103, theme:'imm', freq:6, diff:5, done:false, q:"Selon vous, les immigrés apportent-ils une valeur importante à un pays ? Pourquoi ?" },
  { id:104, theme:'tech', freq:6, diff:4, done:false, q:"Peut-on vraiment faire tous ses achats sur Internet ? Qu'en pensez-vous ?" },
  { id:105, theme:'env', freq:6, diff:3, done:false, q:"Pour les personnes âgées, la vie en ville est-elle plus facile qu'à la campagne ? Êtes-vous d'accord ?" },
  { id:106, theme:'sport', freq:6, diff:3, done:false, q:"Pensez-vous qu'il faut obliger les enfants à pratiquer une activité sportive ? Pourquoi ?" },
  { id:107, theme:'env', freq:6, diff:4, done:false, q:"D'après vous, est-il possible de développer l'économie et de respecter l'environnement en même temps ?" },
  { id:108, theme:'edu', freq:6, diff:3, done:false, q:"Apprendre une langue étrangère est difficile. Êtes-vous d'accord avec cette affirmation ?" },
  { id:109, theme:'tech', freq:6, diff:3, done:false, q:"Les réseaux sociaux permettent de rencontrer de nouveaux amis plus facilement. Qu'en pensez-vous ?" },
  { id:110, theme:'tech', freq:6, diff:3, done:false, q:"De nos jours, beaucoup de personnes changent régulièrement de téléphone portable. Qu'en pensez-vous ?" },
  { id:111, theme:'imm', freq:6, diff:3, done:false, q:"Prendre la décision de quitter son pays est facile. Qu'en pensez-vous ?" },
  { id:112, theme:'env', freq:6, diff:4, done:false, q:"Est-il important de développer les énergies renouvelables ?" },
  { id:113, theme:'imm', freq:6, diff:5, done:false, q:"Quelles sont les principales motivations qui incitent les gens à immigrer vers d'autres pays ? Pourquoi ?" },
  { id:114, theme:'soc', freq:6, diff:4, done:false, q:"Les parents doivent-ils éduquer leurs filles et leurs garçons de la même manière ? Qu'en pensez-vous ?" },
  { id:115, theme:'fam', freq:6, diff:5, done:false, q:"Vivre avec ses parents après l'âge de 25 ans peut être pratique. Qu'en pensez-vous ?" },
  { id:116, theme:'val', freq:6, diff:6, done:false, q:"Les associations et les ONG sont les seules à pouvoir aider les plus pauvres. Qu'en pensez-vous ?" },
  { id:117, theme:'edu', freq:6, diff:5, done:false, q:"Pensez-vous que les universités devraient recevoir davantage de financements ? Pourquoi ?" },
  { id:118, theme:'voy', freq:6, diff:3, done:false, q:"Quelles activités ou visites proposeriez-vous à un touriste étranger qui découvre votre pays pour la première fois ? Pourquoi ?" },
  { id:119, theme:'sport', freq:6, diff:3, done:false, q:"Selon vous, comment pourrait-on encourager les gens à pratiquer plus de sport ?" },
  { id:120, theme:'env', freq:6, diff:4, done:false, q:"Pour protéger la planète, les gouvernements devraient limiter les trajets en avion des citoyens. Qu'en pensez-vous ?" },
  { id:121, theme:'soc', freq:6, diff:5, done:false, q:"Pensez-vous qu'un monde sans frontières, sans passeports et sans visas serait possible ? Pourquoi ?" },
  { id:122, theme:'env', freq:6, diff:4, done:false, q:"Quel est votre avis sur les mesures prises dans votre pays pour réduire la pollution ?" },
  { id:123, theme:'imm', freq:6, diff:4, done:false, q:"Si vous immigrez, est-il important pour vous de bien connaître le pays d'accueil ?" },
  { id:124, theme:'tech', freq:6, diff:4, done:false, q:"Grâce à Internet, on est mieux informé. Qu'en pensez-vous ?" },
  { id:125, theme:'fam', freq:5, diff:6, done:false, q:"Est-il possible de nouer une amitié avec une personne dont les convictions sont opposées aux vôtres ?" },
  { id:126, theme:'val', freq:5, diff:5, done:false, q:"Tout le monde est capable d'occuper des fonctions de responsable (responsable d'un service, un magasin, une association, etc.). Qu'en pensez-vous ?" },
  { id:127, theme:'edu', freq:5, diff:2, done:false, q:"Pensez-vous qu'il soit essentiel d'apprendre des langues étrangères ? Pourquoi ?" },
  { id:128, theme:'soc', freq:5, diff:3, done:false, q:"Pensez-vous que les caméras installées dans les lieux publics améliorent vraiment la sécurité ? Êtes-vous d'accord ?" },
  { id:129, theme:'tech', freq:5, diff:3, done:false, q:"Faut-il apprendre l'utilisation des nouvelles technologies (réseaux sociaux, Internet, etc.) dès le plus jeune âge ? Pourquoi ?" },
  { id:130, theme:'edu', freq:5, diff:4, done:false, q:"Il est normal que les jeunes travaillent pour financer leurs études. Qu'en pensez-vous ?" },
  { id:131, theme:'env', freq:5, diff:6, done:false, q:"La place accordée aux animaux de compagnie dans la société est trop importante. Qu'en pensez-vous ?" },
  { id:132, theme:'env', freq:5, diff:4, done:false, q:"L'écologie devrait être enseignée dès le plus jeune âge. Est-ce que vous êtes d'accord ?" },
  { id:133, theme:'env', freq:5, diff:2, done:false, q:"Pour être en bonne santé, il est préférable de vivre à la campagne plutôt qu'en ville. Êtes-vous d'accord ?" },
  { id:134, theme:'trav', freq:5, diff:5, done:false, q:"Les employeurs doivent donner la possibilité de suivre des formations tout au long de la vie. Est-ce utile pour chacun ? Qu'en pensez-vous ?" },
  { id:135, theme:'trav', freq:5, diff:5, done:false, q:"Pour évoluer dans son entreprise, il faut avant tout être compétent dans son travail. Partagez-vous cette opinion ?" },
  { id:136, theme:'edu', freq:5, diff:4, done:false, q:"Certains parents donnent de l'argent à leurs enfants pour leurs bons résultats scolaires. Qu'en pensez-vous ?" },
  { id:137, theme:'voy', freq:5, diff:4, done:false, q:"Peut-on connaître un pays seulement à travers des livres ? Pourquoi ?" },
  { id:138, theme:'sante', freq:5, diff:5, done:false, q:"Une entreprise doit donner la priorité au bien-être de ses employés pour bien fonctionner. Qu'en pensez-vous ?" },
  { id:139, theme:'imm', freq:5, diff:6, done:false, q:"Quand on vit à l'étranger, il est indispensable de rester dans la communauté de son pays d'origine. Qu'en pensez-vous ?" },
  { id:140, theme:'soc', freq:5, diff:4, done:false, q:"Il faut toujours dire la vérité aux enfants. Qu'en pensez-vous ?" },
  { id:141, theme:'imm', freq:5, diff:4, done:false, q:"Parler la langue du pays d'accueil suffit-il pour bien s'intégrer ? Pourquoi ?" },
  { id:142, theme:'edu', freq:5, diff:5, done:false, q:"Pour réussir sa vie, faut-il avoir fait de longues études ?" },
  { id:143, theme:'sante', freq:5, diff:5, done:false, q:"Consommer des produits bio est réservé aux personnes les plus riches. Êtes-vous d'accord ? Pourquoi ?" },
  { id:144, theme:'env', freq:5, diff:4, done:false, q:"Pour quelles raisons voudrait-on un animal de compagnie chez soi ?" },
  { id:145, theme:'edu', freq:4, diff:7, done:false, q:"Certains parents retirent leur enfant de l'école et font la classe à la maison. Qu'en pensez-vous ?" },
  { id:146, theme:'edu', freq:4, diff:5, done:false, q:"Quand on habite à l'étranger avec ses enfants, faut-il leur parler dans la langue maternelle ou dans la langue du pays d'accueil ? Pourquoi ?" },
  { id:147, theme:'tech', freq:4, diff:4, done:false, q:"Aujourd'hui, peut-on encore vivre sans Internet ? Qu'en pensez-vous ?" },
  { id:148, theme:'edu', freq:4, diff:4, done:false, q:"Il faut faire de longues études pour gagner beaucoup d'argent. Qu'en pensez-vous ?" },
  { id:149, theme:'trav', freq:4, diff:3, done:false, q:"Il faut gagner beaucoup d'argent pour pouvoir profiter de la vie. Êtes-vous d'accord avec cette affirmation ? Pourquoi ?" },
  { id:150, theme:'tech', freq:4, diff:3, done:false, q:"Parmi ces médias (journaux, radio, télévision, Internet, réseaux sociaux), lequel préférez-vous pour vous informer ? Expliquez votre choix." },
  { id:151, theme:'imm', freq:4, diff:4, done:false, q:"Pour bien vivre dans un pays étranger, il est indispensable de créer des relations avec les habitants du pays. Qu'en pensez-vous ?" },
  { id:152, theme:'fam', freq:4, diff:3, done:false, q:"À votre avis, quels sont les effets des jeux vidéo sur les enfants ? Pourquoi ?" },
  { id:153, theme:'imm', freq:4, diff:6, done:false, q:"S'expatrier en famille est plus simple que de partir seul(e). Êtes-vous d'accord avec cette idée ?" },
  { id:154, theme:'fam', freq:4, diff:4, done:false, q:"Deux personnes très différentes peuvent-elles être amies pour la vie ? Qu'en pensez-vous ?" },
  { id:155, theme:'tech', freq:4, diff:4, done:false, q:"Les outils numériques nous font gagner du temps dans la vie de tous les jours. Partagez-vous cet avis ? Expliquez." },
  { id:156, theme:'voy', freq:4, diff:4, done:false, q:"Pensez-vous qu'il faudrait davantage développer le tourisme dans votre pays ? Pourquoi ?" },
  { id:157, theme:'edu', freq:4, diff:3, done:false, q:"Les jeunes peuvent-ils apprendre facilement une langue étrangère ? Pourquoi ?" },
  { id:158, theme:'env', freq:4, diff:2, done:false, q:"Est-il vrai que vivre en ville est plus stressant que vivre à la campagne ? Qu'en pensez-vous ?" },
  { id:159, theme:'soc', freq:4, diff:5, done:false, q:"Certaines personnes choisissent de ne pas suivre la politique. Qu'en pensez-vous ?" },
  { id:160, theme:'fam', freq:4, diff:5, done:false, q:"D'après vous, la famille est-elle ce qu'il y a de plus important dans la vie ?" },
  { id:161, theme:'sport', freq:4, diff:3, done:false, q:"Il faut encourager les enfants à participer aux compétitions sportives. Êtes-vous d'accord avec cette affirmation ?" },
  { id:162, theme:'soc', freq:4, diff:5, done:false, q:"Que pensez-vous des habitudes de consommation dans les pays riches ?" },
  { id:163, theme:'imm', freq:4, diff:3, done:false, q:"S'intégrer dans un nouveau pays est plus facile si on a des enfants. Qu'en pensez-vous ?" },
  { id:164, theme:'val', freq:4, diff:5, done:false, q:"Les jeux du hasard, qu'en pensez-vous ?" },
  { id:165, theme:'fam', freq:4, diff:5, done:false, q:"Les amitiés sur Internet ont-elles une base aussi solide que les relations familiales ? Pourquoi ?" },
  { id:166, theme:'soc', freq:4, diff:5, done:false, q:"Pensez-vous que les célébrités ont leur place en politique ?" },
  { id:167, theme:'edu', freq:4, diff:5, done:false, q:"Quels sont les avantages d'apprendre une langue étrangère dès l'enfance ? Cette pratique facilite-t-elle l'intégration et l'évolution professionnelle à l'âge adulte ?" },
  { id:168, theme:'edu', freq:3, diff:3, done:false, q:"Il est indispensable de savoir parler anglais quand on voyage à l'étranger. Qu'en pensez-vous ?" },
  { id:169, theme:'voy', freq:3, diff:4, done:false, q:"Les programmes scolaires devraient donner plus de place aux activités artistiques (musique, théâtre, dessin, etc.)." },
  { id:170, theme:'edu', freq:3, diff:7, done:false, q:"La diversité au sein des écoles favorise-t-elle l'épanouissement de tous les élèves ? Êtes-vous d'accord avec cette affirmation ?" },
  { id:171, theme:'tech', freq:3, diff:4, done:false, q:"Est-il nécessaire de s'informer chaque jour pour mieux comprendre le monde ? Qu'en pensez-vous ?" },
  { id:172, theme:'tech', freq:3, diff:3, done:false, q:"Pensez-vous que les réseaux sociaux font perdre du temps ? Pourquoi ?" },
  { id:173, theme:'env', freq:3, diff:4, done:false, q:"Quelle est votre opinion sur le fait d'avoir un animal domestique chez soi ?" },
  { id:174, theme:'imm', freq:3, diff:3, done:false, q:"Selon vous, est-il plus facile de s'installer à l'étranger lorsqu'on est jeune ? Qu'en pensez-vous ?" },
  { id:175, theme:'imm', freq:3, diff:5, done:false, q:"Est-il facile de garder un lien avec sa culture d'origine quand on vit dans un autre pays ? Pourquoi ?" },
  { id:176, theme:'soc', freq:3, diff:5, done:false, q:"La gentillesse permet toujours d'être entendu et respecté. Êtes-vous d'accord avec cette affirmation ?" },
  { id:177, theme:'fam', freq:3, diff:3, done:false, q:"À votre avis, l'usage des téléphones portables devrait-il être interdit aux enfants ? Pourquoi ?" },
  { id:178, theme:'soc', freq:3, diff:6, done:false, q:"Regarder la télé permet de s'instruire. Qu'en pensez-vous ?" },
  { id:179, theme:'val', freq:3, diff:4, done:false, q:"L'argent fait-il le bonheur ? Qu'en pensez-vous ?" },
  { id:180, theme:'tech', freq:3, diff:3, done:false, q:"Les téléphones portables facilitent la communication. Êtes-vous d'accord avec cette affirmation ? Pourquoi ?" },
  { id:181, theme:'soc', freq:3, diff:4, done:false, q:"Qui doit aider les personnes en difficulté ? L'État ou les citoyens ? Qu'en pensez-vous ?" },
  { id:182, theme:'edu', freq:3, diff:3, done:false, q:"Travailler et étudier en même temps est difficile. Êtes-vous d'accord avec cette affirmation ?" },
  { id:183, theme:'tech', freq:3, diff:3, done:false, q:"À votre avis, faut-il interdire l'usage du téléphone portable à l'école ? Pourquoi ?" },
  { id:184, theme:'imm', freq:3, diff:6, done:false, q:"Est-ce que les bénéfices de vivre à l'étranger surpassent ses inconvénients ? Pourquoi ?" },
  { id:185, theme:'sante', freq:3, diff:4, done:false, q:"Pour rester en bonne santé, faut-il consommer uniquement des produits biologiques ? Êtes-vous d'accord ?" },
  { id:186, theme:'trav', freq:3, diff:4, done:false, q:"D'après vous, jusqu'à quel âge peut-on travailler ? Quelles en sont les raisons ?" },
  { id:187, theme:'trav', freq:3, diff:4, done:false, q:"Pour réussir dans la vie professionnelle, il faut être beau ou belle. Êtes-vous d'accord avec cette affirmation ?" },
  { id:188, theme:'tech', freq:3, diff:3, done:false, q:"Les nouvelles technologies ont un impact positif sur notre société. Qu'en pensez-vous ?" },
  { id:189, theme:'imm', freq:3, diff:5, done:false, q:"Il n'y a pas d'âge pour s'intégrer dans un pays d'accueil. Êtes-vous d'accord avec cette affirmation ?" },
  { id:190, theme:'voy', freq:3, diff:5, done:false, q:"Les métiers artistiques ne sont pas des métiers sérieux (cinéma, musique, peinture, etc.). Qu'en pensez-vous ?" },
  { id:191, theme:'fam', freq:3, diff:4, done:false, q:"Les personnes âgées donnent toujours de bons conseils. Qu'en pensez-vous ?" },
  { id:192, theme:'sante', freq:3, diff:4, done:false, q:"Pensez-vous que les gens cuisinent encore beaucoup aujourd'hui ? Pourquoi ?" },
  { id:193, theme:'tech', freq:3, diff:3, done:false, q:"Avez-vous confiance dans les informations que vous trouvez sur Internet ? Pourquoi ?" },
  { id:194, theme:'env', freq:3, diff:4, done:false, q:"Pour préserver l'environnement, il faut consommer des produits locaux et de saison. Êtes-vous d'accord avec cette idée ?" },
  { id:195, theme:'trav', freq:3, diff:5, done:false, q:"Quel métier aimeriez-vous tester un jour ? Expliquez votre choix." },
  { id:196, theme:'val', freq:3, diff:6, done:false, q:"Pensez-vous que les aides sociales réduisent la solidarité familiale ? Justifiez votre réponse." },
  { id:197, theme:'voy', freq:3, diff:2, done:false, q:"Beaucoup de personnes n'aiment pas voyager seules. Êtes-vous d'accord avec cette idée ? Pourquoi ?" },
  { id:198, theme:'env', freq:3, diff:7, done:false, q:"Selon vous, comment expliquer l'intérêt pour les déplacements en train, en avion ou en bus (selon la situation locale) ?" },
  { id:199, theme:'val', freq:3, diff:4, done:false, q:"Pour quelles raisons peut-on choisir de participer à une action humanitaire ?" },
  { id:200, theme:'trav', freq:3, diff:4, done:false, q:"Le plus important dans la vie, c'est d'être heureux au travail. Qu'en pensez-vous ?" },
  { id:201, theme:'sante', freq:3, diff:4, done:false, q:"Pour rester en bonne santé, est-ce que bien manger est l'élément le plus essentiel ? Qu'en pensez-vous ?" },
  { id:202, theme:'tech', freq:2, diff:5, done:false, q:"Les outils numériques comme les réseaux sociaux ou les applications nous rendent-ils moins actifs ? Qu'en pensez-vous ?" },
  { id:203, theme:'soc', freq:2, diff:6, done:false, q:"D'après vous, la place réservée aux personnes en situation de handicap dans la société est-elle suffisante ? Pourquoi ?" },
  { id:204, theme:'sante', freq:2, diff:4, done:false, q:"Peut-on faire confiance aux consultations médicales à distance ? Pourquoi ?" },
  { id:205, theme:'trav', freq:2, diff:5, done:false, q:"Certains métiers sont plus utiles que d'autres. Qu'en pensez-vous ?" },
  { id:206, theme:'soc', freq:2, diff:3, done:false, q:"Pensez-vous que les gens consomment trop d'objets, comme les vêtements ou les téléphones ? Pourquoi ?" },
  { id:207, theme:'edu', freq:2, diff:7, done:false, q:"La mixité sociale à l'école (enfants issus de milieux et de cultures différents) aide-t-elle à développer la tolérance ? Pourquoi ?" },
  { id:208, theme:'sante', freq:2, diff:4, done:false, q:"Selon vous, peut-on vraiment modifier ses habitudes alimentaires une fois adulte ? Pourquoi ?" },
  { id:209, theme:'imm', freq:2, diff:4, done:false, q:"Quitter son pays pour s'installer à l'étranger demande du courage. Êtes-vous d'accord ?" },
  { id:210, theme:'voy', freq:2, diff:4, done:false, q:"Explorer un pays, c'est aussi découvrir ses artistes. Partagez-vous cette opinion ?" },
  { id:211, theme:'sport', freq:2, diff:3, done:false, q:"Selon vous, est-ce une bonne idée de débuter un sport après 50 ans ?" },
  { id:212, theme:'edu', freq:2, diff:4, done:false, q:"L'école garantit-elle les mêmes opportunités à tous les élèves ? Qu'en pensez-vous ?" },
  { id:213, theme:'trav', freq:2, diff:5, done:false, q:"Tous les employeurs devraient-ils limiter le télétravail de leurs salariés ? Qu'en pensez-vous ?" },
  { id:214, theme:'env', freq:2, diff:4, done:false, q:"Il faut protéger tous les animaux en danger. Êtes-vous d'accord avec cette affirmation ? Pourquoi ?" },
  { id:215, theme:'soc', freq:2, diff:6, done:false, q:"Pensez-vous que les filles et les garçons devraient recevoir la même éducation ? Pourquoi ?" },
  { id:216, theme:'trav', freq:2, diff:6, done:false, q:"Au travail, faut-il toujours suivre les consignes de son supérieur ? Êtes-vous d'accord ?" },
  { id:217, theme:'edu', freq:2, diff:6, done:false, q:"Les sorties pédagogiques (musées, zoos, galeries) pour les enfants sont-elles bénéfiques ? Pourquoi ?" },
  { id:218, theme:'fam', freq:2, diff:6, done:false, q:"Les tâches ménagères ont-elles une importance dans notre quotidien ?" },
  { id:219, theme:'imm', freq:2, done:false, q:"Il est possible de vivre dans un pays sans en parler la langue. Qu'en pensez-vous ?" },
  { id:220, theme:'voy', freq:2, done:false, q:"Pour bien comprendre la culture d'un pays, il faut absolument parler la langue de ce pays. Qu'en pensez-vous ?" },
  { id:221, theme:'soc', freq:2, diff:3, done:false, q:"Aujourd'hui, les livres sont devenus inutiles. Êtes-vous d'accord avec cette affirmation ?" },
  { id:222, theme:'imm', freq:2, diff:3, done:false, q:"Il est plus facile de s'intégrer dans un nouveau pays quand on est jeune. Qu'en pensez-vous ?" },
  { id:223, theme:'imm', freq:2, diff:4, done:false, q:"Pour quelle(s) raison(s) voudrait-on étudier à l'étranger ?" },
  { id:224, theme:'tech', freq:2, diff:5, done:false, q:"Que pensez-vous de l'Internet en général ?" },
  { id:225, theme:'env', freq:2, diff:6, done:false, q:"Pour sauver l'environnement, les actions de chaque personne (tri, économie d'énergie, etc.) sont indispensables. Êtes-vous d'accord ?" },
  { id:226, theme:'tech', freq:2, diff:3, done:false, q:"Faut-il enseigner les nouvelles technologies (usage des réseaux sociaux, d'Internet, etc.) à l'école ? Pourquoi ?" },
  { id:227, theme:'tech', freq:2, diff:3, done:false, q:"Certaines personnes décident de ne jamais regarder la télévision. Qu'en pensez-vous ?" },
  { id:228, theme:'tech', freq:2, done:false, q:"Avec Internet, on vit mieux. Qu'en pensez-vous ?" },
  { id:229, theme:'sante', freq:2, diff:3, done:false, q:"De nombreuses personnes deviennent végétariennes. Que pensez-vous de ce choix alimentaire ?" },
  { id:230, theme:'trav', freq:2, diff:4, done:false, q:"Le salaire est-il l'élément le plus important dans un travail ? Êtes-vous d'accord ?" },
  { id:231, theme:'fam', freq:2, diff:4, done:false, q:"Les membres de la famille peuvent-ils être nos meilleurs amis ? Expliquez pourquoi." },
  { id:232, theme:'tech', freq:2, diff:4, done:false, q:"Que pensez-vous des informations diffusées par les médias sur Internet ? Les trouvez-vous intéressantes ou sans intérêt ? Pourquoi ?" },
  { id:233, theme:'imm', freq:2, diff:5, done:false, q:"Comment réussir à s'intégrer dans un nouvel environnement (pays, travail, études, etc.) ?" },
  { id:234, theme:'imm', freq:2, diff:7, done:false, q:"Pensez-vous que c'est au pays d'accueil de faire des efforts pour intégrer les immigrants ? Êtes-vous d'accord ?" },
  { id:235, theme:'voy', freq:2, diff:5, done:false, q:"Est-ce une bonne idée, selon vous, de partager un appartement avec d'autres personnes ? Pourquoi ?" },
  { id:236, theme:'imm', freq:2, diff:4, done:false, q:"Selon vous, pour quelle(s) raison(s) pourrait-on vouloir vivre à l'étranger ?" },
  { id:237, theme:'val', freq:2, diff:5, done:false, q:"Quel est le type d'action solidaire que vous aimeriez faire ?" },
  { id:238, theme:'trav', freq:2, diff:5, done:false, q:"Le travail des personnes âgées est-il une bonne chose pour la société ?" },
  { id:239, theme:'imm', freq:2, diff:5, done:false, q:"S'installer dans un autre pays signifie-t-il forcément adopter une nouvelle culture ? Qu'en pensez-vous ?" },
  { id:240, theme:'env', freq:2, diff:5, done:false, q:"Il est nécessaire de limiter la circulation des voitures en ville. Êtes-vous d'accord avec cette affirmation ?" },
  { id:241, theme:'voy', freq:2, diff:4, done:false, q:"Il y a trop de touristes dans une ville, c'est un problème pour les habitants. Qu'en pensez-vous ?" },
  { id:242, theme:'trav', freq:2, diff:3, done:false, q:"L'expérience est plus importante que les diplômes pour trouver un emploi. Êtes-vous d'accord avec cette affirmation ?" },
  { id:243, theme:'tech', freq:2, diff:4, done:false, q:"Que pensez-vous des émissions diffusées à la télévision ? Justifiez votre réponse." },
  { id:244, theme:'val', freq:2, diff:4, done:false, q:"Pour profiter de la vie, il faut travailler moins. Qu'en pensez-vous ?" },
  { id:245, theme:'soc', freq:2, diff:5, done:false, q:"Discutez de l'impact des caméras de surveillance en milieu public sur la sécurité et la vie privée." },
  { id:246, theme:'tech', freq:2, diff:6, done:false, q:"Le développement du télétravail est un progrès pour tous. Qu'en pensez-vous ?" },
  { id:247, theme:'soc', freq:2, diff:6, done:false, q:"Les célébrités devraient participer davantage à la vie publique. Que pensez-vous de cette affirmation ?" },
  { id:248, theme:'trav', freq:1, diff:8, done:false, q:"Choix de vêtements : débattez de l'importance du choix des vêtements dans un cadre professionnel, surtout en contexte de télétravail." },
  { id:249, theme:'fam', freq:1, diff:6, done:false, q:"De nos jours, les jeunes refusent de vieillir. Qu'en pensez-vous ?" },
  { id:250, theme:'edu', freq:1, diff:4, done:false, q:"De bons résultats scolaires garantissent-ils la réussite dans la vie ? Qu'en pensez-vous ?" },
  { id:251, theme:'env', freq:1, diff:5, done:false, q:"Économie d'eau et d'électricité : discutez des stratégies pour réduire la consommation d'eau et d'électricité dans un ménage, et des bénéfices environnementaux et économiques associés." },
  { id:252, theme:'voy', freq:1, diff:5, done:false, q:"Le voyage est une activité réservée aux personnes riches. Êtes-vous d'accord avec cette affirmation ?" },
  { id:253, theme:'env', freq:1, diff:4, done:false, q:"Est-il plus agréable de vivre en ville ou à la campagne ?" },
  { id:254, theme:'env', freq:1, diff:5, done:false, q:"Selon vous, faut-il protéger toutes les espèces animales menacées ? Pourquoi ?" },
  { id:255, theme:'edu', freq:1, diff:4, done:false, q:"Pensez-vous que lire soit une perte de temps ? Pourquoi ?" },
  { id:256, theme:'tech', freq:1, diff:5, done:false, q:"Pourquoi doit-on éviter de partager sa vie privée sur les réseaux sociaux ?" },
  { id:257, theme:'trav', freq:1, diff:6, done:false, q:"Le métier d'enseignant peut faire peur. Comment expliquez-vous cela ?" },
  { id:258, theme:'fam', freq:1, diff:5, done:false, q:"Les animaux peuvent-ils rendre l'être humain heureux ? Pourquoi ?" },
  { id:259, theme:'trav', freq:1, diff:4, done:false, q:"Selon vous, comment un jeune doit-il faire pour trouver du travail ?" },
  { id:260, theme:'tech', freq:1, done:false, q:"Les jeux vidéo entraînent des comportements violents. Qu'en pensez-vous ?" },
  { id:261, theme:'trav', freq:1, done:false, q:"Est-ce que vous préférez travailler dans des équipes féminines ou masculines ? Pourquoi ?" },
  { id:262, theme:'fam', freq:1, done:false, q:"Aujourd'hui, beaucoup de gens souffrent de solitude. Pourquoi ?" },
  { id:263, theme:'env', freq:1, done:false, q:"Au quotidien, il est facile de faire des choses pour respecter l'environnement. Êtes-vous d'accord avec cette affirmation ?" },
  { id:264, theme:'tech', freq:1, done:false, q:"Est-ce qu'il est important de prendre des photos de chaque moment important de votre vie ? Pourquoi ?" },
  { id:265, theme:'tech', freq:1, done:false, q:"La diffusion de films, de musique, d'expositions sur Internet favorise-t-elle l'accès à la culture pour tous ? Qu'en pensez-vous ?" },
  { id:266, theme:'fam', freq:1, done:false, q:"Le plus important dans la vie, ce sont les amis. Qu'en pensez-vous ?" },
  { id:267, theme:'env', freq:1, done:false, q:"Pour protéger la planète, il faut arrêter de voyager. Qu'en pensez-vous ?" },
  { id:268, theme:'imm', freq:1, done:false, q:"Les enfants s'intègrent facilement dans un pays étranger. Qu'en pensez-vous ?" },
  { id:269, theme:'voy', freq:1, done:false, q:"Le tourisme représente-t-il une voie de développement intéressante pour tous les pays ? Pourquoi ?" },
  { id:270, theme:'tech', freq:1, diff:6, done:false, q:"Aujourd'hui, grâce à Internet, on peut avoir des relations amicales ou familiales à distance aussi fortes que lorsque l'on se rencontre souvent. Êtes-vous d'accord ?" },
  { id:271, theme:'fam', freq:1, diff:6, done:false, q:"Les jeunes générations apprennent les langues étrangères beaucoup plus facilement que leurs aînés. Qu'en pensez-vous ?" },
  { id:272, theme:'soc', freq:1, diff:4, done:false, q:"Selon vous, pourquoi certaines personnes s'intéressent-elles peu à la politique ?" },
  { id:273, theme:'imm', freq:1, diff:4, done:false, q:"À votre avis, au cours d'une carrière professionnelle, est-il nécessaire d'avoir une expérience à l'étranger ? Pourquoi ?" },
  { id:274, theme:'soc', freq:1, diff:4, done:false, q:"Certaines personnes refusent aujourd'hui d'avoir un téléphone portable. Que pensez-vous de ce choix ?" },
  { id:275, theme:'soc', freq:1, diff:5, done:false, q:"Les jeux de hasard et d'argent devraient être interdits. Êtes-vous d'accord ?" },
  { id:276, theme:'env', freq:1, diff:4, done:false, q:"À votre avis, est-ce que posséder un animal de compagnie est une bonne idée pour une personne âgée ?" },
  { id:277, theme:'imm', freq:1, diff:4, done:false, q:"Immigrer seul(e) ou en famille, qu'en pensez-vous ?" },
  { id:278, theme:'imm', freq:1, diff:4, done:false, q:"D'après vous, quelles sont les raisons qui peuvent pousser quelqu'un à travailler à l'étranger ?" },
  { id:279, theme:'soc', freq:1, diff:6, done:false, q:"Beaucoup de personnes achètent des produits d'occasion (vêtements, meubles, voitures, etc.). Pensez-vous que c'est une bonne idée ? Pourquoi ?" },
  { id:280, theme:'env', freq:1, diff:4, done:false, q:"Beaucoup d'habitants des grandes villes s'installent à la campagne pour vivre sans stress. Qu'en pensez-vous ?" },
  { id:281, theme:'soc', freq:1, diff:5, done:false, q:"Faut-il laisser beaucoup de liberté aux adolescents ou, au contraire, leur poser de nombreuses limites ? Qu'en pensez-vous ?" },
  { id:282, theme:'soc', freq:1, diff:5, done:false, q:"Grandir avec des frères et sœurs comporte beaucoup d'avantages. Qu'en pensez-vous ?" },
  { id:283, theme:'soc', freq:1, diff:4, done:false, q:"La publicité est-elle utile ? Pourquoi ?" },
  { id:284, theme:'tech', freq:1, diff:4, done:false, q:"Certaines personnes préfèrent vivre sans technologie (Internet, ordinateur, téléphone). Qu'en pensez-vous ?" },
  { id:285, theme:'fam', freq:1, diff:3, done:false, q:"Il faut obliger les enfants à faire du sport. Êtes-vous d'accord ? Pourquoi ?" },
  { id:286, theme:'tech', freq:1, diff:4, done:false, q:"L'Internet rend les gens solitaires. Que pensez-vous de cette affirmation ?" },
  { id:287, theme:'fam', freq:1, done:false, q:"Les parents doivent-ils laisser leurs enfants utiliser les réseaux sociaux ? Qu'en pensez-vous ?" },
  { id:288, theme:'trav', freq:1, done:false, q:"Tout le monde devrait avoir la possibilité de travailler à distance. Qu'en pensez-vous ?" },
  { id:289, theme:'trav', freq:1, done:false, q:"Les entreprises créent toujours de nouveaux produits. Qu'en pensez-vous ?" },
  { id:290, theme:'trav', freq:1, done:false, q:"Pour quelles raisons préférerait-on travailler de chez soi ?" },
  { id:291, theme:'trav', freq:1, done:false, q:"Avec l'augmentation des ventes en ligne, les magasins (boutiques, centres commerciaux, etc.) vont disparaître. Qu'en pensez-vous ?" },
  { id:292, theme:'val', freq:1, done:false, q:"Est-ce que vous pensez que les jeunes sont moins engagés aujourd'hui (environnement, politique, santé, etc.) ? Pourquoi ?" },
  { id:293, theme:'trav', freq:1, done:false, q:"Faut-il rendre le télétravail obligatoire pour tous ceux qui peuvent exercer leur métier à distance ? Expliquez pourquoi." },
  { id:294, theme:'imm', freq:1, done:false, q:"Tous les jeunes devraient partir vivre à l'étranger pendant au moins 6 mois pour apprendre à se débrouiller. Qu'en pensez-vous ?" },
  { id:295, theme:'edu', freq:1, done:false, q:"Les sorties scolaires sont aussi importantes que les matières enseignées à l'école. Êtes-vous d'accord avec cette affirmation ? Pourquoi ?" },
  { id:296, theme:'imm', freq:1, done:false, q:"À votre avis, qu'est-ce que la vie à l'étranger apporte aux immigrés ?" },
  { id:297, theme:'imm', freq:1, done:false, q:"À votre avis, pour quelle(s) raison(s) peut-on revenir vivre dans son pays après des années d'absence ?" },
  { id:298, theme:'val', freq:1, diff:7, done:false, q:"Selon vous, Internet joue-t-il un rôle en matière de solidarité (catastrophe naturelle ou événements d'actualité) ?" },
  { id:299, theme:'tech', freq:1, diff:4, done:false, q:"Que pensez-vous de l'utilité des réseaux sociaux à l'heure actuelle ?" },
  { id:300, theme:'fam', freq:1, diff:3, done:false, q:"Est-ce facile de vivre loin de sa famille ? Qu'en pensez-vous ?" },
  { id:301, theme:'tech', freq:1, diff:6, done:false, q:"Les téléphones portables permettent-ils d'avoir la bonne information ? Êtes-vous d'accord ?" },
  { id:302, theme:'trav', freq:1, diff:6, done:false, q:"L'importance du travail dans la vie." },
  { id:303, theme:'sante', freq:1, diff:5, done:false, q:"Pour être en bonne santé, il faut arrêter de manger de la viande. Que pensez-vous de cette affirmation ?" },
  { id:304, theme:'edu', freq:1, diff:6, done:false, q:"Les universités doivent être accessibles à tous sans sélection. Êtes-vous d'accord avec cette affirmation ?" },
  { id:305, theme:'tech', freq:1, diff:4, done:false, q:"Le temps passé devant la télévision est du temps perdu. Êtes-vous d'accord avec cette affirmation ?" },
  { id:306, theme:'tech', freq:1, diff:4, done:false, q:"Pour quelle(s) raison(s) acceptons-nous de montrer notre vie privée sur les réseaux sociaux (Facebook, Twitter, etc.) ?" },
  { id:307, theme:'sante', freq:1, diff:6, done:false, q:"On ne peut pas lutter contre le stress. Qu'en pensez-vous ?" },
  { id:308, theme:'trav', freq:1, done:false, q:"Pensez-vous qu'il faut aimer son métier pour être plus productif ?" },
  { id:309, theme:'soc', freq:1, done:false, q:"C'est le rôle de l'État de financer les dépenses de santé des citoyens. Êtes-vous d'accord avec cette affirmation ? Pourquoi ?" },
];
