// ═══════════════════════════════════════════════════════════════
//  COUVERTURE GRAMMATICALE B2
//  Le but n'est pas d'entasser toutes les structures dans un texte —
//  ce serait exactement le défaut qu'on cherche à éviter — mais de
//  couvrir l'inventaire sur l'ENSEMBLE du corpus, chaque structure
//  apparaissant là où l'argument la demande vraiment.
// ═══════════════════════════════════════════════════════════════

const B2_STRUCTURES = [
  { id:"subj_cond", fr:"à condition que + subjonctif", fa:"به شرط آنکه + التزامی", re:"à condition qu[e’']" },
  { id:"subj_bien", fr:"bien que / quoique + subjonctif", fa:"هرچند + التزامی", re:"\\b(bien qu[e’']|quoiqu[e’'])" },
  { id:"subj_pour", fr:"pour que / afin que + subjonctif", fa:"تا اینکه + التزامی", re:"\\b(pour qu[e’']|afin qu[e’'])" },
  { id:"subj_sans", fr:"sans que + subjonctif", fa:"بدون آنکه + التزامی", re:"\\bsans qu[e’']" },
  { id:"subj_avant", fr:"avant que + subjonctif", fa:"پیش از آنکه + التزامی", re:"\\bavant qu[e’']" },
  { id:"subj_opin", fr:"subjonctif après opinion négative / doute", fa:"التزامی پس از شک یا نفیِ نظر", re:"\\b(je ne (pense|crois) pas qu[e’']|il n[e’']est pas (sûr|certain) qu[e’']|il se peut qu[e’']|il est possible qu[e’'])" },
  { id:"subj_veiller", fr:"veiller à ce que / faire en sorte que + subjonctif", fa:"مراقب بودن که + التزامی", re:"\\b(veiller à ce qu[e’']|faire en sorte qu[e’'])" },
  { id:"subj_neces", fr:"il faut que / il est nécessaire que + subjonctif", fa:"لازم است که + التزامی", re:"\\b(il faut qu[e’']|il est (nécessaire|important|essentiel) qu[e’'])" },
  { id:"hyp1", fr:"si + présent, + futur", fa:"اگر + حال، آینده", re:"\\bsi (on|l[e’']|tu |vous |nous |je |[a-zéèêà]+ )[^,.;:]{0,70}, [^.;:]{0,80}\\b[a-zéèêàçûôî]+(ra|ras|rez|rons|ront|rai)\\b" },
  { id:"hyp2", fr:"si + imparfait, + conditionnel présent", fa:"اگر + ماضی استمراری، شرطی", re:"\\bsi [^,.;:]{2,70}(ait|aient|issait|issaient)\\b[^,.;:]{0,40}, [^.;:]{0,80}\\b\\w*(rait|raient|rais)\\b" },
  { id:"hyp3", fr:"si + plus-que-parfait, + conditionnel passé", fa:"اگر + بعید، شرطی گذشته", re:"\\bsi [^,.;:]{0,60}\\b(avait|avaient|était|étaient)\\b [^,.;:]{0,50}(é|és|ée|ées|is|it)\\b[^.;:]{0,80}\\baurai(t|ent)\\b" },
  { id:"gerondif", fr:"gérondif (en + participe présent)", fa:"وجه مصدری با en", re:"\\ben (?!plus|effet|revanche|somme|définitive|réalité|particulier|tout|général|matière|France|quoi|ce )[a-zéèêàçûôî]+ant\\b" },
  { id:"toutenpp", fr:"tout en + participe présent (concession)", fa:"tout en + وجه وصفی", re:"\\btout en [a-zéèêàçûôî]+ant\\b" },
  { id:"ppresent", fr:"participe présent / proposition participiale", fa:"وجه وصفی", re:"(^|[.!?] )[A-ZÉÈÀ][a-zéèêàçûôî]+ant\\b" },
  { id:"infpasse", fr:"infinitif passé (après avoir / après être)", fa:"مصدر گذشته", re:"\\baprès (avoir|être) [a-zéèêàçûôî]+" },
  { id:"rel_dont", fr:"relative avec dont", fa:"موصولی با dont", re:"\\bdont\\b" },
  { id:"rel_ou", fr:"relative avec où", fa:"موصولی با où", re:"(^|[^a-zA-Zàâçéèêëîïôûùüÿœ])où([^a-zA-Zàâçéèêëîïôûùüÿœ]|$)" },
  { id:"rel_lequel", fr:"relative avec lequel / auquel / duquel", fa:"موصولی با lequel", re:"\\b(lesquel(le)?s?|laquelle|lequel|auxquel(le)?s|auquel|duquel|desquel(le)?s)\\b" },
  { id:"cequi", fr:"ce qui / ce que / ce dont", fa:"ce qui / ce que", re:"\\bce (qui|qu[e’']|dont)\\b" },
  { id:"relief", fr:"mise en relief (ce n'est pas X, c'est Y / c'est … qui)", fa:"برجسته‌سازی", re:"(ce n[e’']est pas .{2,60}[:,—-] c[e’']est|c[e’']est .{2,50} qu[ie]\\b)" },
  { id:"passif", fr:"voix passive", fa:"مجهول", re:"\\b(est|sont|était|étaient|sera|seront|soit|soient) (souvent |parfois |toujours |largement |également |aussi |bien |très |de plus en plus )?[a-zéèêàçûôî]+(é|és|ée|ées)\\b" },
  { id:"nominal", fr:"nominalisation", fa:"اسم‌سازی", re:"\\b(l[ae’]|les|une|un|du|des) (suppression|augmentation|réduction|diminution|amélioration|acceptation|intégration|adaptation|construction|croissance|progression|transmission|reconnaissance|utilisation|apprentissage|développement|obligation|contrainte|maîtrise|gestion|pratique)\\b" },
  { id:"comparatif", fr:"comparatif / superlatif", fa:"تفضیلی و عالی", re:"\\b(plus .{1,25} que|moins .{1,25} que|aussi .{1,25} que|le plus\\b|la plus\\b|les plus\\b|meilleur|mieux que|davantage que)\\b" },
  { id:"impersonnel", fr:"tournure impersonnelle", fa:"ساخت غیرشخصی", re:"\\b(il est (légitime|difficile|possible|nécessaire|important|essentiel|clair|vrai)|il convient de|il s[e’']agit de|il existe|il revient à|il incombe à|il suffit de)\\b" },
  { id:"cause", fr:"expression de la cause", fa:"بیان علت", re:"\\b(parce qu[e’']|car|puisqu[e’']|étant donné qu[e’']|du fait qu[e’']|grâce à|en raison de|faute de|à cause de)\\b" },
  { id:"consequence", fr:"expression de la conséquence", fa:"بیان نتیجه", re:"\\b(par conséquent|c[e’']est pourquoi|si bien qu[e’']|de sorte qu[e’']|dès lors|d[e’']où|au point de)\\b" },
  { id:"but", fr:"expression du but", fa:"بیان هدف", re:"\\b(afin de|dans le but de|de manière à|de façon à|en vue de|pour que|afin que)\\b" },
  { id:"opposition", fr:"expression de l'opposition", fa:"بیان تقابل", re:"\\b(en revanche|au contraire|alors qu[e’']|tandis qu[e’']|contrairement à|à l[e’']inverse|or\\b)\\b" },
  { id:"concession", fr:"expression de la concession", fa:"بیان اذعان", re:"\\b(cela dit|néanmoins|toutefois|pourtant|malgré|certes|même si|il n[e’']en reste pas moins)\\b" },
  { id:"condition", fr:"expression de la condition", fa:"بیان شرط", re:"(à condition|pourvu qu[e’']|dans la mesure où|sauf si|à moins qu[e’']|en cas de)" },
  { id:"restriction", fr:"restriction : ne … que", fa:"محدودسازی ne … que", re:"\\bne .{1,40}\\bqu[e’']\\b" },
  { id:"discours", fr:"discours indirect", fa:"نقل قول غیرمستقیم", re:"\\b(ils? (disent|estiment|considèrent|rappellent|affirment|soutiennent) qu[e’']|on (dit|estime|considère) qu[e’'])" },
  { id:"futur_ant", fr:"futur / futur antérieur", fa:"آینده", re:"\\b[a-zéèêàçûôî]+(ra|ront|rez|rons|rai)\\b" },
  { id:"cond_pol", fr:"conditionnel (souhait, atténuation)", fa:"شرطی برای تلطیف", re:"\\b(devrai(t|ent)|pourrai(t|ent)|serai(t|ent)|aurai(t|ent)|faudrait|vaudrait|il serait)\\b" },
];

const B2_CORPUS = [
  { id:1, src:"fiche", theme:"culture", q:"Les loisirs culturels (musées, théâtres, etc.) devraient être gratuits. Qu'en pensez-vous ?", paras:[
    { label:"INTRODUCTION", p:"L'accès à la culture soulève aujourd'hui de nombreux débats. Certains estiment que les musées et les théâtres devraient être entièrement gratuits, d'autres pensent que cela n'est pas réaliste. Personnellement, je suis d'avis que la gratuité représente un véritable atout, à condition qu'elle soit bien organisée. Je vais expliquer les raisons pour lesquelles je défends cette position." },
    { label:"ARGUMENT 1 — l'accès", p:"En premier lieu, la gratuité favorise l'accès à la culture pour tous. En effet, le prix d'entrée constitue souvent un obstacle pour les familles modestes. Cela s'explique notamment par le coût élevé des billets dans les grandes villes. Par exemple, une famille de quatre personnes doit parfois payer une somme importante pour une seule visite. Par conséquent, la gratuité permettrait de réduire les inégalités entre les citoyens." },
    { label:"ARGUMENT 2 — la formation du citoyen", p:"Il convient également de souligner que la culture joue un rôle essentiel dans la formation des citoyens. Fréquenter un musée ou une pièce de théâtre contribue à développer l'esprit critique et à renforcer la cohésion sociale. Un enfant qui découvre une exposition n'apprend pas seulement des dates : il apprend à observer, à comparer, à se poser des questions. La gratuité ne représente donc pas une dépense, mais un investissement à long terme." },
    { label:"ARGUMENT 3 — l'effet réel", p:"Un autre aspect mérite d'être pris en considération : la gratuité a un impact direct sur la fréquentation. Quand le prix disparaît, les publics changent, et notamment les jeunes. Par exemple, les journées gratuites organisées dans certains musées attirent un public beaucoup plus large et beaucoup plus varié. Cela montre que la barrière n'est pas le manque d'intérêt, mais bien le prix." },
    { label:"CONTRE-ARGUMENT", p:"Cela dit, il ne faut pas perdre de vue que les institutions culturelles font face à de fortes contraintes budgétaires. Si les recettes disparaissent, la qualité risque de se dégrader. Il convient donc de nuancer ce point : une gratuité totale et sans compensation serait difficile à mettre en place." },
    { label:"CONCLUSION", p:"Pour conclure, je reste convaincu que la gratuité constitue une mesure bénéfique, à condition que l'État prenne en charge la différence. Il serait donc souhaitable de mettre en place une gratuité ciblée, pour les jeunes, les étudiants et les personnes en difficulté, plutôt qu'une gratuité générale." },
  ]},
  { id:2, src:"fiche", theme:"fam", q:"Pensez-vous que l'autorité soit indispensable dans l'éducation d'un enfant ? Pourquoi ?", paras:[
    { label:"INTRODUCTION", p:"Avec l'essor des méthodes éducatives modernes, les modèles traditionnels sont de plus en plus remis en cause, et la question de l'autorité suscite de nombreux débats. Il est donc légitime de se demander si l'autorité est vraiment indispensable pour bien élever un enfant. Certains soutiennent le contraire, et je comprends leur point de vue. Pourtant, je suis convaincu que l'autorité reste essentielle, à condition qu'elle soit juste et bienveillante. Et cela pour trois raisons : elle donne à l'enfant des limites claires, elle le prépare à la vie en société, et elle ne doit jamais se confondre avec la sévérité. Je vais expliquer pourquoi." },
    { label:"ARGUMENT 1 — connaître ses limites", p:"D'emblée, je suis d'avis que l'autorité permet à l'enfant de connaître ses limites. En effet, les enfants cherchent naturellement à tester leur environnement, et sans règles claires, ils se sentent vite perdus. Par exemple, un cadre bien défini à la maison et à l'école les aide à comprendre ce qui est acceptable et ce qui ne l'est pas. Il revient donc aux parents de faire en sorte que les règles soient cohérentes et expliquées. Ce qui compte avant tout, ce n'est pas la règle elle-même : c'est la stabilité du cadre. Parce que c'est cette stabilité qui rassure l'enfant et qui favorise son développement." },
    { label:"ARGUMENT 2 — préparer à la vie en société", p:"En deuxième lieu, j'estime que l'autorité contribue à préparer l'enfant à la vie en société. Cela s'explique simplement : apprendre à respecter les règles familiales l'aide plus tard à respecter les règles sociales. Par exemple, un enfant habitué à un cadre s'intègre plus facilement à l'école, puis dans la vie professionnelle. En grandissant dans un environnement structuré, il développe le sens de la responsabilité. Et tout en étant encadré, il apprend à faire la différence entre la liberté et le laisser-aller." },
    { label:"ARGUMENT 3 — autorité n'est pas sévérité", p:"Un dernier point mérite d'être pris en considération : l'autorité ne doit surtout pas devenir synonyme de sévérité excessive. À titre d'exemple, une discipline trop rigide peut engendrer de la peur, ou au contraire de la rébellion. Malgré la nécessité des règles, celles-ci doivent toujours s'accompagner d'écoute et de dialogue. Quand on élève un enfant uniquement avec des punitions, on détruit peu à peu sa confiance en lui. Là encore, ce qui compte, c'est l'équilibre entre la fermeté et l'écoute." },
    { label:"CONTRE-ARGUMENT — ce que disent les autres", p:"Cela dit, je comprends ceux qui pensent le contraire. Ils estiment qu'un enfant se construit mieux dans la liberté, et que toute autorité finit par étouffer sa personnalité. Leur argument n'est pas sans fondement : beaucoup d'adultes associent encore autorité et rigueur absolue, et ce modèle se transmet souvent de génération en génération. Mais confondre l'autorité et la brutalité, c'est justement l'erreur que je dénonce. Poser un cadre, ce n'est pas priver un enfant de liberté : c'est lui apprendre à s'en servir." },
    { label:"CONCLUSION", p:"Pour conclure, les bienfaits d'une autorité bien mesurée l'emportent largement sur les risques d'une absence totale de cadre. Bien qu'elle soit parfois difficile à exercer, elle reste nécessaire au bon développement de l'enfant. À condition qu'elle soit juste et expliquée, elle favorise son équilibre. Au fond, il vaut mieux guider avec fermeté que laisser faire sans repères. Et l'enfant qui a connu des limites claires est souvent celui qui, plus tard, saura le mieux poser les siennes." },
  ]},
  { id:3, src:"fiche", theme:"sport", q:"Pensez-vous qu'il faut obliger les enfants à pratiquer une activité sportive ? Pourquoi ?", paras:[
    { label:"INTRODUCTION", p:"Avec la sédentarité qui progresse chez les jeunes et le temps passé devant les écrans, la question de l'activité physique des enfants suscite de nombreux débats. Il est donc légitime de se demander s'il faut aller jusqu'à les y obliger. Certains soutiennent que oui, et je comprends parfaitement leur inquiétude : les chiffres de l'inactivité sont réels. Pourtant, je suis convaincu qu'il faut encourager fermement sans jamais contraindre. Et cela pour trois raisons : le sport est réellement nécessaire, l'obligation détruit l'envie, et c'est le choix de l'enfant qui rend la pratique durable. Je vais expliquer pourquoi." },
    { label:"ARGUMENT 1 — le sport est nécessaire", p:"D'emblée, je suis d'avis que le sport est indispensable au développement de l'enfant. En effet, une activité régulière renforce le cœur et les muscles, mais ses effets vont bien plus loin. Par exemple, un enfant actif dort mieux, se concentre plus longtemps à l'école et apprend plus facilement. Et dans les sports collectifs, il apprend aussi la coopération, le respect des règles et la gestion de ses émotions. Sur ce point, ceux qui s'inquiètent de l'inactivité ont entièrement raison, et il serait malhonnête de le nier." },
    { label:"ARGUMENT 2 — l'obligation ruine l'envie", p:"En deuxième lieu, j'estime que l'obligation produit souvent l'effet inverse de celui qu'on recherche. Cela s'explique simplement : un enfant contraint associe très vite l'activité physique à une corvée, et il abandonne dès qu'il le peut. Par exemple, beaucoup d'adultes qui ont été forcés au judo ou à la natation n'ont plus jamais refait de sport ensuite. Ce qui compte avant tout, ce n'est pas le nombre d'heures imposées : c'est le plaisir ressenti pendant l'effort. Parce que sans ce plaisir, aucune pratique ne s'installe durablement." },
    { label:"ARGUMENT 3 — c'est le choix qui dure", p:"Un dernier point mérite d'être pris en considération : c'est le choix qui rend la pratique durable. Il revient donc aux parents de faire découvrir plusieurs sports, le tennis, la danse, l'escalade ou le football, pour que l'enfant trouve celui qui lui convient. En respectant ses goûts, on renforce aussi sa confiance en lui. Et un enfant qui a choisi son sport garde souvent, à l'âge adulte, un rapport plus sain à son corps. Tout en l'encadrant, on laisse ainsi naître une motivation qui lui appartient." },
    { label:"CONTRE-ARGUMENT — ce que disent les autres", p:"Cela dit, je comprends ceux qui défendent une position plus ferme. Ils rappellent qu'un enfant laissé entièrement libre choisit presque toujours l'écran, et que la société offre de moins en moins d'occasions de bouger naturellement. Leur argument n'est pas sans fondement, et je ne vais pas prétendre le contraire. Mais encadrer n'est pas obliger : proposer tous les jours, c'est déjà une forme de fermeté. Et la responsabilité ne repose pas seulement sur les familles : si l'école consacrait plus de temps à l'activité physique quotidienne, la question se poserait beaucoup moins." },
    { label:"CONCLUSION", p:"Pour conclure, la liberté d'adhésion l'emporte largement sur la contrainte imposée. Bien qu'une certaine fermeté soit parfois nécessaire, la pression doit rester mesurée et bienveillante. À condition que le plaisir guide, le sport devient un compagnon pour la vie. Au fond, mieux vaut susciter l'envie que forcer sans conviction. Et l'enfant qui a aimé bouger est souvent celui qui, adulte, n'aura pas besoin qu'on l'y pousse." },
  ]},
  { id:8, src:"texte", theme:"edu", q:"Apprendre la langue du pays où l'on vit est essentiel pour s'intégrer. Êtes-vous d'accord ? Pourquoi ?", qFa:"زبانِ کشوری که در آن زندگی می‌کنی برای ادغام ضروری است. موافقی؟ چرا؟", paras:[
    { label:"INTRODUCTION", p:"Avec la mobilité qui s'accélère et le nombre de personnes qui s'installent chaque année dans un pays qu'elles ne connaissent pas, la question de la langue revient sans cesse. Il est légitime de se demander si l'apprendre est vraiment la condition de l'intégration. Certains estiment qu'on peut très bien vivre ailleurs sans parler la langue du pays, et je comprends d'où vient cette idée. Pourtant, je suis convaincu que la langue reste indispensable, même si elle ne suffit pas à elle seule. Et cela pour trois raisons : elle ouvre l'accès au travail, elle donne accès à la vie sociale, et elle change le regard que les autres portent sur vous." },
    { label:"ARGUMENT 1", p:"D'emblée, il faut qu'on soit clair sur un point : sans la langue, l'accès à l'emploi reste très limité. En effet, la plupart des postes exigent aujourd'hui un minimum d'échange avec des collègues et des clients. Par exemple, un ingénieur très qualifié dont le diplôme est reconnu peut malgré tout se retrouver bloqué s'il ne parvient pas à expliquer son travail. Si l'on maîtrise la langue, on accédera à des postes qui correspondent réellement à ses compétences. Il est donc essentiel que cet apprentissage commence le plus tôt possible." },
    { label:"ARGUMENT 2", p:"En deuxième lieu, j'estime que la langue conditionne toute la vie sociale. Cela s'explique simplement : on ne noue de véritables liens qu'à partir du moment où l'on peut plaisanter, hésiter, se tromper devant quelqu'un. Ainsi, dans un quartier où les habitants se parlent tous les jours, celui qui ne comprend rien reste à l'écart sans que personne ne l'ait voulu. Après avoir vécu quelques mois dans cette situation, beaucoup finissent par se replier sur leur propre communauté. Ce qui compte, ce n'est pas le vocabulaire accumulé : c'est la capacité à entrer dans une conversation." },
    { label:"ARGUMENT 3", p:"Un dernier point mérite d'être pris en considération : la langue change le regard des autres. À titre d'exemple, un étranger qui fait l'effort de parler, même mal, est presque toujours mieux accueilli. Il ne s'agit pas de perfection, mais d'effort visible. Et cet effort est perçu comme une marque de respect, avant même que le premier mot correct ne soit prononcé." },
    { label:"CONTRE-ARGUMENT", p:"Cela dit, je ne pense pas que la langue règle tout. Ceux qui défendent la position inverse rappellent qu'on peut parler parfaitement et rester malgré tout un étranger, faute de réseau ou de reconnaissance professionnelle. Leur argument tient debout. Si les institutions avaient davantage accompagné les nouveaux arrivants dès les premières années, la question ne se poserait pas dans ces termes. Mais la langue reste la première porte : elle ne garantit rien, et pourtant sans elle rien ne commence." },
    { label:"CONCLUSION", p:"Pour conclure, l'apprentissage de la langue l'emporte largement sur tous les autres efforts d'intégration. Bien qu'il soit long et parfois décourageant, il conditionne le reste. À condition qu'on l'aborde comme un outil et non comme un examen, il devient rapidement une seconde nature. Au fond, mieux vaut parler imparfaitement que se taire correctement." },
  ]},
  { id:9, src:"texte", theme:"env", q:"La voiture est indispensable dans notre vie. Êtes-vous d'accord avec cette affirmation ?", qFa:"ماشین در زندگی ما ضروری است. با این حرف موافقی؟", paras:[
    { label:"INTRODUCTION", p:"Avec l'étalement des villes et l'allongement des trajets quotidiens, la place de la voiture dans nos vies suscite de nombreux débats. Il est légitime de se demander si elle est réellement devenue indispensable. Certains le pensent sans hésiter, d'autres y voient une habitude dont nous pourrions nous défaire. Pour ma part, je dirais qu'elle est indispensable pour certains et parfaitement évitable pour d'autres, et que tout dépend de l'endroit où l'on vit. Et cela pour trois raisons." },
    { label:"ARGUMENT 1", p:"D'emblée, il convient de rappeler que la voiture reste vitale hors des grandes villes. En effet, dans une commune rurale où le bus passe deux fois par jour, s'en passer relève de l'exploit. Par exemple, une infirmière qui visite des patients à domicile ne pourrait pas exercer son métier sans véhicule. Si l'on supprimait la voiture demain, ces territoires seraient les premiers pénalisés. Il faut donc que toute réflexion sur ce sujet parte de cette réalité-là." },
    { label:"ARGUMENT 2", p:"En deuxième lieu, j'estime qu'en ville la situation est exactement inverse. Cela s'explique aisément : les transports en commun y sont denses, et le temps perdu dans les embouteillages dépasse souvent celui d'un trajet en métro. Ainsi, de plus en plus d'habitants renoncent à leur véhicule sans que leur quotidien en souffre. Après avoir essayé le vélo pendant quelques mois, beaucoup ne reviennent jamais à la voiture. Ce qui compte, ce n'est donc pas la voiture en elle-même : c'est l'offre de transport disponible autour de soi." },
    { label:"ARGUMENT 3", p:"Un dernier élément mérite d'être pris en considération : le coût réel. À titre d'exemple, entre l'assurance, le carburant et l'entretien, un ménage modeste consacre à son véhicule une part de budget considérable. Cette dépense est rarement calculée, et pourtant elle pèse lourd. Il ne s'agit pas de culpabiliser les automobilistes, mais de regarder les chiffres." },
    { label:"CONTRE-ARGUMENT", p:"Cela dit, je ne crois pas que la voiture disparaisse un jour. Ceux qui défendent la position inverse rappellent qu'elle reste le seul moyen de transport totalement libre, celui grâce auquel on part quand on veut, où l'on veut. Leur argument n'est pas sans fondement. Si les pouvoirs publics avaient investi plus tôt dans les transports régionaux, la dépendance à la voiture aurait été bien moins forte aujourd'hui. Mais avant qu'une alternative crédible n'existe partout, il serait injuste d'exiger de tous le même effort." },
    { label:"CONCLUSION", p:"Pour conclure, la voiture est indispensable là où rien ne la remplace, et superflue là où tout la remplace. Bien qu'elle soit devenue un symbole de liberté, elle n'est qu'un outil parmi d'autres. À condition que l'on développe de vraies alternatives, sa place se réduira d'elle-même. Au fond, mieux vaut offrir un choix que d'imposer une privation." },
  ]},
  { id:10, src:"texte", theme:"imm", q:"Faut-il s'intégrer dans la culture du pays d'accueil ou préserver sa propre culture ?", qFa:"باید در فرهنگِ کشور میزبان ادغام شد یا فرهنگِ خود را حفظ کرد؟", paras:[
    { label:"INTRODUCTION", p:"Avec l'augmentation des flux migratoires et la diversité croissante des sociétés, la question de l'intégration culturelle suscite de nombreux débats. Il est légitime de se demander s'il faut adopter la culture du pays d'accueil ou préserver la sienne. Certains posent la question comme un choix, et c'est précisément là que je ne les suis pas. Je suis convaincu qu'il ne s'agit pas de choisir, mais d'articuler les deux. Et cela pour trois raisons." },
    { label:"ARGUMENT 1", p:"D'emblée, il convient de rappeler que s'intégrer n'est pas se dissoudre. En effet, comprendre les codes d'un pays, ses horaires, sa façon de dire non, relève de la simple efficacité sociale. Par exemple, quelqu'un qui refuse d'apprendre ces codes se heurtera tôt ou tard à des malentendus qu'il aurait pu éviter. Si vous acceptez d'observer avant de juger, vous gagnerez des années. Il faut donc que cet apprentissage soit vu comme un outil, non comme un reniement." },
    { label:"ARGUMENT 2", p:"En deuxième lieu, j'estime que la culture d'origine reste une ressource, et non un poids. Cela s'explique aisément : elle donne un point de comparaison dont les natifs ne disposent pas. Ainsi, une personne élevée dans deux systèmes de valeurs repère souvent des évidences que les autres ne voient plus. Après avoir vécu ailleurs, on ne regarde plus jamais son propre pays de la même façon. Ce qui compte, ce n'est donc pas de trancher : c'est de savoir passer d'un registre à l'autre." },
    { label:"ARGUMENT 3", p:"Un dernier élément mérite d'être pris en considération : les enfants. À titre d'exemple, un enfant à qui l'on interdit la langue de ses parents perd un lien qu'il mettra des années à reconstruire. En revanche, celui qui grandit avec les deux langues acquiert une souplesse dont il tirera profit toute sa vie. Il ne s'agit pas de nostalgie, mais de transmission." },
    { label:"CONTRE-ARGUMENT", p:"Cela dit, je ne prétends pas que l'équilibre soit facile. Ceux qui défendent la position inverse rappellent qu'une communauté trop fermée finit par s'isoler, et que certains n'apprennent jamais la langue du pays où ils vivent. Leur argument tient debout. Si les politiques d'accueil avaient été plus ambitieuses dans les années 1990, beaucoup de ces situations auraient pu être évitées. Mais avant que l'on ne demande aux nouveaux arrivants de tout abandonner, il faudrait s'assurer qu'on leur offre autre chose en échange." },
    { label:"CONCLUSION", p:"Pour conclure, l'articulation des deux cultures l'emporte largement sur le choix de l'une contre l'autre. Bien qu'elle demande un effort constant, elle produit des personnes plus solides et non plus divisées. À condition que le pays d'accueil joue aussi son rôle, cet équilibre est parfaitement tenable. Au fond, on ne s'intègre pas en s'effaçant : on s'intègre en ajoutant." },
  ]},
];
